/**
 * Runs the real yt-dlp with the arguments we build. Opt-in, because it needs
 * the network and real binaries:
 *
 *   VIDSNARE_YTDLP=/path/to/yt-dlp [VIDSNARE_FFMPEG=/path/to/ffmpeg] npm test
 */
import { spawnSync } from 'node:child_process'
import { existsSync, mkdtempSync, rmSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { afterAll, describe, expect, it } from 'vitest'
import { classifyError } from './errors'
import { parseLine, type YtdlpEvent } from './progress'
import { buildDownloadArgs, buildInfoArgs } from './ytdlp-args'

const ytdlp = process.env['VIDSNARE_YTDLP']
const ffmpeg = process.env['VIDSNARE_FFMPEG']
const deno = process.env['VIDSNARE_DENO']
const tools = { ffmpeg, deno }
// "Me at the zoo": the first YouTube video, 19 seconds long.
const URL = 'https://www.youtube.com/watch?v=jNQXAC9IVRw'

describe.runIf(ytdlp)('yt-dlp integration', () => {
  const dir = mkdtempSync(join(tmpdir(), 'vidsnare-it-'))
  afterAll(() => rmSync(dir, { recursive: true, force: true }))

  const run = (args: string[]) => spawnSync(ytdlp!, args, { encoding: 'utf8', timeout: 120_000 })

  it('reads video metadata', () => {
    const result = run(buildInfoArgs(URL, tools))
    expect(result.status, result.stderr).toBe(0)
    const info = JSON.parse(result.stdout)
    expect(info.id).toBe('jNQXAC9IVRw')
    expect(info.title).toBeTruthy()
    expect(info.duration).toBeGreaterThan(0)
  })

  it.runIf(ffmpeg)('downloads audio and reports progress and the final path', () => {
    const result = run(
      buildDownloadArgs({
        url: URL,
        outputDir: dir,
        fileBase: 'zoo [jNQXAC9IVRw]',
        tools,
        options: {
          kind: 'audio',
          quality: 'best',
          container: 'mp4',
          audioFormat: 'mp3',
          subtitles: { enabled: false, languages: [], includeAutoGenerated: false, embed: false }
        }
      })
    )
    expect(result.status, result.stderr).toBe(0)
    // Progress goes to stdout but post-processing messages go to stderr.
    const events = `${result.stdout}\n${result.stderr}`.split('\n').map(parseLine).filter((e): e is YtdlpEvent => e !== null)
    expect(events.some((e) => e.type === 'download' && e.status === 'finished')).toBe(true)
    expect(events.some((e) => e.type === 'postprocess' && e.name === 'ExtractAudio')).toBe(true)
    const file = events.find((e) => e.type === 'file')
    expect(file && file.type === 'file' && file.path.endsWith('zoo [jNQXAC9IVRw].mp3')).toBe(true)
    expect(existsSync(join(dir, 'zoo [jNQXAC9IVRw].mp3'))).toBe(true)
  })

  it.runIf(ffmpeg)('downloads 360p video with subtitles', () => {
    const result = run(
      buildDownloadArgs({
        url: URL,
        outputDir: dir,
        fileBase: 'zoo video',
        tools,
        options: {
          kind: 'video',
          quality: '360',
          container: 'mp4',
          audioFormat: 'mp3',
          subtitles: { enabled: true, languages: ['en'], includeAutoGenerated: false, embed: false }
        }
      })
    )
    expect(result.status, result.stderr).toBe(0)
    expect(existsSync(join(dir, 'zoo video.mp4'))).toBe(true)
  })

  it('explains an invalid video', () => {
    const result = run(buildInfoArgs('https://www.youtube.com/watch?v=aaaaaaaaaaa', tools))
    expect(result.status).not.toBe(0)
    expect(classifyError(result.stderr).code).toBe('VIDEO_UNAVAILABLE')
  })
})
