import type { DownloadOptions } from '@shared/download'
import { escapeOutputTemplate } from './filename'

/** Markers that let us tell our structured output apart from yt-dlp's own logging. */
export const MARK = {
  download: '__VS_DL__',
  postprocess: '__VS_PP__',
  file: '__VS_FILE__'
} as const

export interface ToolPaths {
  ffmpeg?: string
  deno?: string
}

export interface DownloadRequest {
  /** Canonical single-video URL. */
  url: string
  outputDir: string
  /** Already-sanitized file name without extension. */
  fileBase: string
  options: DownloadOptions
  tools: ToolPaths
  /** yt-dlp archive file; set when "skip already downloaded" is on. */
  archiveFile?: string
  /** Where partial files live until finished. */
  tempDir?: string
}

/** Flags every yt-dlp call gets: predictable, machine-readable and isolated from user configs. */
function baseArgs(tools: ToolPaths): string[] {
  const args = ['--ignore-config', '--no-plugin-dirs', '--color', 'never', '--no-playlist']
  if (tools.ffmpeg) args.push('--ffmpeg-location', tools.ffmpeg)
  if (tools.deno) args.push('--js-runtimes', `deno:${tools.deno}`)
  return args
}

/** Matches `en` and its regional variants (`en-GB`), but not auto-translations (`en-de`). */
export function subtitleLanguagePattern(code: string): string {
  const safe = code.trim().replace(/[^A-Za-z0-9-]/g, '')
  if (!safe) return ''
  return /-[A-Z]/.test(safe) ? safe : `${safe}(-[A-Z][A-Za-z]+)?`
}

function formatArgs(options: DownloadOptions): string[] {
  if (options.kind === 'audio') {
    const preferred = { mp3: 'ba/b', m4a: 'ba[ext=m4a]/ba/b', opus: 'ba[acodec=opus]/ba/b' }[options.audioFormat]
    return [
      '-f', preferred,
      '--extract-audio',
      '--audio-format', options.audioFormat,
      '--audio-quality', '0',
      '--embed-thumbnail',
      '--embed-metadata'
    ]
  }

  const args = ['-f', 'bv*+ba/b']
  // `res:N` prefers the largest resolution not above N (by the shorter side, so
  // vertical Shorts behave), falling back to larger only if nothing smaller exists.
  if (options.quality !== 'best') args.push('-S', `res:${options.quality}`)
  args.push(
    '--merge-output-format', options.container,
    '--remux-video', options.container,
    '--embed-metadata',
    '--embed-chapters'
  )
  return args
}

function subtitleArgs(options: DownloadOptions): string[] {
  const { subtitles } = options
  const langs = subtitles.languages.map(subtitleLanguagePattern).filter(Boolean)
  if (!subtitles.enabled || langs.length === 0) return []
  const args = ['--write-subs', '--sub-langs', langs.join(','), '--sub-format', 'srt/vtt/best', '--convert-subs', 'srt']
  if (subtitles.includeAutoGenerated) args.push('--write-auto-subs')
  if (subtitles.embed && options.kind === 'video') args.push('--embed-subs')
  return args
}

export function buildDownloadArgs(req: DownloadRequest): string[] {
  const args = [
    ...baseArgs(req.tools),
    '--newline',
    '--progress',
    '--no-simulate',
    '--windows-filenames',
    '--retries', '10',
    '--fragment-retries', '10',
    '-P', req.outputDir,
    ...(req.tempDir ? ['-P', `temp:${req.tempDir}`] : []),
    '-o', `${escapeOutputTemplate(req.fileBase)}.%(ext)s`,
    ...formatArgs(req.options),
    ...subtitleArgs(req.options),
    ...(req.archiveFile ? ['--download-archive', req.archiveFile] : []),
    '--progress-template',
    `download:${MARK.download} %(progress.status)s|%(progress.downloaded_bytes)s|%(progress.total_bytes)s|%(progress.total_bytes_estimate)s|%(progress.speed)s|%(progress.eta)s|%(info.format_id)s`,
    '--progress-template',
    `postprocess:${MARK.postprocess} %(progress.status)s|%(progress.postprocessor)s`,
    '--print',
    `after_move:${MARK.file} %(filepath)s`,
    // Everything after `--` is a URL, never an option, even if it starts with "-".
    '--',
    req.url
  ]
  return args
}

/** Fetch metadata as JSON. Playlists are listed flat (no per-video requests). */
export function buildInfoArgs(url: string, tools: ToolPaths): string[] {
  return [...baseArgs(tools), '--dump-single-json', '--flat-playlist', '--', url]
}

/** Remove the video from yt-dlp's archive (used by "download again"). */
export function archiveLine(videoId: string): string {
  return `youtube ${videoId}`
}
