import { describe, expect, it } from 'vitest'
import type { DownloadOptions } from '@shared/download'
import { buildDownloadArgs, buildInfoArgs, subtitleLanguagePattern, type DownloadRequest } from './ytdlp-args'

const video: DownloadOptions = {
  kind: 'video',
  quality: 'best',
  container: 'mp4',
  audioFormat: 'mp3',
  subtitles: { enabled: false, languages: [], includeAutoGenerated: false, embed: false }
}

function request(overrides: Partial<DownloadRequest> = {}, options: Partial<DownloadOptions> = {}): DownloadRequest {
  return {
    url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    outputDir: '/home/u/Downloads',
    fileBase: 'Title [dQw4w9WgXcQ]',
    options: { ...video, ...options },
    tools: { ffmpeg: '/opt/vs/ffmpeg', deno: '/opt/vs/deno' },
    ...overrides
  }
}

/** The value following `flag`, for flags that take one argument. */
function valueOf(args: string[], flag: string): string | undefined {
  const i = args.indexOf(flag)
  return i >= 0 ? args[i + 1] : undefined
}

describe('buildDownloadArgs', () => {
  it('ends with the URL after a `--` separator', () => {
    const args = buildDownloadArgs(request({ url: '-x --exec rm' }))
    expect(args.slice(-2)).toEqual(['--', '-x --exec rm'])
  })

  it('ignores user and system yt-dlp configs and plugins', () => {
    const args = buildDownloadArgs(request())
    expect(args).toContain('--ignore-config')
    expect(args).toContain('--no-plugin-dirs')
  })

  it('points yt-dlp at the bundled tools', () => {
    const args = buildDownloadArgs(request())
    expect(valueOf(args, '--ffmpeg-location')).toBe('/opt/vs/ffmpeg')
    expect(valueOf(args, '--js-runtimes')).toBe('deno:/opt/vs/deno')
  })

  it('omits tool flags when a tool is not available', () => {
    const args = buildDownloadArgs(request({ tools: {} }))
    expect(args).not.toContain('--ffmpeg-location')
    expect(args).not.toContain('--js-runtimes')
  })

  it('writes to the chosen folder with an escaped file name', () => {
    const args = buildDownloadArgs(request({ fileBase: '100% legit' }))
    expect(valueOf(args, '-P')).toBe('/home/u/Downloads')
    expect(valueOf(args, '-o')).toBe('100%% legit.%(ext)s')
  })

  it('uses a separate temp folder when given', () => {
    const args = buildDownloadArgs(request({ tempDir: '/tmp/vs' }))
    expect(args).toContain('temp:/tmp/vs')
  })

  it('prefers H.264 + AAC for MP4 so every player shows the video', () => {
    const args = buildDownloadArgs(request())
    expect(valueOf(args, '-f')).toBe('bv*+ba/b')
    expect(valueOf(args, '-S')).toBe('vcodec:h264,res,acodec:m4a')
    expect(valueOf(args, '--merge-output-format')).toBe('mp4')
    expect(valueOf(args, '--remux-video')).toBe('mp4')
  })

  it.each(['1080', '720', '480', '360'] as const)('caps MP4 resolution at %sp', (quality) => {
    const args = buildDownloadArgs(request({}, { quality }))
    expect(valueOf(args, '-S')).toBe(`vcodec:h264,res:${quality},acodec:m4a`)
  })

  it('takes the best streams in any codec for MKV', () => {
    const args = buildDownloadArgs(request({}, { container: 'mkv' }))
    expect(args).not.toContain('-S')
    expect(valueOf(args, '--merge-output-format')).toBe('mkv')
  })

  it('caps MKV resolution without preferring a codec', () => {
    const args = buildDownloadArgs(request({}, { container: 'mkv', quality: '720' }))
    expect(valueOf(args, '-S')).toBe('res:720')
  })

  it.each([
    ['mp3', 'ba/b'],
    ['m4a', 'ba[ext=m4a]/ba/b'],
    ['opus', 'ba[acodec=opus]/ba/b']
  ] as const)('extracts %s audio without needless re-encoding', (audioFormat, format) => {
    const args = buildDownloadArgs(request({}, { kind: 'audio', audioFormat }))
    expect(valueOf(args, '-f')).toBe(format)
    expect(args).toContain('--extract-audio')
    expect(valueOf(args, '--audio-format')).toBe(audioFormat)
    expect(args).toContain('--embed-thumbnail')
    expect(args).not.toContain('--merge-output-format')
  })

  it('adds no subtitle flags when subtitles are off', () => {
    const args = buildDownloadArgs(
      request({}, { subtitles: { enabled: false, languages: ['en'], includeAutoGenerated: true, embed: true } })
    )
    expect(args.some((a) => a.includes('sub'))).toBe(false)
  })

  it('downloads subtitles in the chosen languages', () => {
    const args = buildDownloadArgs(
      request({}, { subtitles: { enabled: true, languages: ['en', 'pt-BR'], includeAutoGenerated: true, embed: true } })
    )
    expect(args).toContain('--write-subs')
    expect(valueOf(args, '--sub-langs')).toBe('en(-[A-Z][A-Za-z]+)?,pt-BR')
    expect(valueOf(args, '--convert-subs')).toBe('srt')
    expect(args).toContain('--write-auto-subs')
    expect(args).toContain('--embed-subs')
  })

  it('never embeds subtitles into audio files', () => {
    const args = buildDownloadArgs(
      request({}, { kind: 'audio', subtitles: { enabled: true, languages: ['en'], includeAutoGenerated: false, embed: true } })
    )
    expect(args).toContain('--write-subs')
    expect(args).not.toContain('--embed-subs')
  })

  it('uses the archive only when skipping is enabled', () => {
    expect(buildDownloadArgs(request())).not.toContain('--download-archive')
    expect(valueOf(buildDownloadArgs(request({ archiveFile: '/data/archive.txt' })), '--download-archive')).toBe(
      '/data/archive.txt'
    )
  })

  it('asks for machine-readable progress and the final path', () => {
    const args = buildDownloadArgs(request())
    expect(args).toContain('--newline')
    expect(args).toContain('--no-simulate')
    expect(args.filter((a) => a === '--progress-template')).toHaveLength(2)
    expect(valueOf(args, '--print')).toMatch(/^after_move:__VS_FILE__ /)
  })
})

describe('buildInfoArgs', () => {
  it('dumps flat JSON for the URL', () => {
    const args = buildInfoArgs('https://www.youtube.com/playlist?list=PL123', {})
    expect(args).toContain('--dump-single-json')
    expect(args).toContain('--flat-playlist')
    expect(args.slice(-2)).toEqual(['--', 'https://www.youtube.com/playlist?list=PL123'])
  })
})

describe('subtitleLanguagePattern', () => {
  it('matches regional variants for a bare code', () => {
    const re = new RegExp(`^${subtitleLanguagePattern('en')}$`)
    expect(re.test('en')).toBe(true)
    expect(re.test('en-GB')).toBe(true)
    expect(re.test('en-de')).toBe(false)
    expect(re.test('es')).toBe(false)
  })

  it('keeps explicit regional codes as they are', () => {
    expect(subtitleLanguagePattern('pt-BR')).toBe('pt-BR')
  })

  it('strips characters that would change the regex', () => {
    expect(subtitleLanguagePattern('.*')).toBe('')
    expect(subtitleLanguagePattern('en|.*')).toBe('en(-[A-Z][A-Za-z]+)?')
  })
})
