import { AUDIO_FORMATS, VIDEO_CONTAINERS, VIDEO_QUALITIES, type DownloadOptions } from '@shared/download'
import { useI18n } from '../i18n'
import { SubtitleLanguages } from './SubtitleLanguages'

interface Props {
  options: DownloadOptions
  onChange: (options: DownloadOptions) => void
  /** Omit to hide the folder row (e.g. when editing defaults in Settings). */
  folder?: string
  onChooseFolder?: () => void
}

export function OptionsPanel({ options, onChange, folder, onChooseFolder }: Props): React.JSX.Element {
  const { t } = useI18n()
  const set = (patch: Partial<DownloadOptions>): void => onChange({ ...options, ...patch })
  const subs = options.subtitles

  return (
    <section className="options" aria-label={t('options.downloadAs')}>
      <div className="field">
        <span className="field-label">{t('options.downloadAs')}</span>
        <div className="segmented" role="radiogroup" aria-label={t('options.downloadAs')}>
          {(['video', 'audio'] as const).map((kind) => (
            <label key={kind} className={options.kind === kind ? 'active' : ''}>
              <input type="radio" name="kind" checked={options.kind === kind} onChange={() => set({ kind })} />
              {t(kind === 'video' ? 'options.video' : 'options.audio')}
            </label>
          ))}
        </div>
      </div>

      {options.kind === 'video' ? (
        <>
          <label className="field">
            <span className="field-label">{t('options.quality')}</span>
            <select value={options.quality} onChange={(e) => set({ quality: e.target.value as DownloadOptions['quality'] })}>
              {VIDEO_QUALITIES.map((q) => (
                <option key={q} value={q}>
                  {q === 'best' ? t('options.qualityBest') : `${q}p`}
                </option>
              ))}
            </select>
          </label>
          <label className="field">
            <span className="field-label">{t('options.container')}</span>
            <select
              value={options.container}
              onChange={(e) => set({ container: e.target.value as DownloadOptions['container'] })}
            >
              {VIDEO_CONTAINERS.map((c) => (
                <option key={c} value={c}>
                  {t(c === 'mp4' ? 'options.containerMp4' : 'options.containerMkv')}
                </option>
              ))}
            </select>
          </label>
        </>
      ) : (
        <label className="field">
          <span className="field-label">{t('options.audioFormat')}</span>
          <select
            value={options.audioFormat}
            onChange={(e) => set({ audioFormat: e.target.value as DownloadOptions['audioFormat'] })}
          >
            {AUDIO_FORMATS.map((f) => (
              <option key={f} value={f}>
                {f === 'opus' ? 'Opus' : f.toUpperCase()}
              </option>
            ))}
          </select>
        </label>
      )}

      <div className="field field-wide">
        <label className="checkbox">
          <input
            type="checkbox"
            checked={subs.enabled}
            onChange={(e) => set({ subtitles: { ...subs, enabled: e.target.checked } })}
          />
          {t('options.subtitlesEnabled')}
        </label>
        {subs.enabled && (
          <div className="subtitle-options">
            <SubtitleLanguages
              value={subs.languages}
              onChange={(languages) => set({ subtitles: { ...subs, languages } })}
            />
            <label className="checkbox">
              <input
                type="checkbox"
                checked={subs.includeAutoGenerated}
                onChange={(e) => set({ subtitles: { ...subs, includeAutoGenerated: e.target.checked } })}
              />
              {t('options.autoSubs')}
            </label>
            {options.kind === 'video' && (
              <label className="checkbox">
                <input
                  type="checkbox"
                  checked={subs.embed}
                  onChange={(e) => set({ subtitles: { ...subs, embed: e.target.checked } })}
                />
                {t('options.embedSubs')}
              </label>
            )}
          </div>
        )}
      </div>

      {folder !== undefined && onChooseFolder && (
      <div className="field field-wide">
        <span className="field-label">{t('options.saveTo')}</span>
        <div className="folder">
          <span className="folder-path" title={folder}>
            <bdi>{folder}</bdi>
          </span>
          <button type="button" className="btn" onClick={onChooseFolder}>
            {t('common.changeFolder')}
          </button>
        </div>
      </div>
      )}
    </section>
  )
}
