/** User-facing download choices. Shared by the UI and the main process. */

export type MediaKind = 'video' | 'audio'
export type VideoQuality = 'best' | '1080' | '720' | '480' | '360'
export type AudioFormat = 'mp3' | 'm4a' | 'opus'
export type VideoContainer = 'mp4' | 'mkv'

export const VIDEO_QUALITIES: readonly VideoQuality[] = ['best', '1080', '720', '480', '360']
export const AUDIO_FORMATS: readonly AudioFormat[] = ['mp3', 'm4a', 'opus']
export const VIDEO_CONTAINERS: readonly VideoContainer[] = ['mp4', 'mkv']

export interface SubtitleOptions {
  enabled: boolean
  /** Language codes such as `en`, `pl` or `pt-BR`. */
  languages: string[]
  /** Also use YouTube's automatic captions when no human-made track exists. */
  includeAutoGenerated: boolean
  /** Put subtitles inside the video file instead of next to it (video only). */
  embed: boolean
}

export interface DownloadOptions {
  kind: MediaKind
  quality: VideoQuality
  container: VideoContainer
  audioFormat: AudioFormat
  subtitles: SubtitleOptions
}
