import { describe, expect, it } from 'vitest'
import { DEFAULT_SETTINGS, normalizeDownloadOptions, normalizeSettings } from './settings'

describe('normalizeSettings', () => {
  it('returns defaults for garbage', () => {
    expect(normalizeSettings(null)).toEqual(DEFAULT_SETTINGS)
    expect(normalizeSettings('nope')).toEqual(DEFAULT_SETTINGS)
    expect(normalizeSettings([1, 2])).toEqual(DEFAULT_SETTINGS)
  })

  it('keeps valid values', () => {
    const s = normalizeSettings({ maxConcurrent: 5, theme: 'dark', language: 'pt-BR', skipDownloaded: false })
    expect(s).toMatchObject({ maxConcurrent: 5, theme: 'dark', language: 'pt-BR', skipDownloaded: false })
  })

  it('clamps the number of simultaneous downloads', () => {
    expect(normalizeSettings({ maxConcurrent: 0 }).maxConcurrent).toBe(1)
    expect(normalizeSettings({ maxConcurrent: 99 }).maxConcurrent).toBe(8)
    expect(normalizeSettings({ maxConcurrent: 2.5 }).maxConcurrent).toBe(3)
    expect(normalizeSettings({ maxConcurrent: '4' }).maxConcurrent).toBe(4)
  })

  it('rejects unknown enum values', () => {
    expect(normalizeSettings({ theme: 'purple', language: 'xx' })).toMatchObject({ theme: 'system', language: 'system' })
  })

  it('drops settings that no longer exist', () => {
    expect(normalizeSettings({ filenameTemplate: '{channel}' })).not.toHaveProperty('filenameTemplate')
  })

  it('applies a partial update on top of current settings', () => {
    const current = normalizeSettings({ maxConcurrent: 6, theme: 'light' })
    expect(normalizeSettings({ ...current, theme: 'dark' }, current)).toMatchObject({ maxConcurrent: 6, theme: 'dark' })
  })
})

describe('normalizeDownloadOptions', () => {
  it('validates every field', () => {
    expect(
      normalizeDownloadOptions({
        kind: 'audio',
        quality: '4320',
        container: 'avi',
        audioFormat: 'opus',
        subtitles: { enabled: true, languages: ['en', 'pt-BR', 'en', '../../x', 42], embed: 'yes' }
      })
    ).toEqual({
      kind: 'audio',
      quality: 'best',
      container: 'mp4',
      audioFormat: 'opus',
      subtitles: { enabled: true, languages: ['en', 'pt-BR'], includeAutoGenerated: false, embed: true }
    })
  })
})
