import {
  AUDIO_FORMATS,
  VIDEO_CONTAINERS,
  VIDEO_QUALITIES,
  type DownloadOptions,
  type SubtitleOptions
} from './download'
import { isLocale, type Locale } from './i18n'

export type ThemeSetting = 'system' | 'light' | 'dark'
export type LanguageSetting = Locale | 'system'

export interface Settings {
  /** Empty means the system Downloads folder. */
  downloadDir: string
  maxConcurrent: number
  skipDownloaded: boolean
  playlistSubfolder: boolean
  notifications: boolean
  language: LanguageSetting
  theme: ThemeSetting
  defaults: DownloadOptions
}

export const MAX_CONCURRENT_LIMIT = 8

export const DEFAULT_SETTINGS: Settings = {
  downloadDir: '',
  maxConcurrent: 3,
  skipDownloaded: true,
  playlistSubfolder: true,
  notifications: true,
  language: 'system',
  theme: 'system',
  defaults: {
    kind: 'video',
    quality: 'best',
    container: 'mp4',
    audioFormat: 'mp3',
    subtitles: { enabled: false, languages: [], includeAutoGenerated: false, embed: true }
  }
}

const LANGUAGE_CODE = /^[A-Za-z]{2,3}(-[A-Za-z0-9]{2,8})?$/

function oneOf<T extends string>(value: unknown, allowed: readonly T[], fallback: T): T {
  return typeof value === 'string' && (allowed as readonly string[]).includes(value) ? (value as T) : fallback
}

function bool(value: unknown, fallback: boolean): boolean {
  return typeof value === 'boolean' ? value : fallback
}

function obj(value: unknown): Record<string, unknown> {
  return value && typeof value === 'object' && !Array.isArray(value) ? (value as Record<string, unknown>) : {}
}

export function normalizeSubtitles(raw: unknown, fallback: SubtitleOptions): SubtitleOptions {
  const s = obj(raw)
  const languages = Array.isArray(s['languages'])
    ? [...new Set(s['languages'].filter((l): l is string => typeof l === 'string' && LANGUAGE_CODE.test(l)))].slice(0, 20)
    : fallback.languages
  return {
    enabled: bool(s['enabled'], fallback.enabled),
    languages,
    includeAutoGenerated: bool(s['includeAutoGenerated'], fallback.includeAutoGenerated),
    embed: bool(s['embed'], fallback.embed)
  }
}

export function normalizeDownloadOptions(raw: unknown, fallback: DownloadOptions = DEFAULT_SETTINGS.defaults): DownloadOptions {
  const o = obj(raw)
  return {
    kind: oneOf(o['kind'], ['video', 'audio'] as const, fallback.kind),
    quality: oneOf(o['quality'], VIDEO_QUALITIES, fallback.quality),
    container: oneOf(o['container'], VIDEO_CONTAINERS, fallback.container),
    audioFormat: oneOf(o['audioFormat'], AUDIO_FORMATS, fallback.audioFormat),
    subtitles: normalizeSubtitles(o['subtitles'], fallback.subtitles)
  }
}

/** Accepts anything (an old or hand-edited file, a renderer request) and returns valid settings. */
export function normalizeSettings(raw: unknown, base: Settings = DEFAULT_SETTINGS): Settings {
  const s = obj(raw)
  const concurrent = Number(s['maxConcurrent'])
  return {
    downloadDir: typeof s['downloadDir'] === 'string' ? s['downloadDir'] : base.downloadDir,
    maxConcurrent: Number.isInteger(concurrent)
      ? Math.min(MAX_CONCURRENT_LIMIT, Math.max(1, concurrent))
      : base.maxConcurrent,
    skipDownloaded: bool(s['skipDownloaded'], base.skipDownloaded),
    playlistSubfolder: bool(s['playlistSubfolder'], base.playlistSubfolder),
    notifications: bool(s['notifications'], base.notifications),
    language: s['language'] === 'system' || isLocale(s['language']) ? (s['language'] as LanguageSetting) : base.language,
    theme: oneOf(s['theme'], ['system', 'light', 'dark'] as const, base.theme),
    defaults: normalizeDownloadOptions(s['defaults'], base.defaults)
  }
}
