// A stand-in for the real preload API that answers with made-up example data,
// so screenshots show the real interface without anyone else's videos.
const { contextBridge } = require('electron')

const theme = process.env.SHOT_THEME || 'light'
const language = process.env.SHOT_LANG || 'en'

function thumb(a, b, shape) {
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 320 180"><defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="${a}"/><stop offset="1" stop-color="${b}"/></linearGradient></defs><rect width="320" height="180" fill="url(#g)"/>${shape}</svg>`
  return 'data:image/svg+xml;base64,' + Buffer.from(svg).toString('base64')
}
const THUMBS = [
  thumb('#f6d365', '#fda085', '<circle cx="230" cy="70" r="34" fill="#fff8" /><path d="M0 150 L90 90 L160 140 L230 100 L320 150 V180 H0Z" fill="#7a3e2a99"/>'),
  thumb('#84fab0', '#8fd3f4', '<path d="M0 120 Q80 80 160 120 T320 120 V180 H0Z" fill="#1e6f8a88"/>'),
  thumb('#a18cd1', '#fbc2eb', '<rect x="120" y="55" width="80" height="70" rx="10" fill="#ffffff99"/>'),
  thumb('#30cfd0', '#330867', '<circle cx="90" cy="60" r="3" fill="#fff"/><circle cx="200" cy="40" r="2" fill="#fff"/><circle cx="260" cy="90" r="3" fill="#fff"/>'),
  thumb('#43e97b', '#38f9d7', '<path d="M60 150 L110 60 L160 150Z M150 150 L210 40 L270 150Z" fill="#14532d88"/>'),
  thumb('#fa709a', '#fee140', '<circle cx="160" cy="90" r="40" fill="#ffffff88"/>')
]
const TITLES = [
  'Sunrise Timelapse over the Mountains',
  'Learn Guitar Chords in 10 Minutes',
  'Easy Homemade Bread Recipe',
  'A Night Under the Stars (4K)',
  'Hiking the Northern Ridge Trail',
  'Relaxing Piano for Focus and Study'
]
const entries = TITLES.map((title, i) => ({
  id: `example${String(i).padStart(4, '0')}`,
  title,
  channel: 'Example Channel',
  duration: [312, 645, 498, 3605, 1203, 2710][i],
  thumbnail: THUMBS[i],
  url: '',
  available: true,
  live: false,
  uploadDate: null,
  index: i + 1,
  downloaded: i === 4
}))

const settings = {
  downloadDir: '',
  maxConcurrent: 3,
  skipDownloaded: true,
  playlistSubfolder: true,
  notifications: true,
  language,
  theme,
  defaults: {
    kind: 'video',
    quality: 'best',
    container: 'mp4',
    audioFormat: 'mp3',
    subtitles: { enabled: false, languages: [], includeAutoGenerated: false, embed: true }
  }
}

const job = (i, status, progress, extra = {}) => ({
  id: `job${i}`,
  videoId: entries[i].id,
  title: entries[i].title,
  channel: 'Example Channel',
  thumbnail: THUMBS[i],
  duration: entries[i].duration,
  options: settings.defaults,
  outputDir: '/home/you/Downloads',
  status,
  progress,
  error: null,
  filePath: status === 'completed' ? `/home/you/Downloads/${entries[i].title}.mp4` : null,
  addedAt: 0,
  finishedAt: null,
  ...extra
})
const jobs = [
  job(0, 'downloading', { fraction: 0.62, downloadedBytes: 81_400_000, totalBytes: 131_300_000, speed: 6_200_000, eta: 8 }),
  job(1, 'downloading', { fraction: 0.27, downloadedBytes: 24_100_000, totalBytes: 89_200_000, speed: 4_800_000, eta: 14 }),
  job(2, 'processing', { fraction: 1, downloadedBytes: 64_000_000, totalBytes: 64_000_000, speed: null, eta: null }),
  job(3, 'queued', null),
  job(5, 'completed', { fraction: 1, downloadedBytes: 38_900_000, totalBytes: 38_900_000, speed: null, eta: null })
]

const answers = {
  'app:get-info': { name: 'VidSnare', version: process.env.SHOT_VERSION || '0.1.0', platform: 'linux' },
  'settings:get': settings,
  'settings:update': settings,
  'queue:list': jobs,
  'queue:default-folder': '/home/you/Downloads',
  'tools:get-status': { ytdlp: { version: '2026.08.19', source: 'bundled' }, ffmpeg: null, deno: null, lastCheck: Date.now() },
  'update:get-status': { state: 'idle', mode: 'disabled' },
  'history:list': [],
  'app:read-clipboard': '',
  'media:fetch-info': {
    ok: true,
    preview: { kind: 'playlist', id: 'PLexample', title: 'Weekend Favourites', channel: 'Example Channel', thumbnail: THUMBS[0], entries }
  }
}

contextBridge.exposeInMainWorld('vidsnare', {
  invoke: async (channel) => answers[channel],
  on: () => () => {}
})
