// Website text in every language. Keys and {placeholders} must match English
// (checked by tests/website.test.ts).
export const STRINGS = {
  en: {
    title: 'VidSnare – download videos and audio from YouTube',
    tagline: 'Download videos and music from YouTube. Simply.',
    lead: 'Paste a link, choose the quality, and VidSnare does the rest. Free for personal use on Windows and Linux.',
    downloadFor: 'Download for {os}',
    otherDownloads: 'Other downloads',
    version: 'Version {version}',
    comingSoon: 'The first release is coming soon.',
    onlyWinLinux: 'VidSnare is available for Windows and Linux.',
    fileWindows: 'Windows 10 and 11 – installer',
    fileAppImage: 'Linux – AppImage, any distribution',
    fileDeb: 'Linux – Debian / Ubuntu package',
    featuresTitle: 'What it does',
    f1Title: 'Playlists and channels',
    f1: 'Load a whole playlist or channel and pick exactly which videos you want.',
    f2Title: 'Video or audio',
    f2: 'Video up to 4K, or just the sound as MP3, M4A or Opus.',
    f3Title: 'Subtitles',
    f3: 'Get subtitles in the languages you choose, saved or built into the video.',
    f4Title: 'Download queue',
    f4: 'Several downloads at once, with progress, speed and time left.',
    f5Title: 'Always up to date',
    f5: 'VidSnare and its download engine update themselves automatically.',
    f6Title: 'Your language',
    f6: 'Available in eight languages, with light and dark themes.',
    shotDownload: 'Choosing videos from a playlist',
    shotQueue: 'The download queue',
    installTitle: 'Installing',
    installWindows: 'Windows may say “unknown publisher” the first time, because VidSnare is not code-signed yet. Click “More info”, then “Run anyway”.',
    installLinux: 'For the AppImage, allow it to run as a program (right-click → Properties → Permissions), then open it.',
    disclaimer:
      "You are responsible for complying with YouTube's Terms of Service and copyright law. Only download content you have the right to download.",
    license: 'Free for personal, non-commercial use.',
    source: 'Source code',
    notAffiliated: 'Not affiliated with YouTube or Google.',
    language: 'Language'
  },
  pl: {
    title: 'VidSnare – pobieraj filmy i dźwięk z YouTube',
    tagline: 'Pobieraj filmy i muzykę z YouTube. Po prostu.',
    lead: 'Wklej link, wybierz jakość, a VidSnare zrobi resztę. Bezpłatny do użytku osobistego na Windows i Linux.',
    downloadFor: 'Pobierz na {os}',
    otherDownloads: 'Inne wersje',
    version: 'Wersja {version}',
    comingSoon: 'Pierwsze wydanie już wkrótce.',
    onlyWinLinux: 'VidSnare jest dostępny na Windows i Linux.',
    fileWindows: 'Windows 10 i 11 – instalator',
    fileAppImage: 'Linux – AppImage, dowolna dystrybucja',
    fileDeb: 'Linux – pakiet Debian / Ubuntu',
    featuresTitle: 'Co potrafi',
    f1Title: 'Playlisty i kanały',
    f1: 'Wczytaj całą playlistę lub kanał i wybierz dokładnie te filmy, których chcesz.',
    f2Title: 'Wideo lub dźwięk',
    f2: 'Wideo do 4K albo sam dźwięk jako MP3, M4A lub Opus.',
    f3Title: 'Napisy',
    f3: 'Pobieraj napisy w wybranych językach – jako pliki lub wbudowane w wideo.',
    f4Title: 'Kolejka pobierania',
    f4: 'Kilka pobrań naraz, z postępem, prędkością i pozostałym czasem.',
    f5Title: 'Zawsze aktualny',
    f5: 'VidSnare i jego silnik pobierania aktualizują się automatycznie.',
    f6Title: 'Twój język',
    f6: 'Dostępny w ośmiu językach, z jasnym i ciemnym motywem.',
    shotDownload: 'Wybieranie filmów z playlisty',
    shotQueue: 'Kolejka pobierania',
    installTitle: 'Instalacja',
    installWindows: 'Windows może za pierwszym razem pokazać „nieznany wydawca”, bo VidSnare nie jest jeszcze podpisany cyfrowo. Kliknij „Więcej informacji”, a potem „Uruchom mimo to”.',
    installLinux: 'Dla AppImage zezwól na uruchamianie jako program (prawy przycisk → Właściwości → Uprawnienia), a potem go otwórz.',
    disclaimer:
      'Odpowiadasz za przestrzeganie Warunków korzystania z YouTube i prawa autorskiego. Pobieraj tylko treści, do których masz prawo.',
    license: 'Bezpłatny do użytku osobistego, niekomercyjnego.',
    source: 'Kod źródłowy',
    notAffiliated: 'Niepowiązany z YouTube ani Google.',
    language: 'Język'
  },
  de: {
    title: 'VidSnare – Videos und Audio von YouTube herunterladen',
    tagline: 'Videos und Musik von YouTube herunterladen. Ganz einfach.',
    lead: 'Link einfügen, Qualität wählen – VidSnare erledigt den Rest. Kostenlos für den privaten Gebrauch unter Windows und Linux.',
    downloadFor: 'Für {os} herunterladen',
    otherDownloads: 'Weitere Downloads',
    version: 'Version {version}',
    comingSoon: 'Die erste Version erscheint bald.',
    onlyWinLinux: 'VidSnare gibt es für Windows und Linux.',
    fileWindows: 'Windows 10 und 11 – Installer',
    fileAppImage: 'Linux – AppImage, jede Distribution',
    fileDeb: 'Linux – Debian-/Ubuntu-Paket',
    featuresTitle: 'Was es kann',
    f1Title: 'Playlists und Kanäle',
    f1: 'Lade eine ganze Playlist oder einen Kanal und wähle genau die Videos aus, die du willst.',
    f2Title: 'Video oder Audio',
    f2: 'Video bis 4K oder nur der Ton als MP3, M4A oder Opus.',
    f3Title: 'Untertitel',
    f3: 'Untertitel in den gewünschten Sprachen – als Datei oder im Video.',
    f4Title: 'Download-Warteschlange',
    f4: 'Mehrere Downloads gleichzeitig, mit Fortschritt, Geschwindigkeit und Restzeit.',
    f5Title: 'Immer aktuell',
    f5: 'VidSnare und seine Download-Engine aktualisieren sich automatisch.',
    f6Title: 'Deine Sprache',
    f6: 'In acht Sprachen verfügbar, mit hellem und dunklem Design.',
    shotDownload: 'Videos aus einer Playlist auswählen',
    shotQueue: 'Die Download-Warteschlange',
    installTitle: 'Installation',
    installWindows: 'Windows meldet beim ersten Mal eventuell „Unbekannter Herausgeber“, weil VidSnare noch nicht signiert ist. Klicke auf „Weitere Informationen“ und dann auf „Trotzdem ausführen“.',
    installLinux: 'Erlaube beim AppImage die Ausführung als Programm (Rechtsklick → Eigenschaften → Berechtigungen) und öffne es dann.',
    disclaimer:
      'Du bist dafür verantwortlich, die Nutzungsbedingungen von YouTube und das Urheberrecht einzuhalten. Lade nur Inhalte herunter, zu deren Download du berechtigt bist.',
    license: 'Kostenlos für private, nicht-kommerzielle Nutzung.',
    source: 'Quellcode',
    notAffiliated: 'Nicht mit YouTube oder Google verbunden.',
    language: 'Sprache'
  },
  es: {
    title: 'VidSnare – descarga vídeos y audio de YouTube',
    tagline: 'Descarga vídeos y música de YouTube. Así de fácil.',
    lead: 'Pega un enlace, elige la calidad y VidSnare hace el resto. Gratis para uso personal en Windows y Linux.',
    downloadFor: 'Descargar para {os}',
    otherDownloads: 'Otras descargas',
    version: 'Versión {version}',
    comingSoon: 'La primera versión llegará pronto.',
    onlyWinLinux: 'VidSnare está disponible para Windows y Linux.',
    fileWindows: 'Windows 10 y 11 – instalador',
    fileAppImage: 'Linux – AppImage, cualquier distribución',
    fileDeb: 'Linux – paquete Debian / Ubuntu',
    featuresTitle: 'Qué hace',
    f1Title: 'Listas y canales',
    f1: 'Carga una lista de reproducción o un canal entero y elige exactamente los vídeos que quieres.',
    f2Title: 'Vídeo o audio',
    f2: 'Vídeo hasta 4K, o solo el sonido en MP3, M4A u Opus.',
    f3Title: 'Subtítulos',
    f3: 'Subtítulos en los idiomas que elijas, como archivo o dentro del vídeo.',
    f4Title: 'Cola de descargas',
    f4: 'Varias descargas a la vez, con progreso, velocidad y tiempo restante.',
    f5Title: 'Siempre actualizado',
    f5: 'VidSnare y su motor de descarga se actualizan solos.',
    f6Title: 'Tu idioma',
    f6: 'Disponible en ocho idiomas, con tema claro y oscuro.',
    shotDownload: 'Eligiendo vídeos de una lista',
    shotQueue: 'La cola de descargas',
    installTitle: 'Instalación',
    installWindows: 'Windows puede mostrar «editor desconocido» la primera vez, porque VidSnare aún no está firmado. Haz clic en «Más información» y luego en «Ejecutar de todas formas».',
    installLinux: 'Para el AppImage, permite ejecutarlo como programa (clic derecho → Propiedades → Permisos) y ábrelo.',
    disclaimer:
      'Eres responsable de cumplir las Condiciones de servicio de YouTube y las leyes de derechos de autor. Descarga solo contenido que tengas derecho a descargar.',
    license: 'Gratis para uso personal y no comercial.',
    source: 'Código fuente',
    notAffiliated: 'Sin relación con YouTube ni Google.',
    language: 'Idioma'
  },
  'pt-BR': {
    title: 'VidSnare – baixe vídeos e áudio do YouTube',
    tagline: 'Baixe vídeos e músicas do YouTube. Simples assim.',
    lead: 'Cole um link, escolha a qualidade e o VidSnare faz o resto. Grátis para uso pessoal no Windows e no Linux.',
    downloadFor: 'Baixar para {os}',
    otherDownloads: 'Outros downloads',
    version: 'Versão {version}',
    comingSoon: 'A primeira versão chega em breve.',
    onlyWinLinux: 'O VidSnare está disponível para Windows e Linux.',
    fileWindows: 'Windows 10 e 11 – instalador',
    fileAppImage: 'Linux – AppImage, qualquer distribuição',
    fileDeb: 'Linux – pacote Debian / Ubuntu',
    featuresTitle: 'O que ele faz',
    f1Title: 'Playlists e canais',
    f1: 'Carregue uma playlist ou um canal inteiro e escolha exatamente os vídeos que quer.',
    f2Title: 'Vídeo ou áudio',
    f2: 'Vídeo em até 4K, ou só o som em MP3, M4A ou Opus.',
    f3Title: 'Legendas',
    f3: 'Legendas nos idiomas que você escolher, em arquivo ou dentro do vídeo.',
    f4Title: 'Fila de downloads',
    f4: 'Vários downloads ao mesmo tempo, com progresso, velocidade e tempo restante.',
    f5Title: 'Sempre atualizado',
    f5: 'O VidSnare e seu mecanismo de download se atualizam sozinhos.',
    f6Title: 'Seu idioma',
    f6: 'Disponível em oito idiomas, com tema claro e escuro.',
    shotDownload: 'Escolhendo vídeos de uma playlist',
    shotQueue: 'A fila de downloads',
    installTitle: 'Instalação',
    installWindows: 'Na primeira vez, o Windows pode mostrar “editor desconhecido”, porque o VidSnare ainda não é assinado. Clique em “Mais informações” e depois em “Executar assim mesmo”.',
    installLinux: 'Para o AppImage, permita executá-lo como programa (botão direito → Propriedades → Permissões) e abra-o.',
    disclaimer:
      'Você é responsável por cumprir os Termos de Serviço do YouTube e as leis de direitos autorais. Baixe apenas conteúdo que você tem o direito de baixar.',
    license: 'Grátis para uso pessoal e não comercial.',
    source: 'Código-fonte',
    notAffiliated: 'Sem vínculo com o YouTube ou o Google.',
    language: 'Idioma'
  },
  ru: {
    title: 'VidSnare – скачивайте видео и аудио с YouTube',
    tagline: 'Скачивайте видео и музыку с YouTube. Просто.',
    lead: 'Вставьте ссылку, выберите качество – остальное сделает VidSnare. Бесплатно для личного использования на Windows и Linux.',
    downloadFor: 'Скачать для {os}',
    otherDownloads: 'Другие версии',
    version: 'Версия {version}',
    comingSoon: 'Первый выпуск скоро появится.',
    onlyWinLinux: 'VidSnare доступен для Windows и Linux.',
    fileWindows: 'Windows 10 и 11 – установщик',
    fileAppImage: 'Linux – AppImage, любой дистрибутив',
    fileDeb: 'Linux – пакет Debian / Ubuntu',
    featuresTitle: 'Возможности',
    f1Title: 'Плейлисты и каналы',
    f1: 'Загрузите весь плейлист или канал и выберите именно те видео, которые нужны.',
    f2Title: 'Видео или аудио',
    f2: 'Видео до 4K или только звук в MP3, M4A или Opus.',
    f3Title: 'Субтитры',
    f3: 'Субтитры на выбранных языках – отдельным файлом или внутри видео.',
    f4Title: 'Очередь загрузок',
    f4: 'Несколько загрузок одновременно, с прогрессом, скоростью и оставшимся временем.',
    f5Title: 'Всегда актуален',
    f5: 'VidSnare и его движок загрузки обновляются автоматически.',
    f6Title: 'Ваш язык',
    f6: 'Доступен на восьми языках, со светлой и тёмной темой.',
    shotDownload: 'Выбор видео из плейлиста',
    shotQueue: 'Очередь загрузок',
    installTitle: 'Установка',
    installWindows: 'При первом запуске Windows может показать «Неизвестный издатель», так как у VidSnare пока нет цифровой подписи. Нажмите «Подробнее», затем «Выполнить в любом случае».',
    installLinux: 'Для AppImage разрешите запуск как программы (правый клик → Свойства → Права), затем откройте его.',
    disclaimer:
      'Вы несёте ответственность за соблюдение Условий использования YouTube и авторского права. Скачивайте только то, на что у вас есть права.',
    license: 'Бесплатно для личного некоммерческого использования.',
    source: 'Исходный код',
    notAffiliated: 'Не связан с YouTube или Google.',
    language: 'Язык'
  },
  ja: {
    title: 'VidSnare – YouTube の動画と音声をダウンロード',
    tagline: 'YouTube の動画と音楽を、かんたんにダウンロード。',
    lead: 'リンクを貼り付けて画質を選ぶだけ。あとは VidSnare におまかせ。Windows と Linux で、個人利用は無料です。',
    downloadFor: '{os} 版をダウンロード',
    otherDownloads: 'その他のダウンロード',
    version: 'バージョン {version}',
    comingSoon: '最初のリリースはまもなく公開予定です。',
    onlyWinLinux: 'VidSnare は Windows と Linux に対応しています。',
    fileWindows: 'Windows 10 / 11 – インストーラー',
    fileAppImage: 'Linux – AppImage（すべてのディストリビューション）',
    fileDeb: 'Linux – Debian / Ubuntu パッケージ',
    featuresTitle: 'できること',
    f1Title: '再生リストとチャンネル',
    f1: '再生リストやチャンネルをまるごと読み込み、欲しい動画だけを選べます。',
    f2Title: '動画または音声',
    f2: '最大 4K の動画、または音声のみを MP3・M4A・Opus で保存。',
    f3Title: '字幕',
    f3: '選んだ言語の字幕を、ファイルとして、または動画に埋め込んで保存。',
    f4Title: 'ダウンロードキュー',
    f4: '複数を同時にダウンロード。進行状況・速度・残り時間を表示します。',
    f5Title: 'いつも最新',
    f5: 'VidSnare とダウンロードエンジンは自動で更新されます。',
    f6Title: 'あなたの言語で',
    f6: '8 つの言語に対応。ライトテーマとダークテーマを用意。',
    shotDownload: '再生リストから動画を選ぶ',
    shotQueue: 'ダウンロードキュー',
    installTitle: 'インストール',
    installWindows: 'VidSnare はまだコード署名されていないため、初回は「不明な発行元」と表示されることがあります。「詳細情報」→「実行」をクリックしてください。',
    installLinux: 'AppImage は、プログラムとしての実行を許可してから（右クリック → プロパティ → アクセス権）開いてください。',
    disclaimer:
      'YouTube の利用規約と著作権法を守る責任はユーザーにあります。ダウンロードする権利のあるコンテンツのみをダウンロードしてください。',
    license: '個人的・非商用の利用は無料です。',
    source: 'ソースコード',
    notAffiliated: 'YouTube および Google とは関係ありません。',
    language: '言語'
  },
  fr: {
    title: 'VidSnare – téléchargez vidéos et audio depuis YouTube',
    tagline: 'Téléchargez vidéos et musique depuis YouTube. Tout simplement.',
    lead: 'Collez un lien, choisissez la qualité, VidSnare s’occupe du reste. Gratuit pour un usage personnel sous Windows et Linux.',
    downloadFor: 'Télécharger pour {os}',
    otherDownloads: 'Autres téléchargements',
    version: 'Version {version}',
    comingSoon: 'La première version arrive bientôt.',
    onlyWinLinux: 'VidSnare est disponible pour Windows et Linux.',
    fileWindows: 'Windows 10 et 11 – programme d’installation',
    fileAppImage: 'Linux – AppImage, toutes distributions',
    fileDeb: 'Linux – paquet Debian / Ubuntu',
    featuresTitle: 'Ce qu’il fait',
    f1Title: 'Playlists et chaînes',
    f1: 'Chargez une playlist ou une chaîne entière et choisissez exactement les vidéos voulues.',
    f2Title: 'Vidéo ou audio',
    f2: 'Vidéo jusqu’en 4K, ou seulement le son en MP3, M4A ou Opus.',
    f3Title: 'Sous-titres',
    f3: 'Sous-titres dans les langues de votre choix, en fichier ou intégrés à la vidéo.',
    f4Title: 'File de téléchargement',
    f4: 'Plusieurs téléchargements à la fois, avec progression, vitesse et temps restant.',
    f5Title: 'Toujours à jour',
    f5: 'VidSnare et son moteur de téléchargement se mettent à jour automatiquement.',
    f6Title: 'Votre langue',
    f6: 'Disponible en huit langues, avec thèmes clair et sombre.',
    shotDownload: 'Choisir des vidéos dans une playlist',
    shotQueue: 'La file de téléchargement',
    installTitle: 'Installation',
    installWindows: 'Windows peut afficher « Éditeur inconnu » la première fois, car VidSnare n’est pas encore signé. Cliquez sur « Informations complémentaires », puis « Exécuter quand même ».',
    installLinux: 'Pour l’AppImage, autorisez son exécution comme programme (clic droit → Propriétés → Permissions), puis ouvrez-la.',
    disclaimer:
      'Vous êtes responsable du respect des Conditions d’utilisation de YouTube et du droit d’auteur. Ne téléchargez que des contenus que vous avez le droit de télécharger.',
    license: 'Gratuit pour un usage personnel et non commercial.',
    source: 'Code source',
    notAffiliated: 'Non affilié à YouTube ni à Google.',
    language: 'Langue'
  }
}

export const LANGUAGE_NAMES = {
  en: 'English',
  pl: 'Polski',
  de: 'Deutsch',
  es: 'Español',
  'pt-BR': 'Português (Brasil)',
  ru: 'Русский',
  ja: '日本語',
  fr: 'Français'
}
