// Website text in every language. Keys and {placeholders} must match English
// (checked by tests/website.test.ts).
export const STRINGS = {
  en: {
    title: 'VidSnare – download videos and audio from YouTube',
    tagline: 'Download videos and music from YouTube. Simply.',
    lead: 'Paste a link, choose the quality, and VidSnare does the rest. Free for personal use on Windows and Linux.',
    downloadFor: 'Download for {os}',
    otherDownloads: 'Other downloads',
    version: 'Version {version}',
    comingSoon: 'The first release is coming soon.',
    onlyWinLinux: 'VidSnare is available for Windows and Linux.',
    fileWindows: 'Windows 10 and 11 – installer',
    fileAppImage: 'Linux – AppImage, any distribution',
    fileDeb: 'Linux – Debian / Ubuntu package',
    featuresTitle: 'What it does',
    f1Title: 'Playlists and channels',
    f1: 'Load a whole playlist or channel and pick exactly which videos you want.',
    f2Title: 'Video or audio',
    f2: 'Video up to 4K, or just the sound as MP3, M4A or Opus.',
    f3Title: 'Subtitles',
    f3: 'Get subtitles in the languages you choose, saved or built into the video.',
    f4Title: 'Download queue',
    f4: 'Several downloads at once, with progress, speed and time left.',
    f5Title: 'Always up to date',
    f5: 'VidSnare and its download engine update themselves automatically.',
    f6Title: 'Your language',
    f6: 'Available in 26 languages, with light and dark themes.',
    shotDownload: 'Choosing videos from a playlist',
    shotQueue: 'The download queue',
    installTitle: 'Installing',
    downloadDeb: "Download for Ubuntu / Debian",
    appImageLink: "Other Linux? Get the AppImage",
    installHelp: "Installation help",
    recommended: "Recommended",
    tabWindows: "Windows",
    tabDeb: "Ubuntu, Debian, Mint",
    tabAppImage: "Other Linux (AppImage)",
    winStep1: "Download VidSnare-Setup.exe with the button above.",
    winStep2: "Open it. If Windows says “Windows protected your PC”, click “More info”, then “Run anyway”. This appears because VidSnare is not code-signed yet.",
    winStep3: "Follow the installer. Afterwards, open VidSnare from the Start menu.",
    winUpdates: "Updates are installed automatically.",
    debStep1: "Download the package with the button above, or in a terminal:",
    debStep2: "Install it from the folder where it was saved:",
    debStep3: "Open VidSnare from your applications menu, or run:",
    debUpdates: "When a new version is out, VidSnare tells you. Install it the same way.",
    debRemove: "To uninstall:",
    appStep1: "Download the AppImage with the link above, or in a terminal:",
    appStep2: "Allow it to run, then start it:",
    appStep2Alt: "Without a terminal: right-click the file → Properties → Permissions → allow running it as a program, then double-click it.",
    appUpdates: "The AppImage updates itself automatically.",
    troubleTitle: "If it doesn’t start",
    troubleFuse: "An error about “libfuse.so.2” means a library AppImages need is missing. Install it for your system:",
    troubleSandbox: "An error about the “sandbox” on Ubuntu 24.04 or newer: use the Ubuntu / Debian package instead – it sets this up for you.",
    copy: "Copy",
    copied: "Copied",
    usageTitle: "How to use it",
    use1: "On YouTube, copy the link of a video, playlist or channel.",
    use2: "In VidSnare, paste it into the box at the top (Ctrl+V, or right-click → Paste). A preview appears.",
    use3: "Choose video or audio, the quality and the folder, then click “Download”.",
    use4: "Click “Queue” on the left to watch the progress. When it’s finished, click “Open file”.",
    disclaimer:
      "You are responsible for complying with YouTube's Terms of Service and copyright law. Only download content you have the right to download.",
    license: 'Free for personal, non-commercial use.',
    source: 'Source code',
    notAffiliated: 'Not affiliated with YouTube or Google.',
    language: 'Language'
  },
  pl: {
    title: 'VidSnare – pobieraj filmy i dźwięk z YouTube',
    tagline: 'Pobieraj filmy i muzykę z YouTube. Po prostu.',
    lead: 'Wklej link, wybierz jakość, a VidSnare zrobi resztę. Bezpłatny do użytku osobistego na Windows i Linux.',
    downloadFor: 'Pobierz na {os}',
    otherDownloads: 'Inne wersje',
    version: 'Wersja {version}',
    comingSoon: 'Pierwsze wydanie już wkrótce.',
    onlyWinLinux: 'VidSnare jest dostępny na Windows i Linux.',
    fileWindows: 'Windows 10 i 11 – instalator',
    fileAppImage: 'Linux – AppImage, dowolna dystrybucja',
    fileDeb: 'Linux – pakiet Debian / Ubuntu',
    featuresTitle: 'Co potrafi',
    f1Title: 'Playlisty i kanały',
    f1: 'Wczytaj całą playlistę lub kanał i wybierz dokładnie te filmy, których chcesz.',
    f2Title: 'Wideo lub dźwięk',
    f2: 'Wideo do 4K albo sam dźwięk jako MP3, M4A lub Opus.',
    f3Title: 'Napisy',
    f3: 'Pobieraj napisy w wybranych językach – jako pliki lub wbudowane w wideo.',
    f4Title: 'Kolejka pobierania',
    f4: 'Kilka pobrań naraz, z postępem, prędkością i pozostałym czasem.',
    f5Title: 'Zawsze aktualny',
    f5: 'VidSnare i jego silnik pobierania aktualizują się automatycznie.',
    f6Title: 'Twój język',
    f6: 'Dostępny w 26 językach, z jasnym i ciemnym motywem.',
    shotDownload: 'Wybieranie filmów z playlisty',
    shotQueue: 'Kolejka pobierania',
    installTitle: 'Instalacja',
    downloadDeb: "Pobierz na Ubuntu / Debian",
    appImageLink: "Inny Linux? Pobierz AppImage",
    installHelp: "Pomoc w instalacji",
    recommended: "Zalecane",
    tabWindows: "Windows",
    tabDeb: "Ubuntu, Debian, Mint",
    tabAppImage: "Inny Linux (AppImage)",
    winStep1: "Pobierz VidSnare-Setup.exe przyciskiem powyżej.",
    winStep2: "Otwórz plik. Jeśli Windows pokaże „System Windows ochronił ten komputer”, kliknij „Więcej informacji”, a potem „Uruchom mimo to”. Ten komunikat pojawia się, bo VidSnare nie jest jeszcze podpisany cyfrowo.",
    winStep3: "Przejdź przez instalator. Potem uruchom VidSnare z menu Start.",
    winUpdates: "Aktualizacje instalują się automatycznie.",
    debStep1: "Pobierz pakiet przyciskiem powyżej albo w terminalu:",
    debStep2: "Zainstaluj go z folderu, w którym został zapisany:",
    debStep3: "Otwórz VidSnare z menu aplikacji albo wpisz:",
    debUpdates: "Gdy pojawi się nowa wersja, VidSnare da znać. Zainstaluj ją w ten sam sposób.",
    debRemove: "Aby odinstalować:",
    appStep1: "Pobierz AppImage linkiem powyżej albo w terminalu:",
    appStep2: "Zezwól na uruchamianie i uruchom:",
    appStep2Alt: "Bez terminala: kliknij plik prawym przyciskiem → Właściwości → Uprawnienia → zezwól na uruchamianie jako program, potem kliknij go dwukrotnie.",
    appUpdates: "AppImage aktualizuje się sam.",
    troubleTitle: "Jeśli się nie uruchamia",
    troubleFuse: "Błąd dotyczący „libfuse.so.2” oznacza brak biblioteki potrzebnej AppImage. Zainstaluj ją dla swojego systemu:",
    troubleSandbox: "Błąd dotyczący „sandbox” na Ubuntu 24.04 lub nowszym: użyj zamiast tego pakietu dla Ubuntu / Debian – on wszystko ustawia sam.",
    copy: "Kopiuj",
    copied: "Skopiowano",
    usageTitle: "Jak używać",
    use1: "Na YouTube skopiuj link do filmu, playlisty lub kanału.",
    use2: "W VidSnare wklej go w pole na górze (Ctrl+V albo prawy przycisk → Wklej). Pojawi się podgląd.",
    use3: "Wybierz wideo lub dźwięk, jakość i folder, potem kliknij „Pobierz”.",
    use4: "Kliknij „Kolejka” po lewej, aby śledzić postęp. Gdy się skończy, kliknij „Otwórz plik”.",
    disclaimer:
      'Odpowiadasz za przestrzeganie Warunków korzystania z YouTube i prawa autorskiego. Pobieraj tylko treści, do których masz prawo.',
    license: 'Bezpłatny do użytku osobistego, niekomercyjnego.',
    source: 'Kod źródłowy',
    notAffiliated: 'Niepowiązany z YouTube ani Google.',
    language: 'Język'
  },
  de: {
    title: 'VidSnare – Videos und Audio von YouTube herunterladen',
    tagline: 'Videos und Musik von YouTube herunterladen. Ganz einfach.',
    lead: 'Link einfügen, Qualität wählen – VidSnare erledigt den Rest. Kostenlos für den privaten Gebrauch unter Windows und Linux.',
    downloadFor: 'Für {os} herunterladen',
    otherDownloads: 'Weitere Downloads',
    version: 'Version {version}',
    comingSoon: 'Die erste Version erscheint bald.',
    onlyWinLinux: 'VidSnare gibt es für Windows und Linux.',
    fileWindows: 'Windows 10 und 11 – Installer',
    fileAppImage: 'Linux – AppImage, jede Distribution',
    fileDeb: 'Linux – Debian-/Ubuntu-Paket',
    featuresTitle: 'Was es kann',
    f1Title: 'Playlists und Kanäle',
    f1: 'Lade eine ganze Playlist oder einen Kanal und wähle genau die Videos aus, die du willst.',
    f2Title: 'Video oder Audio',
    f2: 'Video bis 4K oder nur der Ton als MP3, M4A oder Opus.',
    f3Title: 'Untertitel',
    f3: 'Untertitel in den gewünschten Sprachen – als Datei oder im Video.',
    f4Title: 'Download-Warteschlange',
    f4: 'Mehrere Downloads gleichzeitig, mit Fortschritt, Geschwindigkeit und Restzeit.',
    f5Title: 'Immer aktuell',
    f5: 'VidSnare und seine Download-Engine aktualisieren sich automatisch.',
    f6Title: 'Deine Sprache',
    f6: 'In 26 Sprachen verfügbar, mit hellem und dunklem Design.',
    shotDownload: 'Videos aus einer Playlist auswählen',
    shotQueue: 'Die Download-Warteschlange',
    installTitle: 'Installation',
    downloadDeb: "Für Ubuntu / Debian herunterladen",
    appImageLink: "Anderes Linux? AppImage herunterladen",
    installHelp: "Hilfe zur Installation",
    recommended: "Empfohlen",
    tabWindows: "Windows",
    tabDeb: "Ubuntu, Debian, Mint",
    tabAppImage: "Anderes Linux (AppImage)",
    winStep1: "Lade VidSnare-Setup.exe mit der Schaltfläche oben herunter.",
    winStep2: "Öffne die Datei. Wenn Windows „Der Computer wurde durch Windows geschützt“ meldet, klicke auf „Weitere Informationen“ und dann auf „Trotzdem ausführen“. Das erscheint, weil VidSnare noch nicht signiert ist.",
    winStep3: "Folge dem Installer. Danach startest du VidSnare über das Startmenü.",
    winUpdates: "Updates werden automatisch installiert.",
    debStep1: "Lade das Paket mit der Schaltfläche oben herunter oder im Terminal:",
    debStep2: "Installiere es aus dem Ordner, in dem es gespeichert wurde:",
    debStep3: "Öffne VidSnare über das Anwendungsmenü oder führe aus:",
    debUpdates: "Wenn es eine neue Version gibt, sagt dir VidSnare Bescheid. Installiere sie auf dieselbe Weise.",
    debRemove: "Zum Deinstallieren:",
    appStep1: "Lade das AppImage über den Link oben herunter oder im Terminal:",
    appStep2: "Erlaube die Ausführung und starte es:",
    appStep2Alt: "Ohne Terminal: Rechtsklick auf die Datei → Eigenschaften → Berechtigungen → Ausführen als Programm erlauben, dann doppelklicken.",
    appUpdates: "Das AppImage aktualisiert sich selbst.",
    troubleTitle: "Falls es nicht startet",
    troubleFuse: "Ein Fehler zu „libfuse.so.2“ bedeutet, dass eine Bibliothek fehlt, die AppImages brauchen. Installiere sie für dein System:",
    troubleSandbox: "Ein Fehler zur „Sandbox“ unter Ubuntu 24.04 oder neuer: Nimm stattdessen das Ubuntu-/Debian-Paket – es richtet das für dich ein.",
    copy: "Kopieren",
    copied: "Kopiert",
    usageTitle: "So benutzt du es",
    use1: "Kopiere auf YouTube den Link eines Videos, einer Playlist oder eines Kanals.",
    use2: "Füge ihn in VidSnare oben ins Feld ein (Strg+V oder Rechtsklick → Einfügen). Eine Vorschau erscheint.",
    use3: "Wähle Video oder Audio, die Qualität und den Ordner und klicke dann auf „Herunterladen“.",
    use4: "Klicke links auf „Warteschlange“, um den Fortschritt zu sehen. Wenn es fertig ist, klicke auf „Datei öffnen“.",
    disclaimer:
      'Du bist dafür verantwortlich, die Nutzungsbedingungen von YouTube und das Urheberrecht einzuhalten. Lade nur Inhalte herunter, zu deren Download du berechtigt bist.',
    license: 'Kostenlos für private, nicht-kommerzielle Nutzung.',
    source: 'Quellcode',
    notAffiliated: 'Nicht mit YouTube oder Google verbunden.',
    language: 'Sprache'
  },
  es: {
    title: 'VidSnare – descarga vídeos y audio de YouTube',
    tagline: 'Descarga vídeos y música de YouTube. Así de fácil.',
    lead: 'Pega un enlace, elige la calidad y VidSnare hace el resto. Gratis para uso personal en Windows y Linux.',
    downloadFor: 'Descargar para {os}',
    otherDownloads: 'Otras descargas',
    version: 'Versión {version}',
    comingSoon: 'La primera versión llegará pronto.',
    onlyWinLinux: 'VidSnare está disponible para Windows y Linux.',
    fileWindows: 'Windows 10 y 11 – instalador',
    fileAppImage: 'Linux – AppImage, cualquier distribución',
    fileDeb: 'Linux – paquete Debian / Ubuntu',
    featuresTitle: 'Qué hace',
    f1Title: 'Listas y canales',
    f1: 'Carga una lista de reproducción o un canal entero y elige exactamente los vídeos que quieres.',
    f2Title: 'Vídeo o audio',
    f2: 'Vídeo hasta 4K, o solo el sonido en MP3, M4A u Opus.',
    f3Title: 'Subtítulos',
    f3: 'Subtítulos en los idiomas que elijas, como archivo o dentro del vídeo.',
    f4Title: 'Cola de descargas',
    f4: 'Varias descargas a la vez, con progreso, velocidad y tiempo restante.',
    f5Title: 'Siempre actualizado',
    f5: 'VidSnare y su motor de descarga se actualizan solos.',
    f6Title: 'Tu idioma',
    f6: 'Disponible en 26 idiomas, con tema claro y oscuro.',
    shotDownload: 'Eligiendo vídeos de una lista',
    shotQueue: 'La cola de descargas',
    installTitle: 'Instalación',
    downloadDeb: "Descargar para Ubuntu / Debian",
    appImageLink: "¿Otro Linux? Descarga el AppImage",
    installHelp: "Ayuda de instalación",
    recommended: "Recomendado",
    tabWindows: "Windows",
    tabDeb: "Ubuntu, Debian, Mint",
    tabAppImage: "Otro Linux (AppImage)",
    winStep1: "Descarga VidSnare-Setup.exe con el botón de arriba.",
    winStep2: "Ábrelo. Si Windows dice «Windows protegió su PC», haz clic en «Más información» y luego en «Ejecutar de todas formas». Aparece porque VidSnare aún no está firmado.",
    winStep3: "Sigue el instalador. Después, abre VidSnare desde el menú Inicio.",
    winUpdates: "Las actualizaciones se instalan solas.",
    debStep1: "Descarga el paquete con el botón de arriba, o en una terminal:",
    debStep2: "Instálalo desde la carpeta donde se guardó:",
    debStep3: "Abre VidSnare desde el menú de aplicaciones, o ejecuta:",
    debUpdates: "Cuando salga una versión nueva, VidSnare te avisará. Instálala de la misma forma.",
    debRemove: "Para desinstalar:",
    appStep1: "Descarga el AppImage con el enlace de arriba, o en una terminal:",
    appStep2: "Permite que se ejecute y ábrelo:",
    appStep2Alt: "Sin terminal: clic derecho en el archivo → Propiedades → Permisos → permitir ejecutar como programa, y luego doble clic.",
    appUpdates: "El AppImage se actualiza solo.",
    troubleTitle: "Si no se abre",
    troubleFuse: "Un error sobre «libfuse.so.2» significa que falta una biblioteca que necesitan los AppImage. Instálala para tu sistema:",
    troubleSandbox: "Un error sobre el «sandbox» en Ubuntu 24.04 o posterior: usa el paquete para Ubuntu / Debian, que lo configura por ti.",
    copy: "Copiar",
    copied: "Copiado",
    usageTitle: "Cómo se usa",
    use1: "En YouTube, copia el enlace de un vídeo, una lista o un canal.",
    use2: "En VidSnare, pégalo en el cuadro de arriba (Ctrl+V o clic derecho → Pegar). Aparecerá una vista previa.",
    use3: "Elige vídeo o audio, la calidad y la carpeta, y haz clic en «Descargar».",
    use4: "Haz clic en «Cola» a la izquierda para ver el progreso. Cuando termine, haz clic en «Abrir archivo».",
    disclaimer:
      'Eres responsable de cumplir las Condiciones de servicio de YouTube y las leyes de derechos de autor. Descarga solo contenido que tengas derecho a descargar.',
    license: 'Gratis para uso personal y no comercial.',
    source: 'Código fuente',
    notAffiliated: 'Sin relación con YouTube ni Google.',
    language: 'Idioma'
  },
  'pt-BR': {
    title: 'VidSnare – baixe vídeos e áudio do YouTube',
    tagline: 'Baixe vídeos e músicas do YouTube. Simples assim.',
    lead: 'Cole um link, escolha a qualidade e o VidSnare faz o resto. Grátis para uso pessoal no Windows e no Linux.',
    downloadFor: 'Baixar para {os}',
    otherDownloads: 'Outros downloads',
    version: 'Versão {version}',
    comingSoon: 'A primeira versão chega em breve.',
    onlyWinLinux: 'O VidSnare está disponível para Windows e Linux.',
    fileWindows: 'Windows 10 e 11 – instalador',
    fileAppImage: 'Linux – AppImage, qualquer distribuição',
    fileDeb: 'Linux – pacote Debian / Ubuntu',
    featuresTitle: 'O que ele faz',
    f1Title: 'Playlists e canais',
    f1: 'Carregue uma playlist ou um canal inteiro e escolha exatamente os vídeos que quer.',
    f2Title: 'Vídeo ou áudio',
    f2: 'Vídeo em até 4K, ou só o som em MP3, M4A ou Opus.',
    f3Title: 'Legendas',
    f3: 'Legendas nos idiomas que você escolher, em arquivo ou dentro do vídeo.',
    f4Title: 'Fila de downloads',
    f4: 'Vários downloads ao mesmo tempo, com progresso, velocidade e tempo restante.',
    f5Title: 'Sempre atualizado',
    f5: 'O VidSnare e seu mecanismo de download se atualizam sozinhos.',
    f6Title: 'Seu idioma',
    f6: 'Disponível em 26 idiomas, com tema claro e escuro.',
    shotDownload: 'Escolhendo vídeos de uma playlist',
    shotQueue: 'A fila de downloads',
    installTitle: 'Instalação',
    downloadDeb: "Baixar para Ubuntu / Debian",
    appImageLink: "Outro Linux? Baixe o AppImage",
    installHelp: "Ajuda com a instalação",
    recommended: "Recomendado",
    tabWindows: "Windows",
    tabDeb: "Ubuntu, Debian, Mint",
    tabAppImage: "Outro Linux (AppImage)",
    winStep1: "Baixe o VidSnare-Setup.exe com o botão acima.",
    winStep2: "Abra o arquivo. Se o Windows disser “O Windows protegeu o computador”, clique em “Mais informações” e depois em “Executar assim mesmo”. Isso aparece porque o VidSnare ainda não é assinado.",
    winStep3: "Siga o instalador. Depois, abra o VidSnare pelo menu Iniciar.",
    winUpdates: "As atualizações são instaladas automaticamente.",
    debStep1: "Baixe o pacote com o botão acima, ou no terminal:",
    debStep2: "Instale-o a partir da pasta onde ele foi salvo:",
    debStep3: "Abra o VidSnare pelo menu de aplicativos, ou execute:",
    debUpdates: "Quando sair uma versão nova, o VidSnare avisa. Instale-a do mesmo jeito.",
    debRemove: "Para desinstalar:",
    appStep1: "Baixe o AppImage pelo link acima, ou no terminal:",
    appStep2: "Permita a execução e abra:",
    appStep2Alt: "Sem terminal: clique com o botão direito no arquivo → Propriedades → Permissões → permitir executar como programa, depois clique duas vezes.",
    appUpdates: "O AppImage se atualiza sozinho.",
    troubleTitle: "Se não abrir",
    troubleFuse: "Um erro sobre “libfuse.so.2” significa que falta uma biblioteca de que os AppImages precisam. Instale-a no seu sistema:",
    troubleSandbox: "Um erro sobre o “sandbox” no Ubuntu 24.04 ou mais novo: use o pacote para Ubuntu / Debian, que já configura isso para você.",
    copy: "Copiar",
    copied: "Copiado",
    usageTitle: "Como usar",
    use1: "No YouTube, copie o link de um vídeo, playlist ou canal.",
    use2: "No VidSnare, cole-o na caixa no topo (Ctrl+V ou botão direito → Colar). Uma prévia aparece.",
    use3: "Escolha vídeo ou áudio, a qualidade e a pasta, depois clique em “Baixar”.",
    use4: "Clique em “Fila” à esquerda para acompanhar o progresso. Quando terminar, clique em “Abrir arquivo”.",
    disclaimer:
      'Você é responsável por cumprir os Termos de Serviço do YouTube e as leis de direitos autorais. Baixe apenas conteúdo que você tem o direito de baixar.',
    license: 'Grátis para uso pessoal e não comercial.',
    source: 'Código-fonte',
    notAffiliated: 'Sem vínculo com o YouTube ou o Google.',
    language: 'Idioma'
  },
  ru: {
    title: 'VidSnare – скачивайте видео и аудио с YouTube',
    tagline: 'Скачивайте видео и музыку с YouTube. Просто.',
    lead: 'Вставьте ссылку, выберите качество – остальное сделает VidSnare. Бесплатно для личного использования на Windows и Linux.',
    downloadFor: 'Скачать для {os}',
    otherDownloads: 'Другие версии',
    version: 'Версия {version}',
    comingSoon: 'Первый выпуск скоро появится.',
    onlyWinLinux: 'VidSnare доступен для Windows и Linux.',
    fileWindows: 'Windows 10 и 11 – установщик',
    fileAppImage: 'Linux – AppImage, любой дистрибутив',
    fileDeb: 'Linux – пакет Debian / Ubuntu',
    featuresTitle: 'Возможности',
    f1Title: 'Плейлисты и каналы',
    f1: 'Загрузите весь плейлист или канал и выберите именно те видео, которые нужны.',
    f2Title: 'Видео или аудио',
    f2: 'Видео до 4K или только звук в MP3, M4A или Opus.',
    f3Title: 'Субтитры',
    f3: 'Субтитры на выбранных языках – отдельным файлом или внутри видео.',
    f4Title: 'Очередь загрузок',
    f4: 'Несколько загрузок одновременно, с прогрессом, скоростью и оставшимся временем.',
    f5Title: 'Всегда актуален',
    f5: 'VidSnare и его движок загрузки обновляются автоматически.',
    f6Title: 'Ваш язык',
    f6: 'Доступен на 26 языках, со светлой и тёмной темой.',
    shotDownload: 'Выбор видео из плейлиста',
    shotQueue: 'Очередь загрузок',
    installTitle: 'Установка',
    downloadDeb: "Скачать для Ubuntu / Debian",
    appImageLink: "Другой Linux? Скачайте AppImage",
    installHelp: "Помощь с установкой",
    recommended: "Рекомендуется",
    tabWindows: "Windows",
    tabDeb: "Ubuntu, Debian, Mint",
    tabAppImage: "Другой Linux (AppImage)",
    winStep1: "Скачайте VidSnare-Setup.exe кнопкой выше.",
    winStep2: "Откройте файл. Если Windows покажет «Система Windows защитила ваш компьютер», нажмите «Подробнее», затем «Выполнить в любом случае». Это сообщение появляется, потому что у VidSnare пока нет цифровой подписи.",
    winStep3: "Пройдите шаги установщика. Затем запускайте VidSnare из меню «Пуск».",
    winUpdates: "Обновления устанавливаются автоматически.",
    debStep1: "Скачайте пакет кнопкой выше или в терминале:",
    debStep2: "Установите его из папки, куда он сохранился:",
    debStep3: "Откройте VidSnare из меню приложений или выполните:",
    debUpdates: "Когда выйдет новая версия, VidSnare сообщит об этом. Установите её так же.",
    debRemove: "Чтобы удалить:",
    appStep1: "Скачайте AppImage по ссылке выше или в терминале:",
    appStep2: "Разрешите запуск и запустите:",
    appStep2Alt: "Без терминала: правый клик по файлу → Свойства → Права → разрешить выполнение как программы, затем откройте его двойным щелчком.",
    appUpdates: "AppImage обновляется сам.",
    troubleTitle: "Если не запускается",
    troubleFuse: "Ошибка про «libfuse.so.2» означает, что не хватает библиотеки, нужной для AppImage. Установите её для своей системы:",
    troubleSandbox: "Ошибка про «sandbox» в Ubuntu 24.04 и новее: используйте пакет для Ubuntu / Debian – он всё настроит сам.",
    copy: "Копировать",
    copied: "Скопировано",
    usageTitle: "Как пользоваться",
    use1: "На YouTube скопируйте ссылку на видео, плейлист или канал.",
    use2: "В VidSnare вставьте её в поле сверху (Ctrl+V или правый клик → Вставить). Появится предпросмотр.",
    use3: "Выберите видео или аудио, качество и папку, затем нажмите «Скачать».",
    use4: "Нажмите «Очередь» слева, чтобы следить за прогрессом. Когда всё готово, нажмите «Открыть файл».",
    disclaimer:
      'Вы несёте ответственность за соблюдение Условий использования YouTube и авторского права. Скачивайте только то, на что у вас есть права.',
    license: 'Бесплатно для личного некоммерческого использования.',
    source: 'Исходный код',
    notAffiliated: 'Не связан с YouTube или Google.',
    language: 'Язык'
  },
  ja: {
    title: 'VidSnare – YouTube の動画と音声をダウンロード',
    tagline: 'YouTube の動画と音楽を、かんたんにダウンロード。',
    lead: 'リンクを貼り付けて画質を選ぶだけ。あとは VidSnare におまかせ。Windows と Linux で、個人利用は無料です。',
    downloadFor: '{os} 版をダウンロード',
    otherDownloads: 'その他のダウンロード',
    version: 'バージョン {version}',
    comingSoon: '最初のリリースはまもなく公開予定です。',
    onlyWinLinux: 'VidSnare は Windows と Linux に対応しています。',
    fileWindows: 'Windows 10 / 11 – インストーラー',
    fileAppImage: 'Linux – AppImage（すべてのディストリビューション）',
    fileDeb: 'Linux – Debian / Ubuntu パッケージ',
    featuresTitle: 'できること',
    f1Title: '再生リストとチャンネル',
    f1: '再生リストやチャンネルをまるごと読み込み、欲しい動画だけを選べます。',
    f2Title: '動画または音声',
    f2: '最大 4K の動画、または音声のみを MP3・M4A・Opus で保存。',
    f3Title: '字幕',
    f3: '選んだ言語の字幕を、ファイルとして、または動画に埋め込んで保存。',
    f4Title: 'ダウンロードキュー',
    f4: '複数を同時にダウンロード。進行状況・速度・残り時間を表示します。',
    f5Title: 'いつも最新',
    f5: 'VidSnare とダウンロードエンジンは自動で更新されます。',
    f6Title: 'あなたの言語で',
    f6: '26 の言語に対応。ライトテーマとダークテーマを用意。',
    shotDownload: '再生リストから動画を選ぶ',
    shotQueue: 'ダウンロードキュー',
    installTitle: 'インストール',
    downloadDeb: "Ubuntu / Debian 版をダウンロード",
    appImageLink: "その他の Linux は AppImage をどうぞ",
    installHelp: "インストールのヘルプ",
    recommended: "おすすめ",
    tabWindows: "Windows",
    tabDeb: "Ubuntu・Debian・Mint",
    tabAppImage: "その他の Linux（AppImage）",
    winStep1: "上のボタンから VidSnare-Setup.exe をダウンロードします。",
    winStep2: "ファイルを開きます。「Windows によって PC が保護されました」と表示されたら、「詳細情報」→「実行」をクリックします。VidSnare がまだコード署名されていないために表示されます。",
    winStep3: "インストーラーの指示に従います。その後はスタートメニューから VidSnare を起動できます。",
    winUpdates: "アップデートは自動でインストールされます。",
    debStep1: "上のボタンからパッケージをダウンロードするか、ターミナルで次を実行します:",
    debStep2: "保存したフォルダーでインストールします:",
    debStep3: "アプリケーションメニューから VidSnare を開くか、次を実行します:",
    debUpdates: "新しいバージョンが出ると VidSnare がお知らせします。同じ方法でインストールしてください。",
    debRemove: "アンインストールするには:",
    appStep1: "上のリンクから AppImage をダウンロードするか、ターミナルで次を実行します:",
    appStep2: "実行を許可して起動します:",
    appStep2Alt: "ターミナルを使わない場合: ファイルを右クリック → プロパティ → アクセス権 → プログラムとして実行を許可し、ダブルクリックします。",
    appUpdates: "AppImage は自動で更新されます。",
    troubleTitle: "起動しないときは",
    troubleFuse: "「libfuse.so.2」に関するエラーは、AppImage に必要なライブラリが入っていないことを意味します。お使いのシステムに合わせてインストールしてください:",
    troubleSandbox: "Ubuntu 24.04 以降で「sandbox」に関するエラーが出る場合は、Ubuntu / Debian 用パッケージを使ってください。必要な設定を自動で行います。",
    copy: "コピー",
    copied: "コピーしました",
    usageTitle: "使い方",
    use1: "YouTube で動画・再生リスト・チャンネルのリンクをコピーします。",
    use2: "VidSnare の上部の欄に貼り付けます（Ctrl+V または右クリック →「貼り付け」）。プレビューが表示されます。",
    use3: "動画か音声か、画質、保存先を選び、「ダウンロード」をクリックします。",
    use4: "左側の「キュー」をクリックすると進行状況を確認できます。完了したら「ファイルを開く」をクリックします。",
    disclaimer:
      'YouTube の利用規約と著作権法を守る責任はユーザーにあります。ダウンロードする権利のあるコンテンツのみをダウンロードしてください。',
    license: '個人的・非商用の利用は無料です。',
    source: 'ソースコード',
    notAffiliated: 'YouTube および Google とは関係ありません。',
    language: '言語'
  },
  fr: {
    title: 'VidSnare – téléchargez vidéos et audio depuis YouTube',
    tagline: 'Téléchargez vidéos et musique depuis YouTube. Tout simplement.',
    lead: 'Collez un lien, choisissez la qualité, VidSnare s’occupe du reste. Gratuit pour un usage personnel sous Windows et Linux.',
    downloadFor: 'Télécharger pour {os}',
    otherDownloads: 'Autres téléchargements',
    version: 'Version {version}',
    comingSoon: 'La première version arrive bientôt.',
    onlyWinLinux: 'VidSnare est disponible pour Windows et Linux.',
    fileWindows: 'Windows 10 et 11 – programme d’installation',
    fileAppImage: 'Linux – AppImage, toutes distributions',
    fileDeb: 'Linux – paquet Debian / Ubuntu',
    featuresTitle: 'Ce qu’il fait',
    f1Title: 'Playlists et chaînes',
    f1: 'Chargez une playlist ou une chaîne entière et choisissez exactement les vidéos voulues.',
    f2Title: 'Vidéo ou audio',
    f2: 'Vidéo jusqu’en 4K, ou seulement le son en MP3, M4A ou Opus.',
    f3Title: 'Sous-titres',
    f3: 'Sous-titres dans les langues de votre choix, en fichier ou intégrés à la vidéo.',
    f4Title: 'File de téléchargement',
    f4: 'Plusieurs téléchargements à la fois, avec progression, vitesse et temps restant.',
    f5Title: 'Toujours à jour',
    f5: 'VidSnare et son moteur de téléchargement se mettent à jour automatiquement.',
    f6Title: 'Votre langue',
    f6: 'Disponible en 26 langues, avec thèmes clair et sombre.',
    shotDownload: 'Choisir des vidéos dans une playlist',
    shotQueue: 'La file de téléchargement',
    installTitle: 'Installation',
    downloadDeb: "Télécharger pour Ubuntu / Debian",
    appImageLink: "Autre Linux ? Prenez l’AppImage",
    installHelp: "Aide à l’installation",
    recommended: "Recommandé",
    tabWindows: "Windows",
    tabDeb: "Ubuntu, Debian, Mint",
    tabAppImage: "Autre Linux (AppImage)",
    winStep1: "Téléchargez VidSnare-Setup.exe avec le bouton ci-dessus.",
    winStep2: "Ouvrez-le. Si Windows affiche « Windows a protégé votre ordinateur », cliquez sur « Informations complémentaires », puis « Exécuter quand même ». Ce message apparaît car VidSnare n’est pas encore signé.",
    winStep3: "Suivez l’installation. Ensuite, ouvrez VidSnare depuis le menu Démarrer.",
    winUpdates: "Les mises à jour s’installent automatiquement.",
    debStep1: "Téléchargez le paquet avec le bouton ci-dessus, ou dans un terminal :",
    debStep2: "Installez-le depuis le dossier où il a été enregistré :",
    debStep3: "Ouvrez VidSnare depuis le menu des applications, ou lancez :",
    debUpdates: "Quand une nouvelle version sort, VidSnare vous prévient. Installez-la de la même façon.",
    debRemove: "Pour désinstaller :",
    appStep1: "Téléchargez l’AppImage avec le lien ci-dessus, ou dans un terminal :",
    appStep2: "Autorisez son exécution, puis lancez-la :",
    appStep2Alt: "Sans terminal : clic droit sur le fichier → Propriétés → Permissions → autoriser l’exécution comme programme, puis double-cliquez dessus.",
    appUpdates: "L’AppImage se met à jour toute seule.",
    troubleTitle: "Si elle ne démarre pas",
    troubleFuse: "Une erreur sur « libfuse.so.2 » signifie qu’il manque une bibliothèque nécessaire aux AppImage. Installez-la pour votre système :",
    troubleSandbox: "Une erreur sur le « sandbox » sous Ubuntu 24.04 ou plus récent : utilisez plutôt le paquet Ubuntu / Debian, qui s’en occupe pour vous.",
    copy: "Copier",
    copied: "Copié",
    usageTitle: "Comment l’utiliser",
    use1: "Sur YouTube, copiez le lien d’une vidéo, d’une playlist ou d’une chaîne.",
    use2: "Dans VidSnare, collez-le dans le champ en haut (Ctrl+V ou clic droit → Coller). Un aperçu s’affiche.",
    use3: "Choisissez vidéo ou audio, la qualité et le dossier, puis cliquez sur « Télécharger ».",
    use4: "Cliquez sur « File d’attente » à gauche pour suivre la progression. Une fois terminé, cliquez sur « Ouvrir le fichier ».",
    disclaimer:
      'Vous êtes responsable du respect des Conditions d’utilisation de YouTube et du droit d’auteur. Ne téléchargez que des contenus que vous avez le droit de télécharger.',
    license: 'Gratuit pour un usage personnel et non commercial.',
    source: 'Code source',
    notAffiliated: 'Non affilié à YouTube ni à Google.',
    language: 'Langue'
  },
  tr: {
    title: 'VidSnare – YouTube’dan video ve ses indirin',
    tagline: 'YouTube’dan video ve müzik indirin. Bu kadar basit.',
    lead: 'Bir bağlantı yapıştırın, kaliteyi seçin, gerisini VidSnare halletsin. Windows ve Linux’ta kişisel kullanım için ücretsiz.',
    downloadFor: '{os} için indir',
    otherDownloads: 'Diğer indirmeler',
    version: 'Sürüm {version}',
    comingSoon: 'İlk sürüm çok yakında.',
    onlyWinLinux: 'VidSnare, Windows ve Linux için kullanılabilir.',
    fileWindows: 'Windows 10 ve 11 – kurulum dosyası',
    fileAppImage: 'Linux – AppImage, tüm dağıtımlar',
    fileDeb: 'Linux – Debian / Ubuntu paketi',
    featuresTitle: 'Neler yapar',
    f1Title: 'Oynatma listeleri ve kanallar',
    f1: 'Bir oynatma listesini veya kanalı bütünüyle yükleyin ve istediğiniz videoları seçin.',
    f2Title: 'Video veya ses',
    f2: '4K’ya kadar video ya da yalnızca ses: MP3, M4A veya Opus.',
    f3Title: 'Altyazılar',
    f3: 'Seçtiğiniz dillerde altyazılar; ayrı dosya olarak ya da videoya gömülü.',
    f4Title: 'İndirme sırası',
    f4: 'Aynı anda birden çok indirme; ilerleme, hız ve kalan süreyle.',
    f5Title: 'Her zaman güncel',
    f5: 'VidSnare ve indirme motoru kendilerini otomatik olarak günceller.',
    f6Title: 'Kendi dilinizde',
    f6: '26 dilde, açık ve koyu temayla.',
    shotDownload: 'Bir oynatma listesinden video seçme',
    shotQueue: 'İndirme sırası',
    installTitle: 'Kurulum',
    downloadDeb: "Ubuntu / Debian için indir",
    appImageLink: "Başka bir Linux mu? AppImage’ı indirin",
    installHelp: "Kurulum yardımı",
    recommended: "Önerilen",
    tabWindows: "Windows",
    tabDeb: "Ubuntu, Debian, Mint",
    tabAppImage: "Diğer Linux (AppImage)",
    winStep1: "Yukarıdaki düğmeyle VidSnare-Setup.exe dosyasını indirin.",
    winStep2: "Dosyayı açın. Windows “Windows bilgisayarınızı korudu” derse “Ek bilgi”ye, ardından “Yine de çalıştır”a tıklayın. Bu uyarı, VidSnare henüz dijital olarak imzalanmadığı için çıkar.",
    winStep3: "Kurulum adımlarını izleyin. Ardından VidSnare’i Başlat menüsünden açın.",
    winUpdates: "Güncellemeler otomatik olarak kurulur.",
    debStep1: "Paketi yukarıdaki düğmeyle ya da terminalde indirin:",
    debStep2: "Kaydedildiği klasörden kurun:",
    debStep3: "VidSnare’i uygulama menüsünden açın ya da şunu çalıştırın:",
    debUpdates: "Yeni bir sürüm çıktığında VidSnare size haber verir. Aynı şekilde kurun.",
    debRemove: "Kaldırmak için:",
    appStep1: "AppImage’ı yukarıdaki bağlantıdan ya da terminalde indirin:",
    appStep2: "Çalıştırma izni verin ve başlatın:",
    appStep2Alt: "Terminal olmadan: dosyaya sağ tıklayın → Özellikler → İzinler → program olarak çalıştırmaya izin verin, sonra çift tıklayın.",
    appUpdates: "AppImage kendini otomatik olarak günceller.",
    troubleTitle: "Açılmazsa",
    troubleFuse: "“libfuse.so.2” ile ilgili bir hata, AppImage’ların ihtiyaç duyduğu bir kütüphanenin eksik olduğu anlamına gelir. Sisteminiz için kurun:",
    troubleSandbox: "Ubuntu 24.04 veya daha yenisinde “sandbox” ile ilgili bir hata: bunun yerine Ubuntu / Debian paketini kullanın; gereken ayarı o yapar.",
    copy: "Kopyala",
    copied: "Kopyalandı",
    usageTitle: "Nasıl kullanılır",
    use1: "YouTube’da bir videonun, oynatma listesinin veya kanalın bağlantısını kopyalayın.",
    use2: "VidSnare’de üstteki kutuya yapıştırın (Ctrl+V ya da sağ tık → Yapıştır). Bir önizleme görünür.",
    use3: "Video ya da ses, kalite ve klasörü seçin, sonra “İndir” düğmesine tıklayın.",
    use4: "İlerlemeyi görmek için soldaki “Sıra” öğesine tıklayın. Bitince “Dosyayı aç” düğmesine tıklayın.",
    disclaimer: 'YouTube Hizmet Şartları’na ve telif hakkı yasalarına uymak sizin sorumluluğunuzdadır. Yalnızca indirme hakkına sahip olduğunuz içerikleri indirin.',
    license: 'Kişisel ve ticari olmayan kullanım için ücretsiz.',
    source: 'Kaynak kodu',
    notAffiliated: 'YouTube veya Google ile bağlantılı değildir.',
    language: 'Dil'
  },
  it: {
    title: 'VidSnare – scarica video e audio da YouTube',
    tagline: 'Scarica video e musica da YouTube. Semplicemente.',
    lead: 'Incolla un link, scegli la qualità e VidSnare fa il resto. Gratis per uso personale su Windows e Linux.',
    downloadFor: 'Scarica per {os}',
    otherDownloads: 'Altri download',
    version: 'Versione {version}',
    comingSoon: 'La prima versione arriverà presto.',
    onlyWinLinux: 'VidSnare è disponibile per Windows e Linux.',
    fileWindows: 'Windows 10 e 11 – programma di installazione',
    fileAppImage: 'Linux – AppImage, qualsiasi distribuzione',
    fileDeb: 'Linux – pacchetto Debian / Ubuntu',
    featuresTitle: 'Cosa fa',
    f1Title: 'Playlist e canali',
    f1: 'Carica un’intera playlist o un canale e scegli esattamente i video che vuoi.',
    f2Title: 'Video o audio',
    f2: 'Video fino al 4K, oppure solo l’audio in MP3, M4A o Opus.',
    f3Title: 'Sottotitoli',
    f3: 'Sottotitoli nelle lingue che preferisci, come file o dentro il video.',
    f4Title: 'Coda di download',
    f4: 'Più download insieme, con avanzamento, velocità e tempo rimanente.',
    f5Title: 'Sempre aggiornato',
    f5: 'VidSnare e il suo motore di download si aggiornano da soli.',
    f6Title: 'La tua lingua',
    f6: 'Disponibile in 26 lingue, con tema chiaro e scuro.',
    shotDownload: 'Scegliere i video di una playlist',
    shotQueue: 'La coda di download',
    installTitle: 'Installazione',
    downloadDeb: "Scarica per Ubuntu / Debian",
    appImageLink: "Altro Linux? Scarica l’AppImage",
    installHelp: "Aiuto per l’installazione",
    recommended: "Consigliato",
    tabWindows: "Windows",
    tabDeb: "Ubuntu, Debian, Mint",
    tabAppImage: "Altro Linux (AppImage)",
    winStep1: "Scarica VidSnare-Setup.exe con il pulsante qui sopra.",
    winStep2: "Aprilo. Se Windows mostra “PC protetto da Windows”, fai clic su “Ulteriori informazioni” e poi su “Esegui comunque”. Il messaggio compare perché VidSnare non è ancora firmato.",
    winStep3: "Segui l’installazione. Poi apri VidSnare dal menu Start.",
    winUpdates: "Gli aggiornamenti si installano da soli.",
    debStep1: "Scarica il pacchetto con il pulsante qui sopra, oppure da terminale:",
    debStep2: "Installalo dalla cartella in cui è stato salvato:",
    debStep3: "Apri VidSnare dal menu delle applicazioni, oppure esegui:",
    debUpdates: "Quando esce una nuova versione, VidSnare te lo dice. Installala allo stesso modo.",
    debRemove: "Per disinstallare:",
    appStep1: "Scarica l’AppImage con il link qui sopra, oppure da terminale:",
    appStep2: "Consenti l’esecuzione e avvialo:",
    appStep2Alt: "Senza terminale: clic destro sul file → Proprietà → Permessi → consenti l’esecuzione come programma, poi fai doppio clic.",
    appUpdates: "L’AppImage si aggiorna da solo.",
    troubleTitle: "Se non si avvia",
    troubleFuse: "Un errore su “libfuse.so.2” significa che manca una libreria necessaria agli AppImage. Installala per il tuo sistema:",
    troubleSandbox: "Un errore sul “sandbox” in Ubuntu 24.04 o successivi: usa invece il pacchetto per Ubuntu / Debian, che configura tutto da sé.",
    copy: "Copia",
    copied: "Copiato",
    usageTitle: "Come si usa",
    use1: "Su YouTube, copia il link di un video, di una playlist o di un canale.",
    use2: "In VidSnare, incollalo nella casella in alto (Ctrl+V o clic destro → Incolla). Compare un’anteprima.",
    use3: "Scegli video o audio, la qualità e la cartella, poi fai clic su “Scarica”.",
    use4: "Fai clic su “Coda” a sinistra per seguire l’avanzamento. Al termine, fai clic su “Apri file”.",
    disclaimer: 'Sei responsabile del rispetto dei Termini di servizio di YouTube e delle leggi sul diritto d’autore. Scarica solo contenuti che hai il diritto di scaricare.',
    license: 'Gratis per uso personale e non commerciale.',
    source: 'Codice sorgente',
    notAffiliated: 'Non affiliato a YouTube né a Google.',
    language: 'Lingua'
  },
  uk: {
    title: 'VidSnare – завантажуйте відео й аудіо з YouTube',
    tagline: 'Завантажуйте відео й музику з YouTube. Просто.',
    lead: 'Вставте посилання, виберіть якість – решту зробить VidSnare. Безкоштовно для особистого використання на Windows і Linux.',
    downloadFor: 'Завантажити для {os}',
    otherDownloads: 'Інші версії',
    version: 'Версія {version}',
    comingSoon: 'Перший випуск зовсім скоро.',
    onlyWinLinux: 'VidSnare доступний для Windows і Linux.',
    fileWindows: 'Windows 10 і 11 – інсталятор',
    fileAppImage: 'Linux – AppImage, будь-який дистрибутив',
    fileDeb: 'Linux – пакет Debian / Ubuntu',
    featuresTitle: 'Можливості',
    f1Title: 'Плейлисти й канали',
    f1: 'Відкрийте весь плейлист або канал і виберіть саме ті відео, які потрібні.',
    f2Title: 'Відео або аудіо',
    f2: 'Відео до 4K або лише звук у MP3, M4A чи Opus.',
    f3Title: 'Субтитри',
    f3: 'Субтитри вибраними мовами – окремим файлом або всередині відео.',
    f4Title: 'Черга завантажень',
    f4: 'Кілька завантажень одночасно, з прогресом, швидкістю та часом, що залишився.',
    f5Title: 'Завжди актуальний',
    f5: 'VidSnare і його рушій завантаження оновлюються автоматично.',
    f6Title: 'Ваша мова',
    f6: 'Доступний 26 мовами, зі світлою й темною темою.',
    shotDownload: 'Вибір відео з плейлиста',
    shotQueue: 'Черга завантажень',
    installTitle: 'Встановлення',
    downloadDeb: "Завантажити для Ubuntu / Debian",
    appImageLink: "Інший Linux? Завантажте AppImage",
    installHelp: "Допомога з встановленням",
    recommended: "Рекомендовано",
    tabWindows: "Windows",
    tabDeb: "Ubuntu, Debian, Mint",
    tabAppImage: "Інший Linux (AppImage)",
    winStep1: "Завантажте VidSnare-Setup.exe кнопкою вище.",
    winStep2: "Відкрийте файл. Якщо Windows покаже «Windows захистила ваш ПК», натисніть «Докладніше», а потім «Усе одно запустити». Це повідомлення з’являється, бо VidSnare ще не має цифрового підпису.",
    winStep3: "Пройдіть кроки інсталятора. Потім запускайте VidSnare з меню «Пуск».",
    winUpdates: "Оновлення встановлюються автоматично.",
    debStep1: "Завантажте пакет кнопкою вище або в терміналі:",
    debStep2: "Встановіть його з папки, куди він зберігся:",
    debStep3: "Відкрийте VidSnare з меню програм або виконайте:",
    debUpdates: "Коли вийде нова версія, VidSnare повідомить про це. Встановіть її так само.",
    debRemove: "Щоб видалити:",
    appStep1: "Завантажте AppImage за посиланням вище або в терміналі:",
    appStep2: "Дозвольте запуск і запустіть:",
    appStep2Alt: "Без термінала: правий клік на файлі → Властивості → Права → дозволити виконання як програми, потім відкрийте його подвійним клацанням.",
    appUpdates: "AppImage оновлюється сам.",
    troubleTitle: "Якщо не запускається",
    troubleFuse: "Помилка про «libfuse.so.2» означає, що бракує бібліотеки, потрібної для AppImage. Встановіть її для своєї системи:",
    troubleSandbox: "Помилка про «sandbox» в Ubuntu 24.04 і новіших: скористайтеся пакетом для Ubuntu / Debian – він усе налаштує сам.",
    copy: "Копіювати",
    copied: "Скопійовано",
    usageTitle: "Як користуватися",
    use1: "На YouTube скопіюйте посилання на відео, плейлист або канал.",
    use2: "У VidSnare вставте його в поле вгорі (Ctrl+V або правий клік → Вставити). З’явиться попередній перегляд.",
    use3: "Виберіть відео чи аудіо, якість і папку, потім натисніть «Завантажити».",
    use4: "Натисніть «Черга» ліворуч, щоб стежити за прогресом. Коли все готово, натисніть «Відкрити файл».",
    disclaimer: 'Ви відповідаєте за дотримання Умов використання YouTube та авторського права. Завантажуйте лише те, на що маєте право.',
    license: 'Безкоштовно для особистого некомерційного використання.',
    source: 'Вихідний код',
    notAffiliated: 'Не пов’язаний з YouTube чи Google.',
    language: 'Мова'
  },
  id: {
    title: 'VidSnare – unduh video dan audio dari YouTube',
    tagline: 'Unduh video dan musik dari YouTube. Semudah itu.',
    lead: 'Tempel tautan, pilih kualitas, dan VidSnare mengurus sisanya. Gratis untuk penggunaan pribadi di Windows dan Linux.',
    downloadFor: 'Unduh untuk {os}',
    otherDownloads: 'Unduhan lainnya',
    version: 'Versi {version}',
    comingSoon: 'Rilis pertama segera hadir.',
    onlyWinLinux: 'VidSnare tersedia untuk Windows dan Linux.',
    fileWindows: 'Windows 10 dan 11 – penginstal',
    fileAppImage: 'Linux – AppImage, semua distribusi',
    fileDeb: 'Linux – paket Debian / Ubuntu',
    featuresTitle: 'Fiturnya',
    f1Title: 'Playlist dan channel',
    f1: 'Muat seluruh playlist atau channel dan pilih video yang Anda inginkan.',
    f2Title: 'Video atau audio',
    f2: 'Video hingga 4K, atau hanya suaranya sebagai MP3, M4A, atau Opus.',
    f3Title: 'Subtitle',
    f3: 'Subtitle dalam bahasa pilihan Anda, sebagai file atau di dalam video.',
    f4Title: 'Antrean unduhan',
    f4: 'Beberapa unduhan sekaligus, dengan progres, kecepatan, dan sisa waktu.',
    f5Title: 'Selalu terbaru',
    f5: 'VidSnare dan mesin unduhnya memperbarui diri secara otomatis.',
    f6Title: 'Bahasa Anda',
    f6: 'Tersedia dalam 26 bahasa, dengan tema terang dan gelap.',
    shotDownload: 'Memilih video dari playlist',
    shotQueue: 'Antrean unduhan',
    installTitle: 'Pemasangan',
    downloadDeb: "Unduh untuk Ubuntu / Debian",
    appImageLink: "Linux lain? Unduh AppImage",
    installHelp: "Bantuan pemasangan",
    recommended: "Disarankan",
    tabWindows: "Windows",
    tabDeb: "Ubuntu, Debian, Mint",
    tabAppImage: "Linux lain (AppImage)",
    winStep1: "Unduh VidSnare-Setup.exe dengan tombol di atas.",
    winStep2: "Buka file tersebut. Jika Windows menampilkan “Windows melindungi PC Anda”, klik “Info selengkapnya”, lalu “Tetap jalankan”. Pesan ini muncul karena VidSnare belum ditandatangani secara digital.",
    winStep3: "Ikuti langkah penginstal. Setelah itu, buka VidSnare dari menu Start.",
    winUpdates: "Pembaruan dipasang secara otomatis.",
    debStep1: "Unduh paketnya dengan tombol di atas, atau di terminal:",
    debStep2: "Pasang dari folder tempat file disimpan:",
    debStep3: "Buka VidSnare dari menu aplikasi, atau jalankan:",
    debUpdates: "Saat ada versi baru, VidSnare akan memberi tahu. Pasang dengan cara yang sama.",
    debRemove: "Untuk menghapus:",
    appStep1: "Unduh AppImage lewat tautan di atas, atau di terminal:",
    appStep2: "Izinkan dijalankan, lalu buka:",
    appStep2Alt: "Tanpa terminal: klik kanan file → Properti → Izin → izinkan dijalankan sebagai program, lalu klik dua kali.",
    appUpdates: "AppImage memperbarui dirinya secara otomatis.",
    troubleTitle: "Jika tidak mau terbuka",
    troubleFuse: "Galat tentang “libfuse.so.2” berarti ada pustaka yang dibutuhkan AppImage tetapi belum terpasang. Pasang untuk sistem Anda:",
    troubleSandbox: "Galat tentang “sandbox” di Ubuntu 24.04 atau lebih baru: gunakan paket untuk Ubuntu / Debian, yang mengaturnya untuk Anda.",
    copy: "Salin",
    copied: "Disalin",
    usageTitle: "Cara memakai",
    use1: "Di YouTube, salin tautan video, playlist, atau channel.",
    use2: "Di VidSnare, tempelkan ke kotak di bagian atas (Ctrl+V atau klik kanan → Tempel). Pratinjau akan muncul.",
    use3: "Pilih video atau audio, kualitas, dan folder, lalu klik “Unduh”.",
    use4: "Klik “Antrean” di sebelah kiri untuk melihat progres. Setelah selesai, klik “Buka file”.",
    disclaimer: 'Anda bertanggung jawab mematuhi Persyaratan Layanan YouTube dan hukum hak cipta. Unduh hanya konten yang berhak Anda unduh.',
    license: 'Gratis untuk penggunaan pribadi dan non-komersial.',
    source: 'Kode sumber',
    notAffiliated: 'Tidak berafiliasi dengan YouTube atau Google.',
    language: 'Bahasa'
  },
  vi: {
    title: 'VidSnare – tải video và âm thanh từ YouTube',
    tagline: 'Tải video và nhạc từ YouTube. Thật đơn giản.',
    lead: 'Dán liên kết, chọn chất lượng, VidSnare lo phần còn lại. Miễn phí cho mục đích cá nhân trên Windows và Linux.',
    downloadFor: 'Tải cho {os}',
    otherDownloads: 'Bản tải khác',
    version: 'Phiên bản {version}',
    comingSoon: 'Bản phát hành đầu tiên sắp ra mắt.',
    onlyWinLinux: 'VidSnare có cho Windows và Linux.',
    fileWindows: 'Windows 10 và 11 – trình cài đặt',
    fileAppImage: 'Linux – AppImage, mọi bản phân phối',
    fileDeb: 'Linux – gói Debian / Ubuntu',
    featuresTitle: 'Tính năng',
    f1Title: 'Danh sách phát và kênh',
    f1: 'Tải cả danh sách phát hoặc kênh và chọn đúng những video bạn muốn.',
    f2Title: 'Video hoặc âm thanh',
    f2: 'Video tới 4K, hoặc chỉ âm thanh dạng MP3, M4A hay Opus.',
    f3Title: 'Phụ đề',
    f3: 'Phụ đề theo ngôn ngữ bạn chọn, dạng tệp riêng hoặc nhúng vào video.',
    f4Title: 'Hàng chờ tải',
    f4: 'Tải nhiều mục cùng lúc, có tiến trình, tốc độ và thời gian còn lại.',
    f5Title: 'Luôn cập nhật',
    f5: 'VidSnare và công cụ tải xuống tự động cập nhật.',
    f6Title: 'Ngôn ngữ của bạn',
    f6: 'Có 26 ngôn ngữ, với giao diện sáng và tối.',
    shotDownload: 'Chọn video từ danh sách phát',
    shotQueue: 'Hàng chờ tải',
    installTitle: 'Cài đặt',
    downloadDeb: "Tải cho Ubuntu / Debian",
    appImageLink: "Linux khác? Tải bản AppImage",
    installHelp: "Hướng dẫn cài đặt",
    recommended: "Khuyên dùng",
    tabWindows: "Windows",
    tabDeb: "Ubuntu, Debian, Mint",
    tabAppImage: "Linux khác (AppImage)",
    winStep1: "Tải VidSnare-Setup.exe bằng nút ở trên.",
    winStep2: "Mở tệp. Nếu Windows báo “Windows đã bảo vệ PC của bạn”, nhấn “Thông tin thêm”, rồi “Vẫn chạy”. Thông báo này xuất hiện vì VidSnare chưa được ký số.",
    winStep3: "Làm theo trình cài đặt. Sau đó mở VidSnare từ menu Start.",
    winUpdates: "Bản cập nhật được cài tự động.",
    debStep1: "Tải gói bằng nút ở trên, hoặc trong terminal:",
    debStep2: "Cài đặt từ thư mục đã lưu tệp:",
    debStep3: "Mở VidSnare từ menu ứng dụng, hoặc chạy:",
    debUpdates: "Khi có phiên bản mới, VidSnare sẽ báo cho bạn. Cài đặt theo cách tương tự.",
    debRemove: "Để gỡ cài đặt:",
    appStep1: "Tải AppImage bằng liên kết ở trên, hoặc trong terminal:",
    appStep2: "Cho phép chạy rồi mở nó:",
    appStep2Alt: "Không dùng terminal: nhấp chuột phải vào tệp → Thuộc tính → Quyền → cho phép chạy như chương trình, rồi nhấp đúp.",
    appUpdates: "AppImage tự động cập nhật.",
    troubleTitle: "Nếu không mở được",
    troubleFuse: "Lỗi về “libfuse.so.2” nghĩa là thiếu thư viện mà AppImage cần. Hãy cài cho hệ thống của bạn:",
    troubleSandbox: "Lỗi về “sandbox” trên Ubuntu 24.04 trở lên: hãy dùng gói cho Ubuntu / Debian, gói này tự thiết lập giúp bạn.",
    copy: "Sao chép",
    copied: "Đã sao chép",
    usageTitle: "Cách sử dụng",
    use1: "Trên YouTube, sao chép liên kết của video, danh sách phát hoặc kênh.",
    use2: "Trong VidSnare, dán vào ô ở trên cùng (Ctrl+V hoặc chuột phải → Dán). Bản xem trước sẽ hiện ra.",
    use3: "Chọn video hoặc âm thanh, chất lượng và thư mục, rồi nhấn “Tải xuống”.",
    use4: "Nhấn “Hàng chờ” ở bên trái để xem tiến trình. Khi xong, nhấn “Mở tệp”.",
    disclaimer: 'Bạn chịu trách nhiệm tuân thủ Điều khoản dịch vụ của YouTube và luật bản quyền. Chỉ tải nội dung mà bạn có quyền tải.',
    license: 'Miễn phí cho mục đích cá nhân, phi thương mại.',
    source: 'Mã nguồn',
    notAffiliated: 'Không liên kết với YouTube hay Google.',
    language: 'Ngôn ngữ'
  },
  ko: {
    title: 'VidSnare – YouTube 동영상과 오디오 다운로드',
    tagline: 'YouTube 동영상과 음악을 간단하게 다운로드하세요.',
    lead: '링크를 붙여넣고 화질만 고르면 나머지는 VidSnare가 처리합니다. Windows와 Linux에서 개인 용도로 무료입니다.',
    downloadFor: '{os}용 다운로드',
    otherDownloads: '다른 다운로드',
    version: '버전 {version}',
    comingSoon: '첫 번째 릴리스가 곧 나옵니다.',
    onlyWinLinux: 'VidSnare는 Windows와 Linux를 지원합니다.',
    fileWindows: 'Windows 10 및 11 – 설치 프로그램',
    fileAppImage: 'Linux – AppImage, 모든 배포판',
    fileDeb: 'Linux – Debian / Ubuntu 패키지',
    featuresTitle: '주요 기능',
    f1Title: '재생목록과 채널',
    f1: '재생목록이나 채널 전체를 불러와 원하는 동영상만 골라 받으세요.',
    f2Title: '동영상 또는 오디오',
    f2: '최대 4K 동영상, 또는 MP3·M4A·Opus 오디오만 저장.',
    f3Title: '자막',
    f3: '원하는 언어의 자막을 파일로 저장하거나 동영상에 포함하세요.',
    f4Title: '다운로드 대기열',
    f4: '여러 개를 동시에 다운로드하며 진행 상황, 속도, 남은 시간을 표시합니다.',
    f5Title: '항상 최신',
    f5: 'VidSnare와 다운로드 엔진은 자동으로 업데이트됩니다.',
    f6Title: '여러분의 언어로',
    f6: '26개 언어 지원, 라이트·다크 테마 제공.',
    shotDownload: '재생목록에서 동영상 고르기',
    shotQueue: '다운로드 대기열',
    installTitle: '설치',
    downloadDeb: "Ubuntu / Debian용 다운로드",
    appImageLink: "다른 Linux인가요? AppImage 받기",
    installHelp: "설치 도움말",
    recommended: "권장",
    tabWindows: "Windows",
    tabDeb: "Ubuntu, Debian, Mint",
    tabAppImage: "기타 Linux (AppImage)",
    winStep1: "위 버튼으로 VidSnare-Setup.exe를 다운로드하세요.",
    winStep2: "파일을 여세요. Windows가 “Windows의 PC 보호”를 표시하면 “추가 정보”를 누른 뒤 “실행”을 클릭하세요. VidSnare가 아직 코드 서명되지 않아 나타나는 메시지입니다.",
    winStep3: "설치 프로그램을 따라 진행하세요. 이후에는 시작 메뉴에서 VidSnare를 여세요.",
    winUpdates: "업데이트는 자동으로 설치됩니다.",
    debStep1: "위 버튼으로 패키지를 받거나 터미널에서 실행하세요:",
    debStep2: "저장된 폴더에서 설치하세요:",
    debStep3: "애플리케이션 메뉴에서 VidSnare를 열거나 다음을 실행하세요:",
    debUpdates: "새 버전이 나오면 VidSnare가 알려 줍니다. 같은 방법으로 설치하세요.",
    debRemove: "제거하려면:",
    appStep1: "위 링크로 AppImage를 받거나 터미널에서 실행하세요:",
    appStep2: "실행을 허용한 뒤 시작하세요:",
    appStep2Alt: "터미널 없이: 파일을 오른쪽 클릭 → 속성 → 권한 → 프로그램으로 실행 허용 후 더블 클릭하세요.",
    appUpdates: "AppImage는 자동으로 업데이트됩니다.",
    troubleTitle: "실행되지 않으면",
    troubleFuse: "“libfuse.so.2” 관련 오류는 AppImage에 필요한 라이브러리가 없다는 뜻입니다. 사용하는 시스템에 맞게 설치하세요:",
    troubleSandbox: "Ubuntu 24.04 이상에서 “sandbox” 관련 오류가 나면 Ubuntu / Debian용 패키지를 사용하세요. 필요한 설정을 대신 해 줍니다.",
    copy: "복사",
    copied: "복사됨",
    usageTitle: "사용 방법",
    use1: "YouTube에서 동영상, 재생목록 또는 채널 링크를 복사하세요.",
    use2: "VidSnare 상단 입력란에 붙여넣으세요(Ctrl+V 또는 오른쪽 클릭 → 붙여넣기). 미리 보기가 나타납니다.",
    use3: "동영상 또는 오디오, 화질, 폴더를 고른 뒤 “다운로드”를 클릭하세요.",
    use4: "왼쪽의 “대기열”을 클릭하면 진행 상황을 볼 수 있습니다. 끝나면 “파일 열기”를 클릭하세요.",
    disclaimer: 'YouTube 서비스 약관과 저작권법을 지킬 책임은 사용자에게 있습니다. 다운로드할 권리가 있는 콘텐츠만 다운로드하세요.',
    license: '개인적·비상업적 용도로 무료입니다.',
    source: '소스 코드',
    notAffiliated: 'YouTube 및 Google과 관련이 없습니다.',
    language: '언어'
  },
  'zh-TW': {
    title: 'VidSnare – 下載 YouTube 影片與音訊',
    tagline: '輕鬆下載 YouTube 影片和音樂。',
    lead: '貼上連結、選擇畫質，其餘交給 VidSnare。Windows 和 Linux 個人使用免費。',
    downloadFor: '下載 {os} 版',
    otherDownloads: '其他下載',
    version: '版本 {version}',
    comingSoon: '第一個版本即將推出。',
    onlyWinLinux: 'VidSnare 支援 Windows 和 Linux。',
    fileWindows: 'Windows 10 和 11 – 安裝程式',
    fileAppImage: 'Linux – AppImage，適用所有發行版',
    fileDeb: 'Linux – Debian / Ubuntu 套件',
    featuresTitle: '功能',
    f1Title: '播放清單與頻道',
    f1: '載入整個播放清單或頻道，只挑你想要的影片。',
    f2Title: '影片或音訊',
    f2: '最高 4K 影片，或只存音訊（MP3、M4A、Opus）。',
    f3Title: '字幕',
    f3: '下載你選擇語言的字幕，可存成檔案或嵌入影片。',
    f4Title: '下載佇列',
    f4: '同時下載多個項目，顯示進度、速度和剩餘時間。',
    f5Title: '隨時保持最新',
    f5: 'VidSnare 和下載引擎會自動更新。',
    f6Title: '你的語言',
    f6: '支援 26 種語言，提供淺色和深色主題。',
    shotDownload: '從播放清單挑選影片',
    shotQueue: '下載佇列',
    installTitle: '安裝',
    downloadDeb: "下載 Ubuntu / Debian 版",
    appImageLink: "其他 Linux？下載 AppImage",
    installHelp: "安裝說明",
    recommended: "建議",
    tabWindows: "Windows",
    tabDeb: "Ubuntu、Debian、Mint",
    tabAppImage: "其他 Linux（AppImage）",
    winStep1: "用上方的按鈕下載 VidSnare-Setup.exe。",
    winStep2: "開啟檔案。如果 Windows 顯示「Windows 已保護您的電腦」，請點選「其他資訊」，再點選「仍要執行」。這是因為 VidSnare 尚未經過程式碼簽署。",
    winStep3: "依照安裝程式的步驟完成。之後從「開始」功能表開啟 VidSnare。",
    winUpdates: "更新會自動安裝。",
    debStep1: "用上方的按鈕下載套件，或在終端機執行：",
    debStep2: "在存放檔案的資料夾中安裝：",
    debStep3: "從應用程式選單開啟 VidSnare，或執行：",
    debUpdates: "有新版本時，VidSnare 會通知你。用同樣的方式安裝即可。",
    debRemove: "解除安裝：",
    appStep1: "用上方的連結下載 AppImage，或在終端機執行：",
    appStep2: "允許執行後啟動：",
    appStep2Alt: "不用終端機：在檔案上按右鍵 → 內容 → 權限 → 允許以程式執行，然後按兩下開啟。",
    appUpdates: "AppImage 會自動更新。",
    troubleTitle: "如果無法啟動",
    troubleFuse: "出現「libfuse.so.2」相關錯誤，表示缺少 AppImage 需要的函式庫。請依你的系統安裝：",
    troubleSandbox: "在 Ubuntu 24.04 或更新版本出現「sandbox」相關錯誤：請改用 Ubuntu / Debian 套件，它會自動完成設定。",
    copy: "複製",
    copied: "已複製",
    usageTitle: "使用方式",
    use1: "在 YouTube 複製影片、播放清單或頻道的連結。",
    use2: "在 VidSnare 上方的欄位貼上（Ctrl+V 或按右鍵 →「貼上」），就會出現預覽。",
    use3: "選擇影片或音訊、畫質和資料夾，然後點選「下載」。",
    use4: "點選左側的「佇列」查看進度。完成後點選「開啟檔案」。",
    disclaimer: '遵守 YouTube 服務條款和著作權法是您的責任。請只下載您有權下載的內容。',
    license: '個人非商業使用免費。',
    source: '原始碼',
    notAffiliated: '與 YouTube 或 Google 無關。',
    language: '語言'
  },
  hi: {
    title: 'VidSnare – YouTube से वीडियो और ऑडियो डाउनलोड करें',
    tagline: 'YouTube से वीडियो और म्यूज़िक डाउनलोड करें। बिल्कुल आसान।',
    lead: 'लिंक चिपकाएँ, क्वालिटी चुनें, बाकी VidSnare कर देगा। Windows और Linux पर निजी इस्तेमाल के लिए मुफ़्त।',
    downloadFor: '{os} के लिए डाउनलोड करें',
    otherDownloads: 'दूसरे डाउनलोड',
    version: 'वर्शन {version}',
    comingSoon: 'पहला रिलीज़ जल्द आ रहा है।',
    onlyWinLinux: 'VidSnare Windows और Linux के लिए उपलब्ध है।',
    fileWindows: 'Windows 10 और 11 – इंस्टॉलर',
    fileAppImage: 'Linux – AppImage, हर डिस्ट्रीब्यूशन',
    fileDeb: 'Linux – Debian / Ubuntu पैकेज',
    featuresTitle: 'यह क्या करता है',
    f1Title: 'प्लेलिस्ट और चैनल',
    f1: 'पूरी प्लेलिस्ट या चैनल लोड करें और ठीक वही वीडियो चुनें जो चाहिए।',
    f2Title: 'वीडियो या ऑडियो',
    f2: '4K तक वीडियो, या सिर्फ़ आवाज़ MP3, M4A या Opus में।',
    f3Title: 'सबटाइटल',
    f3: 'अपनी चुनी भाषाओं में सबटाइटल, अलग फ़ाइल में या वीडियो के अंदर।',
    f4Title: 'डाउनलोड कतार',
    f4: 'एक साथ कई डाउनलोड, प्रगति, स्पीड और बचे समय के साथ।',
    f5Title: 'हमेशा अपडेट',
    f5: 'VidSnare और उसका डाउनलोड इंजन अपने-आप अपडेट होते हैं।',
    f6Title: 'आपकी भाषा',
    f6: '26 भाषाओं में, हल्की और गहरी थीम के साथ।',
    shotDownload: 'प्लेलिस्ट से वीडियो चुनना',
    shotQueue: 'डाउनलोड कतार',
    installTitle: 'इंस्टॉल करना',
    downloadDeb: "Ubuntu / Debian के लिए डाउनलोड करें",
    appImageLink: "कोई दूसरा Linux? AppImage लें",
    installHelp: "इंस्टॉल करने में मदद",
    recommended: "सुझाया गया",
    tabWindows: "Windows",
    tabDeb: "Ubuntu, Debian, Mint",
    tabAppImage: "दूसरा Linux (AppImage)",
    winStep1: "ऊपर दिए बटन से VidSnare-Setup.exe डाउनलोड करें।",
    winStep2: "फ़ाइल खोलें। अगर Windows “Windows ने आपके PC को सुरक्षित किया” दिखाए, तो “अधिक जानकारी” और फिर “फिर भी चलाएँ” पर क्लिक करें। यह इसलिए दिखता है क्योंकि VidSnare पर अभी डिजिटल हस्ताक्षर नहीं है।",
    winStep3: "इंस्टॉलर के चरण पूरे करें। इसके बाद VidSnare को Start मेनू से खोलें।",
    winUpdates: "अपडेट अपने-आप इंस्टॉल होते हैं।",
    debStep1: "ऊपर दिए बटन से पैकेज डाउनलोड करें, या टर्मिनल में चलाएँ:",
    debStep2: "जिस फ़ोल्डर में फ़ाइल सहेजी गई है, वहाँ से इंस्टॉल करें:",
    debStep3: "VidSnare को ऐप्लिकेशन मेनू से खोलें, या चलाएँ:",
    debUpdates: "नया वर्शन आने पर VidSnare आपको बताएगा। उसे भी इसी तरह इंस्टॉल करें।",
    debRemove: "अनइंस्टॉल करने के लिए:",
    appStep1: "ऊपर दिए लिंक से AppImage डाउनलोड करें, या टर्मिनल में चलाएँ:",
    appStep2: "चलाने की अनुमति दें और शुरू करें:",
    appStep2Alt: "बिना टर्मिनल के: फ़ाइल पर राइट-क्लिक → Properties → Permissions → प्रोग्राम की तरह चलाने की अनुमति दें, फिर डबल-क्लिक करें।",
    appUpdates: "AppImage अपने-आप अपडेट होता है।",
    troubleTitle: "अगर यह शुरू न हो",
    troubleFuse: "“libfuse.so.2” वाली त्रुटि का मतलब है कि AppImage के लिए ज़रूरी लाइब्रेरी मौजूद नहीं है। अपने सिस्टम के लिए इसे इंस्टॉल करें:",
    troubleSandbox: "Ubuntu 24.04 या नए में “sandbox” वाली त्रुटि: इसके बजाय Ubuntu / Debian पैकेज इस्तेमाल करें, वह यह सेटिंग अपने-आप कर देता है।",
    copy: "कॉपी करें",
    copied: "कॉपी हो गया",
    usageTitle: "इस्तेमाल कैसे करें",
    use1: "YouTube पर किसी वीडियो, प्लेलिस्ट या चैनल का लिंक कॉपी करें।",
    use2: "VidSnare में ऊपर वाले बॉक्स में चिपकाएँ (Ctrl+V या राइट-क्लिक → चिपकाएँ)। एक प्रीव्यू दिखेगा।",
    use3: "वीडियो या ऑडियो, क्वालिटी और फ़ोल्डर चुनें, फिर “डाउनलोड करें” पर क्लिक करें।",
    use4: "प्रगति देखने के लिए बाईं ओर “कतार” पर क्लिक करें। पूरा होने पर “फ़ाइल खोलें” पर क्लिक करें।",
    disclaimer: 'YouTube की सेवा की शर्तों और कॉपीराइट क़ानून का पालन करना आपकी ज़िम्मेदारी है। सिर्फ़ वही सामग्री डाउनलोड करें जिसे डाउनलोड करने का आपको अधिकार है।',
    license: 'निजी, गैर-व्यावसायिक इस्तेमाल के लिए मुफ़्त।',
    source: 'सोर्स कोड',
    notAffiliated: 'YouTube या Google से संबद्ध नहीं।',
    language: 'भाषा'
  },
  nl: {
    title: 'VidSnare – download video’s en audio van YouTube',
    tagline: 'Download video’s en muziek van YouTube. Gewoon simpel.',
    lead: 'Plak een link, kies de kwaliteit en VidSnare doet de rest. Gratis voor persoonlijk gebruik op Windows en Linux.',
    downloadFor: 'Downloaden voor {os}',
    otherDownloads: 'Andere downloads',
    version: 'Versie {version}',
    comingSoon: 'De eerste versie komt binnenkort.',
    onlyWinLinux: 'VidSnare is er voor Windows en Linux.',
    fileWindows: 'Windows 10 en 11 – installatieprogramma',
    fileAppImage: 'Linux – AppImage, elke distributie',
    fileDeb: 'Linux – Debian-/Ubuntu-pakket',
    featuresTitle: 'Wat het doet',
    f1Title: 'Afspeellijsten en kanalen',
    f1: 'Laad een hele afspeellijst of een kanaal en kies precies de video’s die je wilt.',
    f2Title: 'Video of audio',
    f2: 'Video tot 4K, of alleen het geluid als MP3, M4A of Opus.',
    f3Title: 'Ondertiteling',
    f3: 'Ondertiteling in de talen die je kiest, als bestand of in de video.',
    f4Title: 'Downloadwachtrij',
    f4: 'Meerdere downloads tegelijk, met voortgang, snelheid en resterende tijd.',
    f5Title: 'Altijd up-to-date',
    f5: 'VidSnare en de download-engine werken zichzelf automatisch bij.',
    f6Title: 'Jouw taal',
    f6: 'Beschikbaar in 26 talen, met licht en donker thema.',
    shotDownload: 'Video’s kiezen uit een afspeellijst',
    shotQueue: 'De downloadwachtrij',
    installTitle: 'Installeren',
    downloadDeb: "Downloaden voor Ubuntu / Debian",
    appImageLink: "Ander Linux? Download de AppImage",
    installHelp: "Hulp bij installeren",
    recommended: "Aanbevolen",
    tabWindows: "Windows",
    tabDeb: "Ubuntu, Debian, Mint",
    tabAppImage: "Ander Linux (AppImage)",
    winStep1: "Download VidSnare-Setup.exe met de knop hierboven.",
    winStep2: "Open het bestand. Als Windows “Uw pc is beveiligd door Windows” toont, klik dan op “Meer informatie” en daarna op “Toch uitvoeren”. Dit verschijnt omdat VidSnare nog niet ondertekend is.",
    winStep3: "Volg het installatieprogramma. Open VidSnare daarna via het Startmenu.",
    winUpdates: "Updates worden automatisch geïnstalleerd.",
    debStep1: "Download het pakket met de knop hierboven, of in een terminal:",
    debStep2: "Installeer het vanuit de map waarin het is opgeslagen:",
    debStep3: "Open VidSnare via het applicatiemenu, of voer uit:",
    debUpdates: "Als er een nieuwe versie is, laat VidSnare het weten. Installeer die op dezelfde manier.",
    debRemove: "Verwijderen:",
    appStep1: "Download de AppImage via de link hierboven, of in een terminal:",
    appStep2: "Sta uitvoeren toe en start hem:",
    appStep2Alt: "Zonder terminal: rechtsklik op het bestand → Eigenschappen → Rechten → uitvoeren als programma toestaan, en dubbelklik erop.",
    appUpdates: "De AppImage werkt zichzelf automatisch bij.",
    troubleTitle: "Als hij niet start",
    troubleFuse: "Een fout over “libfuse.so.2” betekent dat een bibliotheek ontbreekt die AppImages nodig hebben. Installeer die voor je systeem:",
    troubleSandbox: "Een fout over de “sandbox” op Ubuntu 24.04 of nieuwer: gebruik in plaats daarvan het Ubuntu-/Debian-pakket, dat regelt dit voor je.",
    copy: "Kopiëren",
    copied: "Gekopieerd",
    usageTitle: "Zo gebruik je het",
    use1: "Kopieer op YouTube de link van een video, afspeellijst of kanaal.",
    use2: "Plak hem in VidSnare in het vak bovenaan (Ctrl+V of rechtsklik → Plakken). Er verschijnt een voorbeeld.",
    use3: "Kies video of audio, de kwaliteit en de map, en klik op ‘Downloaden’.",
    use4: "Klik links op ‘Wachtrij’ om de voortgang te volgen. Als het klaar is, klik je op ‘Bestand openen’.",
    disclaimer: 'Je bent zelf verantwoordelijk voor het naleven van de Servicevoorwaarden van YouTube en het auteursrecht. Download alleen inhoud die je mag downloaden.',
    license: 'Gratis voor persoonlijk, niet-commercieel gebruik.',
    source: 'Broncode',
    notAffiliated: 'Niet verbonden aan YouTube of Google.',
    language: 'Taal'
  },
  cs: {
    title: 'VidSnare – stahujte videa a zvuk z YouTube',
    tagline: 'Stahujte videa a hudbu z YouTube. Jednoduše.',
    lead: 'Vložte odkaz, vyberte kvalitu a zbytek zařídí VidSnare. Zdarma pro osobní použití ve Windows a Linuxu.',
    downloadFor: 'Stáhnout pro {os}',
    otherDownloads: 'Další verze',
    version: 'Verze {version}',
    comingSoon: 'První verze vyjde brzy.',
    onlyWinLinux: 'VidSnare je k dispozici pro Windows a Linux.',
    fileWindows: 'Windows 10 a 11 – instalátor',
    fileAppImage: 'Linux – AppImage, libovolná distribuce',
    fileDeb: 'Linux – balíček Debian / Ubuntu',
    featuresTitle: 'Co umí',
    f1Title: 'Playlisty a kanály',
    f1: 'Načtěte celý playlist nebo kanál a vyberte přesně ta videa, která chcete.',
    f2Title: 'Video, nebo zvuk',
    f2: 'Video až ve 4K, nebo jen zvuk jako MP3, M4A či Opus.',
    f3Title: 'Titulky',
    f3: 'Titulky ve zvolených jazycích, jako soubor nebo přímo ve videu.',
    f4Title: 'Fronta stahování',
    f4: 'Více stahování najednou, s průběhem, rychlostí a zbývajícím časem.',
    f5Title: 'Vždy aktuální',
    f5: 'VidSnare i jeho stahovací jádro se aktualizují samy.',
    f6Title: 'Váš jazyk',
    f6: 'K dispozici ve 26 jazycích, se světlým i tmavým motivem.',
    shotDownload: 'Výběr videí z playlistu',
    shotQueue: 'Fronta stahování',
    installTitle: 'Instalace',
    downloadDeb: "Stáhnout pro Ubuntu / Debian",
    appImageLink: "Jiný Linux? Stáhněte AppImage",
    installHelp: "Nápověda k instalaci",
    recommended: "Doporučeno",
    tabWindows: "Windows",
    tabDeb: "Ubuntu, Debian, Mint",
    tabAppImage: "Jiný Linux (AppImage)",
    winStep1: "Stáhněte VidSnare-Setup.exe tlačítkem výše.",
    winStep2: "Otevřete soubor. Pokud Windows zobrazí „Systém Windows ochránil váš počítač“, klikněte na „Další informace“ a pak na „Přesto spustit“. Zobrazí se to, protože VidSnare zatím není digitálně podepsaný.",
    winStep3: "Projděte instalátorem. Potom spouštějte VidSnare z nabídky Start.",
    winUpdates: "Aktualizace se instalují automaticky.",
    debStep1: "Stáhněte balíček tlačítkem výše, nebo v terminálu:",
    debStep2: "Nainstalujte ho ze složky, kam se uložil:",
    debStep3: "Otevřete VidSnare z nabídky aplikací, nebo spusťte:",
    debUpdates: "Až vyjde nová verze, VidSnare vám dá vědět. Nainstalujte ji stejným způsobem.",
    debRemove: "Odinstalace:",
    appStep1: "Stáhněte AppImage odkazem výše, nebo v terminálu:",
    appStep2: "Povolte spuštění a spusťte ho:",
    appStep2Alt: "Bez terminálu: klikněte na soubor pravým tlačítkem → Vlastnosti → Oprávnění → povolit spouštění jako program, pak na něj dvakrát klikněte.",
    appUpdates: "AppImage se aktualizuje sám.",
    troubleTitle: "Když se nespustí",
    troubleFuse: "Chyba týkající se „libfuse.so.2“ znamená, že chybí knihovna, kterou AppImage potřebuje. Nainstalujte ji pro svůj systém:",
    troubleSandbox: "Chyba týkající se „sandbox“ v Ubuntu 24.04 nebo novějším: použijte raději balíček pro Ubuntu / Debian, který to nastaví za vás.",
    copy: "Kopírovat",
    copied: "Zkopírováno",
    usageTitle: "Jak ho používat",
    use1: "Na YouTube zkopírujte odkaz na video, playlist nebo kanál.",
    use2: "Ve VidSnare ho vložte do pole nahoře (Ctrl+V nebo pravé tlačítko → Vložit). Zobrazí se náhled.",
    use3: "Vyberte video nebo zvuk, kvalitu a složku, potom klikněte na „Stáhnout“.",
    use4: "Klikněte vlevo na „Fronta“ a sledujte průběh. Po dokončení klikněte na „Otevřít soubor“.",
    disclaimer: 'Odpovídáte za dodržování smluvních podmínek YouTube a autorského práva. Stahujte jen obsah, ke kterému máte právo.',
    license: 'Zdarma pro osobní, nekomerční použití.',
    source: 'Zdrojový kód',
    notAffiliated: 'Není spojeno s YouTube ani Googlem.',
    language: 'Jazyk'
  },
  ro: {
    title: 'VidSnare – descarcă videoclipuri și audio de pe YouTube',
    tagline: 'Descarcă videoclipuri și muzică de pe YouTube. Simplu.',
    lead: 'Lipește un link, alege calitatea și VidSnare face restul. Gratuit pentru uz personal pe Windows și Linux.',
    downloadFor: 'Descarcă pentru {os}',
    otherDownloads: 'Alte descărcări',
    version: 'Versiunea {version}',
    comingSoon: 'Prima versiune apare în curând.',
    onlyWinLinux: 'VidSnare este disponibil pentru Windows și Linux.',
    fileWindows: 'Windows 10 și 11 – program de instalare',
    fileAppImage: 'Linux – AppImage, orice distribuție',
    fileDeb: 'Linux – pachet Debian / Ubuntu',
    featuresTitle: 'Ce face',
    f1Title: 'Playlisturi și canale',
    f1: 'Încarcă un playlist sau un canal întreg și alege exact videoclipurile pe care le vrei.',
    f2Title: 'Video sau audio',
    f2: 'Video până la 4K sau doar sunetul ca MP3, M4A ori Opus.',
    f3Title: 'Subtitrări',
    f3: 'Subtitrări în limbile alese, ca fișier separat sau în videoclip.',
    f4Title: 'Coadă de descărcări',
    f4: 'Mai multe descărcări simultan, cu progres, viteză și timp rămas.',
    f5Title: 'Mereu actualizat',
    f5: 'VidSnare și motorul său de descărcare se actualizează singure.',
    f6Title: 'Limba ta',
    f6: 'Disponibil în 26 de limbi, cu temă luminoasă și întunecată.',
    shotDownload: 'Alegerea videoclipurilor dintr-un playlist',
    shotQueue: 'Coada de descărcări',
    installTitle: 'Instalare',
    downloadDeb: "Descarcă pentru Ubuntu / Debian",
    appImageLink: "Alt Linux? Descarcă AppImage",
    installHelp: "Ajutor la instalare",
    recommended: "Recomandat",
    tabWindows: "Windows",
    tabDeb: "Ubuntu, Debian, Mint",
    tabAppImage: "Alt Linux (AppImage)",
    winStep1: "Descarcă VidSnare-Setup.exe cu butonul de mai sus.",
    winStep2: "Deschide-l. Dacă Windows afișează „Windows v-a protejat PC-ul”, apasă „Mai multe informații”, apoi „Rulează oricum”. Mesajul apare pentru că VidSnare nu este încă semnat digital.",
    winStep3: "Urmează pașii programului de instalare. Apoi deschide VidSnare din meniul Start.",
    winUpdates: "Actualizările se instalează automat.",
    debStep1: "Descarcă pachetul cu butonul de mai sus sau în terminal:",
    debStep2: "Instalează-l din dosarul în care a fost salvat:",
    debStep3: "Deschide VidSnare din meniul de aplicații sau rulează:",
    debUpdates: "Când apare o versiune nouă, VidSnare te anunță. Instaleaz-o la fel.",
    debRemove: "Pentru dezinstalare:",
    appStep1: "Descarcă AppImage cu linkul de mai sus sau în terminal:",
    appStep2: "Permite rularea și pornește-l:",
    appStep2Alt: "Fără terminal: clic dreapta pe fișier → Proprietăți → Permisiuni → permite rularea ca program, apoi dublu clic.",
    appUpdates: "AppImage se actualizează singur.",
    troubleTitle: "Dacă nu pornește",
    troubleFuse: "O eroare despre „libfuse.so.2” înseamnă că lipsește o bibliotecă de care au nevoie AppImage-urile. Instaleaz-o pentru sistemul tău:",
    troubleSandbox: "O eroare despre „sandbox” pe Ubuntu 24.04 sau mai nou: folosește în schimb pachetul pentru Ubuntu / Debian, care configurează asta pentru tine.",
    copy: "Copiază",
    copied: "Copiat",
    usageTitle: "Cum îl folosești",
    use1: "Pe YouTube, copiază linkul unui videoclip, playlist sau canal.",
    use2: "În VidSnare, lipește-l în caseta de sus (Ctrl+V sau clic dreapta → Lipește). Apare o previzualizare.",
    use3: "Alege video sau audio, calitatea și dosarul, apoi apasă „Descarcă”.",
    use4: "Apasă „Coadă” în stânga ca să vezi progresul. Când e gata, apasă „Deschide fișierul”.",
    disclaimer: 'Ești responsabil să respecți Termenii și condițiile YouTube și legea drepturilor de autor. Descarcă doar conținut pe care ai dreptul să-l descarci.',
    license: 'Gratuit pentru uz personal, necomercial.',
    source: 'Cod sursă',
    notAffiliated: 'Nu este afiliat cu YouTube sau Google.',
    language: 'Limbă'
  },
  hu: {
    title: 'VidSnare – videók és hang letöltése a YouTube-ról',
    tagline: 'Videók és zene letöltése a YouTube-ról. Egyszerűen.',
    lead: 'Illessz be egy linket, válaszd ki a minőséget, a többit a VidSnare elintézi. Személyes használatra ingyenes Windowson és Linuxon.',
    downloadFor: 'Letöltés {os} rendszerre',
    otherDownloads: 'További letöltések',
    version: '{version} verzió',
    comingSoon: 'Az első kiadás hamarosan érkezik.',
    onlyWinLinux: 'A VidSnare Windowsra és Linuxra érhető el.',
    fileWindows: 'Windows 10 és 11 – telepítő',
    fileAppImage: 'Linux – AppImage, bármely disztribúció',
    fileDeb: 'Linux – Debian/Ubuntu csomag',
    featuresTitle: 'Mit tud',
    f1Title: 'Lejátszási listák és csatornák',
    f1: 'Tölts be egy teljes listát vagy csatornát, és válaszd ki pontosan a kívánt videókat.',
    f2Title: 'Videó vagy hang',
    f2: 'Videó akár 4K-ban, vagy csak a hang MP3, M4A vagy Opus formátumban.',
    f3Title: 'Feliratok',
    f3: 'Feliratok a választott nyelveken, külön fájlként vagy a videóba ágyazva.',
    f4Title: 'Letöltési sor',
    f4: 'Több letöltés egyszerre, folyamattal, sebességgel és hátralévő idővel.',
    f5Title: 'Mindig naprakész',
    f5: 'A VidSnare és a letöltőmotorja automatikusan frissül.',
    f6Title: 'A te nyelveden',
    f6: '26 nyelven érhető el, világos és sötét témával.',
    shotDownload: 'Videók kiválasztása egy listából',
    shotQueue: 'A letöltési sor',
    installTitle: 'Telepítés',
    downloadDeb: "Letöltés Ubuntu / Debian rendszerre",
    appImageLink: "Más Linux? Töltsd le az AppImage-et",
    installHelp: "Segítség a telepítéshez",
    recommended: "Ajánlott",
    tabWindows: "Windows",
    tabDeb: "Ubuntu, Debian, Mint",
    tabAppImage: "Más Linux (AppImage)",
    winStep1: "Töltsd le a VidSnare-Setup.exe fájlt a fenti gombbal.",
    winStep2: "Nyisd meg. Ha a Windows azt írja, hogy „A Windows megvédte a számítógépet”, kattints a „További információ”, majd a „Futtatás mindenképp” gombra. Ez azért jelenik meg, mert a VidSnare még nincs digitálisan aláírva.",
    winStep3: "Kövesd a telepítő lépéseit. Utána a Start menüből indíthatod a VidSnare-t.",
    winUpdates: "A frissítések automatikusan települnek.",
    debStep1: "Töltsd le a csomagot a fenti gombbal, vagy terminálban:",
    debStep2: "Telepítsd abból a mappából, ahová mentetted:",
    debStep3: "Nyisd meg a VidSnare-t az alkalmazások menüjéből, vagy futtasd:",
    debUpdates: "Ha új verzió jelenik meg, a VidSnare szól. Ugyanígy telepítsd.",
    debRemove: "Eltávolítás:",
    appStep1: "Töltsd le az AppImage-et a fenti linkkel, vagy terminálban:",
    appStep2: "Engedélyezd a futtatást, és indítsd el:",
    appStep2Alt: "Terminál nélkül: kattints jobb gombbal a fájlra → Tulajdonságok → Jogosultságok → futtatás programként engedélyezése, majd kattints rá duplán.",
    appUpdates: "Az AppImage automatikusan frissül.",
    troubleTitle: "Ha nem indul el",
    troubleFuse: "A „libfuse.so.2” hiba azt jelenti, hogy hiányzik egy könyvtár, amely az AppImage-ekhez kell. Telepítsd a rendszeredhez:",
    troubleSandbox: "„sandbox” hiba Ubuntu 24.04 vagy újabb rendszeren: használd inkább az Ubuntu/Debian csomagot, az elvégzi ezt a beállítást.",
    copy: "Másolás",
    copied: "Másolva",
    usageTitle: "Hogyan használd",
    use1: "A YouTube-on másold ki egy videó, lejátszási lista vagy csatorna linkjét.",
    use2: "A VidSnare-ben illeszd be a felső mezőbe (Ctrl+V vagy jobb klikk → Beillesztés). Megjelenik egy előnézet.",
    use3: "Válaszd ki, hogy videót vagy hangot szeretnél, a minőséget és a mappát, majd kattints a „Letöltés” gombra.",
    use4: "Kattints bal oldalt a „Sor” elemre a folyamat követéséhez. Ha elkészült, kattints a „Fájl megnyitása” gombra.",
    disclaimer: 'Te felelsz a YouTube Szolgáltatási feltételeinek és a szerzői jognak a betartásáért. Csak olyan tartalmat tölts le, amelyhez jogod van.',
    license: 'Személyes, nem kereskedelmi használatra ingyenes.',
    source: 'Forráskód',
    notAffiliated: 'Nem áll kapcsolatban a YouTube-bal vagy a Google-lel.',
    language: 'Nyelv'
  },
  sv: {
    title: 'VidSnare – ladda ned video och ljud från YouTube',
    tagline: 'Ladda ned video och musik från YouTube. Enkelt.',
    lead: 'Klistra in en länk, välj kvalitet så sköter VidSnare resten. Gratis för privat bruk på Windows och Linux.',
    downloadFor: 'Ladda ned för {os}',
    otherDownloads: 'Andra nedladdningar',
    version: 'Version {version}',
    comingSoon: 'Den första versionen kommer snart.',
    onlyWinLinux: 'VidSnare finns för Windows och Linux.',
    fileWindows: 'Windows 10 och 11 – installationsprogram',
    fileAppImage: 'Linux – AppImage, alla distributioner',
    fileDeb: 'Linux – Debian-/Ubuntu-paket',
    featuresTitle: 'Vad den gör',
    f1Title: 'Spellistor och kanaler',
    f1: 'Läs in en hel spellista eller kanal och välj exakt de videor du vill ha.',
    f2Title: 'Video eller ljud',
    f2: 'Video upp till 4K, eller bara ljudet som MP3, M4A eller Opus.',
    f3Title: 'Undertexter',
    f3: 'Undertexter på de språk du väljer, som fil eller inbäddade i videon.',
    f4Title: 'Nedladdningskö',
    f4: 'Flera nedladdningar samtidigt, med förlopp, hastighet och tid kvar.',
    f5Title: 'Alltid uppdaterad',
    f5: 'VidSnare och dess nedladdningsmotor uppdaterar sig själva.',
    f6Title: 'Ditt språk',
    f6: 'Finns på 26 språk, med ljust och mörkt tema.',
    shotDownload: 'Välja videor från en spellista',
    shotQueue: 'Nedladdningskön',
    installTitle: 'Installation',
    downloadDeb: "Ladda ned för Ubuntu / Debian",
    appImageLink: "Annan Linux? Hämta AppImage",
    installHelp: "Hjälp med installationen",
    recommended: "Rekommenderas",
    tabWindows: "Windows",
    tabDeb: "Ubuntu, Debian, Mint",
    tabAppImage: "Annan Linux (AppImage)",
    winStep1: "Ladda ned VidSnare-Setup.exe med knappen ovan.",
    winStep2: "Öppna filen. Om Windows visar ”Datorn skyddades av Windows” klickar du på ”Mer information” och sedan ”Kör ändå”. Det visas eftersom VidSnare ännu inte är kodsignerad.",
    winStep3: "Följ installationsprogrammet. Öppna sedan VidSnare från Start-menyn.",
    winUpdates: "Uppdateringar installeras automatiskt.",
    debStep1: "Ladda ned paketet med knappen ovan, eller i en terminal:",
    debStep2: "Installera det från mappen där det sparades:",
    debStep3: "Öppna VidSnare från programmenyn, eller kör:",
    debUpdates: "När en ny version finns säger VidSnare till. Installera den på samma sätt.",
    debRemove: "Avinstallera:",
    appStep1: "Ladda ned AppImage med länken ovan, eller i en terminal:",
    appStep2: "Tillåt körning och starta den:",
    appStep2Alt: "Utan terminal: högerklicka på filen → Egenskaper → Behörigheter → tillåt körning som program, och dubbelklicka sedan.",
    appUpdates: "AppImage uppdaterar sig själv automatiskt.",
    troubleTitle: "Om den inte startar",
    troubleFuse: "Ett fel om ”libfuse.so.2” betyder att ett bibliotek som AppImage behöver saknas. Installera det för ditt system:",
    troubleSandbox: "Ett fel om ”sandbox” på Ubuntu 24.04 eller nyare: använd Ubuntu-/Debian-paketet i stället, det ordnar det åt dig.",
    copy: "Kopiera",
    copied: "Kopierat",
    usageTitle: "Så använder du den",
    use1: "Kopiera länken till en video, spellista eller kanal på YouTube.",
    use2: "Klistra in den i rutan överst i VidSnare (Ctrl+V eller högerklick → Klistra in). En förhandsvisning visas.",
    use3: "Välj video eller ljud, kvalitet och mapp och klicka sedan på ”Ladda ned”.",
    use4: "Klicka på ”Kö” till vänster för att följa förloppet. När det är klart klickar du på ”Öppna fil”.",
    disclaimer: 'Du ansvarar för att följa YouTubes användarvillkor och upphovsrättslagen. Ladda bara ned innehåll som du har rätt att ladda ned.',
    license: 'Gratis för privat, icke-kommersiellt bruk.',
    source: 'Källkod',
    notAffiliated: 'Inte knuten till YouTube eller Google.',
    language: 'Språk'
  },
  el: {
    title: 'VidSnare – κατεβάστε βίντεο και ήχο από το YouTube',
    tagline: 'Κατεβάστε βίντεο και μουσική από το YouTube. Απλά.',
    lead: 'Επικολλήστε έναν σύνδεσμο, επιλέξτε ποιότητα και το VidSnare κάνει τα υπόλοιπα. Δωρεάν για προσωπική χρήση σε Windows και Linux.',
    downloadFor: 'Λήψη για {os}',
    otherDownloads: 'Άλλες λήψεις',
    version: 'Έκδοση {version}',
    comingSoon: 'Η πρώτη έκδοση έρχεται σύντομα.',
    onlyWinLinux: 'Το VidSnare είναι διαθέσιμο για Windows και Linux.',
    fileWindows: 'Windows 10 και 11 – πρόγραμμα εγκατάστασης',
    fileAppImage: 'Linux – AppImage, κάθε διανομή',
    fileDeb: 'Linux – πακέτο Debian / Ubuntu',
    featuresTitle: 'Τι κάνει',
    f1Title: 'Λίστες αναπαραγωγής και κανάλια',
    f1: 'Φορτώστε ολόκληρη λίστα ή κανάλι και επιλέξτε ακριβώς τα βίντεο που θέλετε.',
    f2Title: 'Βίντεο ή ήχος',
    f2: 'Βίντεο έως 4K ή μόνο ο ήχος σε MP3, M4A ή Opus.',
    f3Title: 'Υπότιτλοι',
    f3: 'Υπότιτλοι στις γλώσσες που επιλέγετε, ως αρχείο ή μέσα στο βίντεο.',
    f4Title: 'Ουρά λήψεων',
    f4: 'Πολλές λήψεις ταυτόχρονα, με πρόοδο, ταχύτητα και χρόνο που απομένει.',
    f5Title: 'Πάντα ενημερωμένο',
    f5: 'Το VidSnare και η μηχανή λήψης του ενημερώνονται αυτόματα.',
    f6Title: 'Η γλώσσα σας',
    f6: 'Διαθέσιμο σε 26 γλώσσες, με ανοιχτό και σκούρο θέμα.',
    shotDownload: 'Επιλογή βίντεο από λίστα αναπαραγωγής',
    shotQueue: 'Η ουρά λήψεων',
    installTitle: 'Εγκατάσταση',
    downloadDeb: "Λήψη για Ubuntu / Debian",
    appImageLink: "Άλλο Linux; Κατεβάστε το AppImage",
    installHelp: "Βοήθεια εγκατάστασης",
    recommended: "Προτείνεται",
    tabWindows: "Windows",
    tabDeb: "Ubuntu, Debian, Mint",
    tabAppImage: "Άλλο Linux (AppImage)",
    winStep1: "Κατεβάστε το VidSnare-Setup.exe με το κουμπί παραπάνω.",
    winStep2: "Ανοίξτε το. Αν τα Windows δείξουν «Τα Windows προστάτευσαν τον υπολογιστή σας», πατήστε «Περισσότερες πληροφορίες» και μετά «Εκτέλεση οπωσδήποτε». Εμφανίζεται επειδή το VidSnare δεν έχει ακόμη ψηφιακή υπογραφή.",
    winStep3: "Ακολουθήστε το πρόγραμμα εγκατάστασης. Μετά ανοίξτε το VidSnare από το μενού Έναρξη.",
    winUpdates: "Οι ενημερώσεις εγκαθίστανται αυτόματα.",
    debStep1: "Κατεβάστε το πακέτο με το κουμπί παραπάνω ή σε τερματικό:",
    debStep2: "Εγκαταστήστε το από τον φάκελο όπου αποθηκεύτηκε:",
    debStep3: "Ανοίξτε το VidSnare από το μενού εφαρμογών ή εκτελέστε:",
    debUpdates: "Όταν βγει νέα έκδοση, το VidSnare θα σας ενημερώσει. Εγκαταστήστε την με τον ίδιο τρόπο.",
    debRemove: "Για απεγκατάσταση:",
    appStep1: "Κατεβάστε το AppImage από τον σύνδεσμο παραπάνω ή σε τερματικό:",
    appStep2: "Επιτρέψτε την εκτέλεση και ξεκινήστε το:",
    appStep2Alt: "Χωρίς τερματικό: δεξί κλικ στο αρχείο → Ιδιότητες → Δικαιώματα → επιτρέψτε την εκτέλεση ως πρόγραμμα και κάντε διπλό κλικ.",
    appUpdates: "Το AppImage ενημερώνεται αυτόματα.",
    troubleTitle: "Αν δεν ξεκινά",
    troubleFuse: "Ένα σφάλμα για το «libfuse.so.2» σημαίνει ότι λείπει μια βιβλιοθήκη που χρειάζονται τα AppImage. Εγκαταστήστε την για το σύστημά σας:",
    troubleSandbox: "Ένα σφάλμα για το «sandbox» σε Ubuntu 24.04 ή νεότερο: χρησιμοποιήστε το πακέτο για Ubuntu / Debian, που το ρυθμίζει για εσάς.",
    copy: "Αντιγραφή",
    copied: "Αντιγράφηκε",
    usageTitle: "Πώς το χρησιμοποιείτε",
    use1: "Στο YouTube, αντιγράψτε τον σύνδεσμο ενός βίντεο, μιας λίστας ή ενός καναλιού.",
    use2: "Στο VidSnare, επικολλήστε τον στο πλαίσιο επάνω (Ctrl+V ή δεξί κλικ → Επικόλληση). Εμφανίζεται μια προεπισκόπηση.",
    use3: "Επιλέξτε βίντεο ή ήχο, ποιότητα και φάκελο και πατήστε «Λήψη».",
    use4: "Πατήστε «Ουρά» στα αριστερά για να δείτε την πρόοδο. Όταν τελειώσει, πατήστε «Άνοιγμα αρχείου».",
    disclaimer: 'Είστε υπεύθυνοι για την τήρηση των Όρων Παροχής Υπηρεσιών του YouTube και της νομοθεσίας για τα πνευματικά δικαιώματα. Κατεβάζετε μόνο περιεχόμενο που έχετε δικαίωμα να κατεβάσετε.',
    license: 'Δωρεάν για προσωπική, μη εμπορική χρήση.',
    source: 'Πηγαίος κώδικας',
    notAffiliated: 'Δεν συνδέεται με το YouTube ή την Google.',
    language: 'Γλώσσα'
  },
  th: {
    title: 'VidSnare – ดาวน์โหลดวิดีโอและเสียงจาก YouTube',
    tagline: 'ดาวน์โหลดวิดีโอและเพลงจาก YouTube ง่าย ๆ',
    lead: 'วางลิงก์ เลือกคุณภาพ แล้ว VidSnare จะจัดการที่เหลือให้ ใช้ฟรีสำหรับการใช้งานส่วนตัวบน Windows และ Linux',
    downloadFor: 'ดาวน์โหลดสำหรับ {os}',
    otherDownloads: 'ดาวน์โหลดอื่น ๆ',
    version: 'เวอร์ชัน {version}',
    comingSoon: 'รุ่นแรกกำลังจะมาเร็ว ๆ นี้',
    onlyWinLinux: 'VidSnare ใช้ได้บน Windows และ Linux',
    fileWindows: 'Windows 10 และ 11 – ตัวติดตั้ง',
    fileAppImage: 'Linux – AppImage ใช้ได้ทุกดิสทริบิวชัน',
    fileDeb: 'Linux – แพ็กเกจ Debian / Ubuntu',
    featuresTitle: 'ทำอะไรได้บ้าง',
    f1Title: 'เพลย์ลิสต์และช่อง',
    f1: 'โหลดทั้งเพลย์ลิสต์หรือทั้งช่อง แล้วเลือกเฉพาะวิดีโอที่ต้องการ',
    f2Title: 'วิดีโอหรือเสียง',
    f2: 'วิดีโอสูงสุด 4K หรือเฉพาะเสียงเป็น MP3, M4A หรือ Opus',
    f3Title: 'คำบรรยาย',
    f3: 'คำบรรยายในภาษาที่คุณเลือก เป็นไฟล์แยกหรือฝังในวิดีโอ',
    f4Title: 'คิวดาวน์โหลด',
    f4: 'ดาวน์โหลดหลายรายการพร้อมกัน พร้อมแสดงความคืบหน้า ความเร็ว และเวลาที่เหลือ',
    f5Title: 'อัปเดตอยู่เสมอ',
    f5: 'VidSnare และเอนจินดาวน์โหลดอัปเดตตัวเองโดยอัตโนมัติ',
    f6Title: 'ภาษาของคุณ',
    f6: 'มีให้เลือก 26 ภาษา พร้อมธีมสว่างและมืด',
    shotDownload: 'เลือกวิดีโอจากเพลย์ลิสต์',
    shotQueue: 'คิวดาวน์โหลด',
    installTitle: 'การติดตั้ง',
    downloadDeb: "ดาวน์โหลดสำหรับ Ubuntu / Debian",
    appImageLink: "ใช้ Linux อื่นหรือไม่ ดาวน์โหลด AppImage",
    installHelp: "วิธีติดตั้ง",
    recommended: "แนะนำ",
    tabWindows: "Windows",
    tabDeb: "Ubuntu, Debian, Mint",
    tabAppImage: "Linux อื่น ๆ (AppImage)",
    winStep1: "ดาวน์โหลด VidSnare-Setup.exe ด้วยปุ่มด้านบน",
    winStep2: "เปิดไฟล์ หาก Windows แสดง “Windows ได้ปกป้องพีซีของคุณ” ให้คลิก “ข้อมูลเพิ่มเติม” แล้วคลิก “เรียกใช้ต่อไป” ข้อความนี้ปรากฏเพราะ VidSnare ยังไม่ได้ลงนามรหัส",
    winStep3: "ทำตามขั้นตอนของตัวติดตั้ง จากนั้นเปิด VidSnare จากเมนู Start",
    winUpdates: "ระบบจะติดตั้งการอัปเดตให้อัตโนมัติ",
    debStep1: "ดาวน์โหลดแพ็กเกจด้วยปุ่มด้านบน หรือในเทอร์มินัล:",
    debStep2: "ติดตั้งจากโฟลเดอร์ที่บันทึกไฟล์ไว้:",
    debStep3: "เปิด VidSnare จากเมนูแอปพลิเคชัน หรือเรียกใช้:",
    debUpdates: "เมื่อมีเวอร์ชันใหม่ VidSnare จะแจ้งให้ทราบ ติดตั้งด้วยวิธีเดียวกัน",
    debRemove: "ถอนการติดตั้ง:",
    appStep1: "ดาวน์โหลด AppImage จากลิงก์ด้านบน หรือในเทอร์มินัล:",
    appStep2: "อนุญาตให้เรียกใช้แล้วเปิด:",
    appStep2Alt: "ไม่ใช้เทอร์มินัล: คลิกขวาที่ไฟล์ → คุณสมบัติ → สิทธิ์ → อนุญาตให้เรียกใช้เป็นโปรแกรม แล้วดับเบิลคลิก",
    appUpdates: "AppImage อัปเดตตัวเองโดยอัตโนมัติ",
    troubleTitle: "หากเปิดไม่ได้",
    troubleFuse: "ข้อผิดพลาดเกี่ยวกับ “libfuse.so.2” หมายความว่าขาดไลบรารีที่ AppImage ต้องใช้ ติดตั้งให้ตรงกับระบบของคุณ:",
    troubleSandbox: "ข้อผิดพลาดเกี่ยวกับ “sandbox” บน Ubuntu 24.04 ขึ้นไป: ให้ใช้แพ็กเกจสำหรับ Ubuntu / Debian แทน ซึ่งจะตั้งค่าให้เอง",
    copy: "คัดลอก",
    copied: "คัดลอกแล้ว",
    usageTitle: "วิธีใช้งาน",
    use1: "บน YouTube ให้คัดลอกลิงก์ของวิดีโอ เพลย์ลิสต์ หรือช่อง",
    use2: "ใน VidSnare ให้วางลงในช่องด้านบน (Ctrl+V หรือคลิกขวา → วาง) จะมีตัวอย่างแสดงขึ้นมา",
    use3: "เลือกวิดีโอหรือเสียง คุณภาพ และโฟลเดอร์ แล้วคลิก “ดาวน์โหลด”",
    use4: "คลิก “คิว” ทางซ้ายเพื่อดูความคืบหน้า เมื่อเสร็จแล้วคลิก “เปิดไฟล์”",
    disclaimer: 'คุณมีหน้าที่ปฏิบัติตามข้อกำหนดในการให้บริการของ YouTube และกฎหมายลิขสิทธิ์ โปรดดาวน์โหลดเฉพาะเนื้อหาที่คุณมีสิทธิ์ดาวน์โหลด',
    license: 'ใช้ฟรีสำหรับการใช้งานส่วนตัวที่ไม่ใช่เชิงพาณิชย์',
    source: 'ซอร์สโค้ด',
    notAffiliated: 'ไม่มีส่วนเกี่ยวข้องกับ YouTube หรือ Google',
    language: 'ภาษา'
  },
  ar: {
    title: 'VidSnare – نزّل الفيديوهات والصوت من YouTube',
    tagline: 'نزّل الفيديوهات والموسيقى من YouTube ببساطة.',
    lead: 'الصق رابطًا واختر الجودة، ويتولى VidSnare الباقي. مجاني للاستخدام الشخصي على Windows وLinux.',
    downloadFor: 'تنزيل لنظام {os}',
    otherDownloads: 'تنزيلات أخرى',
    version: 'الإصدار {version}',
    comingSoon: 'الإصدار الأول قادم قريبًا.',
    onlyWinLinux: 'VidSnare متاح لنظامي Windows وLinux.',
    fileWindows: 'Windows 10 و11 – برنامج التثبيت',
    fileAppImage: 'Linux – AppImage لكل التوزيعات',
    fileDeb: 'Linux – حزمة Debian / Ubuntu',
    featuresTitle: 'ماذا يقدّم',
    f1Title: 'قوائم التشغيل والقنوات',
    f1: 'حمّل قائمة تشغيل أو قناة كاملة واختر الفيديوهات التي تريدها بالضبط.',
    f2Title: 'فيديو أو صوت',
    f2: 'فيديو حتى 4K، أو الصوت فقط بصيغة MP3 أو M4A أو Opus.',
    f3Title: 'الترجمة',
    f3: 'ترجمة باللغات التي تختارها، كملف منفصل أو داخل الفيديو.',
    f4Title: 'قائمة انتظار التنزيل',
    f4: 'عدة تنزيلات في وقت واحد، مع التقدم والسرعة والوقت المتبقي.',
    f5Title: 'محدّث دائمًا',
    f5: 'يحدّث VidSnare نفسه ومحرك التنزيل تلقائيًا.',
    f6Title: 'بلغتك',
    f6: 'متاح بـ 26 لغة، مع سمة فاتحة وأخرى داكنة.',
    shotDownload: 'اختيار فيديوهات من قائمة تشغيل',
    shotQueue: 'قائمة انتظار التنزيل',
    installTitle: 'التثبيت',
    downloadDeb: "تنزيل لنظامي Ubuntu / Debian",
    appImageLink: "توزيعة Linux أخرى؟ نزّل AppImage",
    installHelp: "مساعدة في التثبيت",
    recommended: "مُوصى به",
    tabWindows: "Windows",
    tabDeb: "Ubuntu وDebian وMint",
    tabAppImage: "Linux آخر (AppImage)",
    winStep1: "نزّل VidSnare-Setup.exe بالزر أعلاه.",
    winStep2: "افتح الملف. إذا ظهرت رسالة «قام Windows بحماية الكمبيوتر الشخصي»، فانقر «مزيد من المعلومات» ثم «التشغيل على أي حال». تظهر هذه الرسالة لأن VidSnare غير موقّع رقميًا بعد.",
    winStep3: "اتبع خطوات برنامج التثبيت. بعدها افتح VidSnare من قائمة «ابدأ».",
    winUpdates: "تُثبَّت التحديثات تلقائيًا.",
    debStep1: "نزّل الحزمة بالزر أعلاه، أو في الطرفية:",
    debStep2: "ثبّتها من المجلد الذي حُفظت فيه:",
    debStep3: "افتح VidSnare من قائمة التطبيقات، أو شغّل:",
    debUpdates: "عند صدور إصدار جديد سينبّهك VidSnare. ثبّته بالطريقة نفسها.",
    debRemove: "لإلغاء التثبيت:",
    appStep1: "نزّل AppImage من الرابط أعلاه، أو في الطرفية:",
    appStep2: "اسمح بتشغيله ثم افتحه:",
    appStep2Alt: "بدون طرفية: انقر بزر الفأرة الأيمن على الملف ← خصائص ← الأذونات ← السماح بالتشغيل كبرنامج، ثم انقر عليه نقرًا مزدوجًا.",
    appUpdates: "يحدّث AppImage نفسه تلقائيًا.",
    troubleTitle: "إذا لم يعمل",
    troubleFuse: "خطأ متعلق بـ «libfuse.so.2» يعني أن مكتبة يحتاجها AppImage غير مثبّتة. ثبّتها لنظامك:",
    troubleSandbox: "خطأ متعلق بـ «sandbox» في Ubuntu 24.04 أو أحدث: استخدم حزمة Ubuntu / Debian بدلًا منه، فهي تضبط ذلك نيابةً عنك.",
    copy: "نسخ",
    copied: "تم النسخ",
    usageTitle: "طريقة الاستخدام",
    use1: "انسخ من YouTube رابط فيديو أو قائمة تشغيل أو قناة.",
    use2: "الصقه في VidSnare في الحقل العلوي (Ctrl+V أو نقرة يمنى ← لصق). ستظهر معاينة.",
    use3: "اختر فيديو أو صوتًا، والجودة والمجلد، ثم انقر «تنزيل».",
    use4: "انقر «قائمة الانتظار» في الشريط الجانبي لمتابعة التقدم. عند الانتهاء انقر «فتح الملف».",
    disclaimer: 'أنت مسؤول عن الالتزام بشروط خدمة YouTube وقوانين حقوق النشر. لا تنزّل إلا المحتوى الذي يحق لك تنزيله.',
    license: 'مجاني للاستخدام الشخصي غير التجاري.',
    source: 'الشيفرة المصدرية',
    notAffiliated: 'غير تابع لـ YouTube أو Google.',
    language: 'اللغة'
  },
  fa: {
    title: 'VidSnare – بارگیری ویدیو و صدا از YouTube',
    tagline: 'ویدیو و موسیقی را از YouTube بارگیری کنید. به همین سادگی.',
    lead: 'پیوند را بچسبانید، کیفیت را انتخاب کنید و بقیه را به VidSnare بسپارید. برای استفادهٔ شخصی روی Windows و Linux رایگان است.',
    downloadFor: 'بارگیری برای {os}',
    otherDownloads: 'بارگیری‌های دیگر',
    version: 'نسخهٔ {version}',
    comingSoon: 'نخستین نسخه به‌زودی منتشر می‌شود.',
    onlyWinLinux: 'VidSnare برای Windows و Linux در دسترس است.',
    fileWindows: 'Windows 10 و 11 – برنامهٔ نصب',
    fileAppImage: 'Linux – AppImage برای همهٔ توزیع‌ها',
    fileDeb: 'Linux – بستهٔ Debian / Ubuntu',
    featuresTitle: 'چه کارهایی می‌کند',
    f1Title: 'فهرست‌های پخش و کانال‌ها',
    f1: 'کل یک فهرست پخش یا کانال را بارگذاری کنید و دقیقاً ویدیوهای دلخواه را انتخاب کنید.',
    f2Title: 'ویدیو یا صدا',
    f2: 'ویدیو تا کیفیت 4K، یا فقط صدا با قالب MP3، M4A یا Opus.',
    f3Title: 'زیرنویس',
    f3: 'زیرنویس به زبان‌های دلخواه، به‌صورت فایل جدا یا درون ویدیو.',
    f4Title: 'صف بارگیری',
    f4: 'چند بارگیری هم‌زمان، با نمایش پیشرفت، سرعت و زمان باقی‌مانده.',
    f5Title: 'همیشه به‌روز',
    f5: 'VidSnare و موتور بارگیری‌اش به‌طور خودکار به‌روز می‌شوند.',
    f6Title: 'به زبان شما',
    f6: 'در ۲۶ زبان، با پوستهٔ روشن و تیره.',
    shotDownload: 'انتخاب ویدیو از فهرست پخش',
    shotQueue: 'صف بارگیری',
    installTitle: 'نصب',
    downloadDeb: "بارگیری برای Ubuntu / Debian",
    appImageLink: "لینوکس دیگری دارید؟ AppImage را بگیرید",
    installHelp: "راهنمای نصب",
    recommended: "پیشنهادی",
    tabWindows: "Windows",
    tabDeb: "Ubuntu، Debian، Mint",
    tabAppImage: "لینوکس دیگر (AppImage)",
    winStep1: "VidSnare-Setup.exe را با دکمهٔ بالا بارگیری کنید.",
    winStep2: "آن را باز کنید. اگر Windows پیام «Windows از رایانهٔ شما محافظت کرد» را نشان داد، روی «اطلاعات بیشتر» و سپس «به هر حال اجرا شود» کلیک کنید. این پیام به این دلیل است که VidSnare هنوز امضای دیجیتال ندارد.",
    winStep3: "مراحل نصب را دنبال کنید. سپس VidSnare را از منوی Start باز کنید.",
    winUpdates: "به‌روزرسانی‌ها خودکار نصب می‌شوند.",
    debStep1: "بسته را با دکمهٔ بالا یا در ترمینال بارگیری کنید:",
    debStep2: "آن را از پوشه‌ای که ذخیره شده نصب کنید:",
    debStep3: "VidSnare را از منوی برنامه‌ها باز کنید یا این را اجرا کنید:",
    debUpdates: "وقتی نسخهٔ جدیدی بیاید، VidSnare به شما خبر می‌دهد. آن را به همین روش نصب کنید.",
    debRemove: "برای حذف:",
    appStep1: "AppImage را با پیوند بالا یا در ترمینال بارگیری کنید:",
    appStep2: "اجازهٔ اجرا بدهید و اجرایش کنید:",
    appStep2Alt: "بدون ترمینال: روی فایل راست‌کلیک کنید ← ویژگی‌ها ← مجوزها ← اجازهٔ اجرا به‌عنوان برنامه، سپس دوبار کلیک کنید.",
    appUpdates: "AppImage خودش به‌طور خودکار به‌روز می‌شود.",
    troubleTitle: "اگر اجرا نشد",
    troubleFuse: "خطای مربوط به «libfuse.so.2» یعنی کتابخانه‌ای که AppImage لازم دارد نصب نیست. آن را برای سیستم خود نصب کنید:",
    troubleSandbox: "خطای مربوط به «sandbox» در Ubuntu 24.04 یا جدیدتر: به‌جای آن از بستهٔ Ubuntu / Debian استفاده کنید؛ این بسته تنظیمات لازم را انجام می‌دهد.",
    copy: "رونوشت",
    copied: "رونوشت شد",
    usageTitle: "روش استفاده",
    use1: "در YouTube پیوند یک ویدیو، فهرست پخش یا کانال را رونوشت کنید.",
    use2: "در VidSnare آن را در کادر بالا بچسبانید (Ctrl+V یا راست‌کلیک ← چسباندن). پیش‌نمایش نمایش داده می‌شود.",
    use3: "ویدیو یا صدا، کیفیت و پوشه را انتخاب کنید و روی «بارگیری» کلیک کنید.",
    use4: "برای دیدن پیشرفت روی «صف» در نوار کناری کلیک کنید. پس از پایان، روی «باز کردن فایل» کلیک کنید.",
    disclaimer: 'رعایت شرایط خدمات YouTube و قانون حق نشر بر عهدهٔ شماست. فقط محتوایی را بارگیری کنید که حق بارگیری آن را دارید.',
    license: 'برای استفادهٔ شخصی و غیرتجاری رایگان است.',
    source: 'کد منبع',
    notAffiliated: 'وابسته به YouTube یا Google نیست.',
    language: 'زبان'
  },
  he: {
    title: 'VidSnare – הורדת סרטונים ושמע מ-YouTube',
    tagline: 'הורידו סרטונים ומוזיקה מ-YouTube. פשוט.',
    lead: 'הדביקו קישור, בחרו איכות, ו-VidSnare יעשה את השאר. חינם לשימוש אישי ב-Windows וב-Linux.',
    downloadFor: 'הורדה ל-{os}',
    otherDownloads: 'הורדות נוספות',
    version: 'גרסה {version}',
    comingSoon: 'הגרסה הראשונה תצא בקרוב.',
    onlyWinLinux: 'VidSnare זמין ל-Windows ול-Linux.',
    fileWindows: 'Windows 10 ו-11 – תוכנת התקנה',
    fileAppImage: 'Linux – AppImage לכל ההפצות',
    fileDeb: 'Linux – חבילת Debian / Ubuntu',
    featuresTitle: 'מה הוא עושה',
    f1Title: 'פלייליסטים וערוצים',
    f1: 'טענו פלייליסט או ערוץ שלם ובחרו בדיוק את הסרטונים שתרצו.',
    f2Title: 'וידאו או שמע',
    f2: 'וידאו עד 4K, או רק השמע בפורמט MP3, ‏M4A או Opus.',
    f3Title: 'כתוביות',
    f3: 'כתוביות בשפות שתבחרו, כקובץ נפרד או בתוך הסרטון.',
    f4Title: 'תור הורדות',
    f4: 'כמה הורדות במקביל, עם התקדמות, מהירות וזמן שנותר.',
    f5Title: 'תמיד מעודכן',
    f5: 'VidSnare ומנוע ההורדה שלו מתעדכנים אוטומטית.',
    f6Title: 'בשפה שלכם',
    f6: 'זמין ב-26 שפות, עם ערכת נושא בהירה וכהה.',
    shotDownload: 'בחירת סרטונים מפלייליסט',
    shotQueue: 'תור ההורדות',
    installTitle: 'התקנה',
    downloadDeb: "הורדה ל-Ubuntu / Debian",
    appImageLink: "לינוקס אחר? הורידו את ה-AppImage",
    installHelp: "עזרה בהתקנה",
    recommended: "מומלץ",
    tabWindows: "Windows",
    tabDeb: "Ubuntu‏, Debian‏, Mint",
    tabAppImage: "לינוקס אחר (AppImage)",
    winStep1: "הורידו את VidSnare-Setup.exe בכפתור שלמעלה.",
    winStep2: "פתחו את הקובץ. אם Windows מציג „Windows הגן על המחשב שלך”, לחצו על „מידע נוסף” ואז על „הפעל בכל זאת”. ההודעה מופיעה כי VidSnare עדיין לא חתום דיגיטלית.",
    winStep3: "עברו על שלבי ההתקנה. אחר כך פתחו את VidSnare מתפריט ההתחלה.",
    winUpdates: "העדכונים מותקנים אוטומטית.",
    debStep1: "הורידו את החבילה בכפתור שלמעלה, או במסוף:",
    debStep2: "התקינו אותה מהתיקייה שבה נשמרה:",
    debStep3: "פתחו את VidSnare מתפריט היישומים, או הריצו:",
    debUpdates: "כשתצא גרסה חדשה, VidSnare יודיע לכם. התקינו אותה באותה דרך.",
    debRemove: "להסרה:",
    appStep1: "הורידו את ה-AppImage בקישור שלמעלה, או במסוף:",
    appStep2: "אפשרו הרצה והפעילו אותו:",
    appStep2Alt: "בלי מסוף: לחיצה ימנית על הקובץ ← מאפיינים ← הרשאות ← לאפשר הרצה כתוכנה, ואז לחיצה כפולה.",
    appUpdates: "ה-AppImage מתעדכן אוטומטית.",
    troubleTitle: "אם הוא לא נפתח",
    troubleFuse: "שגיאה לגבי „libfuse.so.2” פירושה שחסרה ספרייה ש-AppImage צריך. התקינו אותה למערכת שלכם:",
    troubleSandbox: "שגיאה לגבי „sandbox” ב-Ubuntu 24.04 ומעלה: השתמשו במקום זאת בחבילה ל-Ubuntu / Debian, שמגדירה את זה בשבילכם.",
    copy: "העתקה",
    copied: "הועתק",
    usageTitle: "איך משתמשים",
    use1: "ב-YouTube, העתיקו קישור לסרטון, לפלייליסט או לערוץ.",
    use2: "ב-VidSnare, הדביקו אותו בתיבה שלמעלה (Ctrl+V או לחיצה ימנית ← הדבקה). תופיע תצוגה מקדימה.",
    use3: "בחרו וידאו או שמע, איכות ותיקייה, ואז לחצו על „הורדה”.",
    use4: "לחצו על „תור” בסרגל הצד כדי לעקוב אחרי ההתקדמות. בסיום, לחצו על „פתיחת הקובץ”.",
    disclaimer: 'האחריות לעמוד בתנאים וההגבלות של YouTube ובדיני זכויות היוצרים היא שלכם. הורידו רק תוכן שיש לכם זכות להוריד.',
    license: 'חינם לשימוש אישי שאינו מסחרי.',
    source: 'קוד מקור',
    notAffiliated: 'לא קשור ל-YouTube או ל-Google.',
    language: 'שפה'
  }
}

export const LANGUAGE_NAMES = {
  en: 'English',
  pl: 'Polski',
  de: 'Deutsch',
  es: 'Español',
  'pt-BR': 'Português (Brasil)',
  ru: 'Русский',
  ja: '日本語',
  fr: 'Français',
  tr: 'Türkçe',
  it: 'Italiano',
  uk: 'Українська',
  id: 'Bahasa Indonesia',
  vi: 'Tiếng Việt',
  ko: '한국어',
  'zh-TW': '繁體中文',
  hi: 'हिन्दी',
  nl: 'Nederlands',
  cs: 'Čeština',
  ro: 'Română',
  hu: 'Magyar',
  sv: 'Svenska',
  el: 'Ελληνικά',
  th: 'ไทย',
  ar: 'العربية',
  fa: 'فارسی',
  he: 'עברית'
}

/** Written right to left; the page mirrors for these. */
export const RTL = ['ar', 'fa', 'he']
