// Website text in every language. Keys and {placeholders} must match English
// (checked by tests/website.test.ts).
export const STRINGS = {
  en: {
    title: 'VidSnare – download videos and audio from YouTube',
    tagline: 'Download videos and music from YouTube. Simply.',
    lead: 'Paste a link, choose the quality, and VidSnare does the rest. Free for personal use on Windows and Linux.',
    downloadFor: 'Download for {os}',
    otherDownloads: 'Other downloads',
    version: 'Version {version}',
    comingSoon: 'The first release is coming soon.',
    onlyWinLinux: 'VidSnare is available for Windows and Linux.',
    fileWindows: 'Windows 10 and 11 – installer',
    fileAppImage: 'Linux – AppImage, any distribution',
    fileDeb: 'Linux – Debian / Ubuntu package',
    featuresTitle: 'What it does',
    f1Title: 'Playlists and channels',
    f1: 'Load a whole playlist or channel and pick exactly which videos you want.',
    f2Title: 'Video or audio',
    f2: 'Video up to 4K, or just the sound as MP3, M4A or Opus.',
    f3Title: 'Subtitles',
    f3: 'Get subtitles in the languages you choose, saved or built into the video.',
    f4Title: 'Download queue',
    f4: 'Several downloads at once, with progress, speed and time left.',
    f5Title: 'Always up to date',
    f5: 'VidSnare and its download engine update themselves automatically.',
    f6Title: 'Your language',
    f6: 'Available in 26 languages, with light and dark themes.',
    shotDownload: 'Choosing videos from a playlist',
    shotQueue: 'The download queue',
    installTitle: 'Installing',
    installWindows: 'Windows may say “unknown publisher” the first time, because VidSnare is not code-signed yet. Click “More info”, then “Run anyway”.',
    installLinux: 'For the AppImage, allow it to run as a program (right-click → Properties → Permissions), then open it.',
    disclaimer:
      "You are responsible for complying with YouTube's Terms of Service and copyright law. Only download content you have the right to download.",
    license: 'Free for personal, non-commercial use.',
    source: 'Source code',
    notAffiliated: 'Not affiliated with YouTube or Google.',
    language: 'Language'
  },
  pl: {
    title: 'VidSnare – pobieraj filmy i dźwięk z YouTube',
    tagline: 'Pobieraj filmy i muzykę z YouTube. Po prostu.',
    lead: 'Wklej link, wybierz jakość, a VidSnare zrobi resztę. Bezpłatny do użytku osobistego na Windows i Linux.',
    downloadFor: 'Pobierz na {os}',
    otherDownloads: 'Inne wersje',
    version: 'Wersja {version}',
    comingSoon: 'Pierwsze wydanie już wkrótce.',
    onlyWinLinux: 'VidSnare jest dostępny na Windows i Linux.',
    fileWindows: 'Windows 10 i 11 – instalator',
    fileAppImage: 'Linux – AppImage, dowolna dystrybucja',
    fileDeb: 'Linux – pakiet Debian / Ubuntu',
    featuresTitle: 'Co potrafi',
    f1Title: 'Playlisty i kanały',
    f1: 'Wczytaj całą playlistę lub kanał i wybierz dokładnie te filmy, których chcesz.',
    f2Title: 'Wideo lub dźwięk',
    f2: 'Wideo do 4K albo sam dźwięk jako MP3, M4A lub Opus.',
    f3Title: 'Napisy',
    f3: 'Pobieraj napisy w wybranych językach – jako pliki lub wbudowane w wideo.',
    f4Title: 'Kolejka pobierania',
    f4: 'Kilka pobrań naraz, z postępem, prędkością i pozostałym czasem.',
    f5Title: 'Zawsze aktualny',
    f5: 'VidSnare i jego silnik pobierania aktualizują się automatycznie.',
    f6Title: 'Twój język',
    f6: 'Dostępny w 26 językach, z jasnym i ciemnym motywem.',
    shotDownload: 'Wybieranie filmów z playlisty',
    shotQueue: 'Kolejka pobierania',
    installTitle: 'Instalacja',
    installWindows: 'Windows może za pierwszym razem pokazać „nieznany wydawca”, bo VidSnare nie jest jeszcze podpisany cyfrowo. Kliknij „Więcej informacji”, a potem „Uruchom mimo to”.',
    installLinux: 'Dla AppImage zezwól na uruchamianie jako program (prawy przycisk → Właściwości → Uprawnienia), a potem go otwórz.',
    disclaimer:
      'Odpowiadasz za przestrzeganie Warunków korzystania z YouTube i prawa autorskiego. Pobieraj tylko treści, do których masz prawo.',
    license: 'Bezpłatny do użytku osobistego, niekomercyjnego.',
    source: 'Kod źródłowy',
    notAffiliated: 'Niepowiązany z YouTube ani Google.',
    language: 'Język'
  },
  de: {
    title: 'VidSnare – Videos und Audio von YouTube herunterladen',
    tagline: 'Videos und Musik von YouTube herunterladen. Ganz einfach.',
    lead: 'Link einfügen, Qualität wählen – VidSnare erledigt den Rest. Kostenlos für den privaten Gebrauch unter Windows und Linux.',
    downloadFor: 'Für {os} herunterladen',
    otherDownloads: 'Weitere Downloads',
    version: 'Version {version}',
    comingSoon: 'Die erste Version erscheint bald.',
    onlyWinLinux: 'VidSnare gibt es für Windows und Linux.',
    fileWindows: 'Windows 10 und 11 – Installer',
    fileAppImage: 'Linux – AppImage, jede Distribution',
    fileDeb: 'Linux – Debian-/Ubuntu-Paket',
    featuresTitle: 'Was es kann',
    f1Title: 'Playlists und Kanäle',
    f1: 'Lade eine ganze Playlist oder einen Kanal und wähle genau die Videos aus, die du willst.',
    f2Title: 'Video oder Audio',
    f2: 'Video bis 4K oder nur der Ton als MP3, M4A oder Opus.',
    f3Title: 'Untertitel',
    f3: 'Untertitel in den gewünschten Sprachen – als Datei oder im Video.',
    f4Title: 'Download-Warteschlange',
    f4: 'Mehrere Downloads gleichzeitig, mit Fortschritt, Geschwindigkeit und Restzeit.',
    f5Title: 'Immer aktuell',
    f5: 'VidSnare und seine Download-Engine aktualisieren sich automatisch.',
    f6Title: 'Deine Sprache',
    f6: 'In 26 Sprachen verfügbar, mit hellem und dunklem Design.',
    shotDownload: 'Videos aus einer Playlist auswählen',
    shotQueue: 'Die Download-Warteschlange',
    installTitle: 'Installation',
    installWindows: 'Windows meldet beim ersten Mal eventuell „Unbekannter Herausgeber“, weil VidSnare noch nicht signiert ist. Klicke auf „Weitere Informationen“ und dann auf „Trotzdem ausführen“.',
    installLinux: 'Erlaube beim AppImage die Ausführung als Programm (Rechtsklick → Eigenschaften → Berechtigungen) und öffne es dann.',
    disclaimer:
      'Du bist dafür verantwortlich, die Nutzungsbedingungen von YouTube und das Urheberrecht einzuhalten. Lade nur Inhalte herunter, zu deren Download du berechtigt bist.',
    license: 'Kostenlos für private, nicht-kommerzielle Nutzung.',
    source: 'Quellcode',
    notAffiliated: 'Nicht mit YouTube oder Google verbunden.',
    language: 'Sprache'
  },
  es: {
    title: 'VidSnare – descarga vídeos y audio de YouTube',
    tagline: 'Descarga vídeos y música de YouTube. Así de fácil.',
    lead: 'Pega un enlace, elige la calidad y VidSnare hace el resto. Gratis para uso personal en Windows y Linux.',
    downloadFor: 'Descargar para {os}',
    otherDownloads: 'Otras descargas',
    version: 'Versión {version}',
    comingSoon: 'La primera versión llegará pronto.',
    onlyWinLinux: 'VidSnare está disponible para Windows y Linux.',
    fileWindows: 'Windows 10 y 11 – instalador',
    fileAppImage: 'Linux – AppImage, cualquier distribución',
    fileDeb: 'Linux – paquete Debian / Ubuntu',
    featuresTitle: 'Qué hace',
    f1Title: 'Listas y canales',
    f1: 'Carga una lista de reproducción o un canal entero y elige exactamente los vídeos que quieres.',
    f2Title: 'Vídeo o audio',
    f2: 'Vídeo hasta 4K, o solo el sonido en MP3, M4A u Opus.',
    f3Title: 'Subtítulos',
    f3: 'Subtítulos en los idiomas que elijas, como archivo o dentro del vídeo.',
    f4Title: 'Cola de descargas',
    f4: 'Varias descargas a la vez, con progreso, velocidad y tiempo restante.',
    f5Title: 'Siempre actualizado',
    f5: 'VidSnare y su motor de descarga se actualizan solos.',
    f6Title: 'Tu idioma',
    f6: 'Disponible en 26 idiomas, con tema claro y oscuro.',
    shotDownload: 'Eligiendo vídeos de una lista',
    shotQueue: 'La cola de descargas',
    installTitle: 'Instalación',
    installWindows: 'Windows puede mostrar «editor desconocido» la primera vez, porque VidSnare aún no está firmado. Haz clic en «Más información» y luego en «Ejecutar de todas formas».',
    installLinux: 'Para el AppImage, permite ejecutarlo como programa (clic derecho → Propiedades → Permisos) y ábrelo.',
    disclaimer:
      'Eres responsable de cumplir las Condiciones de servicio de YouTube y las leyes de derechos de autor. Descarga solo contenido que tengas derecho a descargar.',
    license: 'Gratis para uso personal y no comercial.',
    source: 'Código fuente',
    notAffiliated: 'Sin relación con YouTube ni Google.',
    language: 'Idioma'
  },
  'pt-BR': {
    title: 'VidSnare – baixe vídeos e áudio do YouTube',
    tagline: 'Baixe vídeos e músicas do YouTube. Simples assim.',
    lead: 'Cole um link, escolha a qualidade e o VidSnare faz o resto. Grátis para uso pessoal no Windows e no Linux.',
    downloadFor: 'Baixar para {os}',
    otherDownloads: 'Outros downloads',
    version: 'Versão {version}',
    comingSoon: 'A primeira versão chega em breve.',
    onlyWinLinux: 'O VidSnare está disponível para Windows e Linux.',
    fileWindows: 'Windows 10 e 11 – instalador',
    fileAppImage: 'Linux – AppImage, qualquer distribuição',
    fileDeb: 'Linux – pacote Debian / Ubuntu',
    featuresTitle: 'O que ele faz',
    f1Title: 'Playlists e canais',
    f1: 'Carregue uma playlist ou um canal inteiro e escolha exatamente os vídeos que quer.',
    f2Title: 'Vídeo ou áudio',
    f2: 'Vídeo em até 4K, ou só o som em MP3, M4A ou Opus.',
    f3Title: 'Legendas',
    f3: 'Legendas nos idiomas que você escolher, em arquivo ou dentro do vídeo.',
    f4Title: 'Fila de downloads',
    f4: 'Vários downloads ao mesmo tempo, com progresso, velocidade e tempo restante.',
    f5Title: 'Sempre atualizado',
    f5: 'O VidSnare e seu mecanismo de download se atualizam sozinhos.',
    f6Title: 'Seu idioma',
    f6: 'Disponível em 26 idiomas, com tema claro e escuro.',
    shotDownload: 'Escolhendo vídeos de uma playlist',
    shotQueue: 'A fila de downloads',
    installTitle: 'Instalação',
    installWindows: 'Na primeira vez, o Windows pode mostrar “editor desconhecido”, porque o VidSnare ainda não é assinado. Clique em “Mais informações” e depois em “Executar assim mesmo”.',
    installLinux: 'Para o AppImage, permita executá-lo como programa (botão direito → Propriedades → Permissões) e abra-o.',
    disclaimer:
      'Você é responsável por cumprir os Termos de Serviço do YouTube e as leis de direitos autorais. Baixe apenas conteúdo que você tem o direito de baixar.',
    license: 'Grátis para uso pessoal e não comercial.',
    source: 'Código-fonte',
    notAffiliated: 'Sem vínculo com o YouTube ou o Google.',
    language: 'Idioma'
  },
  ru: {
    title: 'VidSnare – скачивайте видео и аудио с YouTube',
    tagline: 'Скачивайте видео и музыку с YouTube. Просто.',
    lead: 'Вставьте ссылку, выберите качество – остальное сделает VidSnare. Бесплатно для личного использования на Windows и Linux.',
    downloadFor: 'Скачать для {os}',
    otherDownloads: 'Другие версии',
    version: 'Версия {version}',
    comingSoon: 'Первый выпуск скоро появится.',
    onlyWinLinux: 'VidSnare доступен для Windows и Linux.',
    fileWindows: 'Windows 10 и 11 – установщик',
    fileAppImage: 'Linux – AppImage, любой дистрибутив',
    fileDeb: 'Linux – пакет Debian / Ubuntu',
    featuresTitle: 'Возможности',
    f1Title: 'Плейлисты и каналы',
    f1: 'Загрузите весь плейлист или канал и выберите именно те видео, которые нужны.',
    f2Title: 'Видео или аудио',
    f2: 'Видео до 4K или только звук в MP3, M4A или Opus.',
    f3Title: 'Субтитры',
    f3: 'Субтитры на выбранных языках – отдельным файлом или внутри видео.',
    f4Title: 'Очередь загрузок',
    f4: 'Несколько загрузок одновременно, с прогрессом, скоростью и оставшимся временем.',
    f5Title: 'Всегда актуален',
    f5: 'VidSnare и его движок загрузки обновляются автоматически.',
    f6Title: 'Ваш язык',
    f6: 'Доступен на 26 языках, со светлой и тёмной темой.',
    shotDownload: 'Выбор видео из плейлиста',
    shotQueue: 'Очередь загрузок',
    installTitle: 'Установка',
    installWindows: 'При первом запуске Windows может показать «Неизвестный издатель», так как у VidSnare пока нет цифровой подписи. Нажмите «Подробнее», затем «Выполнить в любом случае».',
    installLinux: 'Для AppImage разрешите запуск как программы (правый клик → Свойства → Права), затем откройте его.',
    disclaimer:
      'Вы несёте ответственность за соблюдение Условий использования YouTube и авторского права. Скачивайте только то, на что у вас есть права.',
    license: 'Бесплатно для личного некоммерческого использования.',
    source: 'Исходный код',
    notAffiliated: 'Не связан с YouTube или Google.',
    language: 'Язык'
  },
  ja: {
    title: 'VidSnare – YouTube の動画と音声をダウンロード',
    tagline: 'YouTube の動画と音楽を、かんたんにダウンロード。',
    lead: 'リンクを貼り付けて画質を選ぶだけ。あとは VidSnare におまかせ。Windows と Linux で、個人利用は無料です。',
    downloadFor: '{os} 版をダウンロード',
    otherDownloads: 'その他のダウンロード',
    version: 'バージョン {version}',
    comingSoon: '最初のリリースはまもなく公開予定です。',
    onlyWinLinux: 'VidSnare は Windows と Linux に対応しています。',
    fileWindows: 'Windows 10 / 11 – インストーラー',
    fileAppImage: 'Linux – AppImage（すべてのディストリビューション）',
    fileDeb: 'Linux – Debian / Ubuntu パッケージ',
    featuresTitle: 'できること',
    f1Title: '再生リストとチャンネル',
    f1: '再生リストやチャンネルをまるごと読み込み、欲しい動画だけを選べます。',
    f2Title: '動画または音声',
    f2: '最大 4K の動画、または音声のみを MP3・M4A・Opus で保存。',
    f3Title: '字幕',
    f3: '選んだ言語の字幕を、ファイルとして、または動画に埋め込んで保存。',
    f4Title: 'ダウンロードキュー',
    f4: '複数を同時にダウンロード。進行状況・速度・残り時間を表示します。',
    f5Title: 'いつも最新',
    f5: 'VidSnare とダウンロードエンジンは自動で更新されます。',
    f6Title: 'あなたの言語で',
    f6: '26 の言語に対応。ライトテーマとダークテーマを用意。',
    shotDownload: '再生リストから動画を選ぶ',
    shotQueue: 'ダウンロードキュー',
    installTitle: 'インストール',
    installWindows: 'VidSnare はまだコード署名されていないため、初回は「不明な発行元」と表示されることがあります。「詳細情報」→「実行」をクリックしてください。',
    installLinux: 'AppImage は、プログラムとしての実行を許可してから（右クリック → プロパティ → アクセス権）開いてください。',
    disclaimer:
      'YouTube の利用規約と著作権法を守る責任はユーザーにあります。ダウンロードする権利のあるコンテンツのみをダウンロードしてください。',
    license: '個人的・非商用の利用は無料です。',
    source: 'ソースコード',
    notAffiliated: 'YouTube および Google とは関係ありません。',
    language: '言語'
  },
  fr: {
    title: 'VidSnare – téléchargez vidéos et audio depuis YouTube',
    tagline: 'Téléchargez vidéos et musique depuis YouTube. Tout simplement.',
    lead: 'Collez un lien, choisissez la qualité, VidSnare s’occupe du reste. Gratuit pour un usage personnel sous Windows et Linux.',
    downloadFor: 'Télécharger pour {os}',
    otherDownloads: 'Autres téléchargements',
    version: 'Version {version}',
    comingSoon: 'La première version arrive bientôt.',
    onlyWinLinux: 'VidSnare est disponible pour Windows et Linux.',
    fileWindows: 'Windows 10 et 11 – programme d’installation',
    fileAppImage: 'Linux – AppImage, toutes distributions',
    fileDeb: 'Linux – paquet Debian / Ubuntu',
    featuresTitle: 'Ce qu’il fait',
    f1Title: 'Playlists et chaînes',
    f1: 'Chargez une playlist ou une chaîne entière et choisissez exactement les vidéos voulues.',
    f2Title: 'Vidéo ou audio',
    f2: 'Vidéo jusqu’en 4K, ou seulement le son en MP3, M4A ou Opus.',
    f3Title: 'Sous-titres',
    f3: 'Sous-titres dans les langues de votre choix, en fichier ou intégrés à la vidéo.',
    f4Title: 'File de téléchargement',
    f4: 'Plusieurs téléchargements à la fois, avec progression, vitesse et temps restant.',
    f5Title: 'Toujours à jour',
    f5: 'VidSnare et son moteur de téléchargement se mettent à jour automatiquement.',
    f6Title: 'Votre langue',
    f6: 'Disponible en 26 langues, avec thèmes clair et sombre.',
    shotDownload: 'Choisir des vidéos dans une playlist',
    shotQueue: 'La file de téléchargement',
    installTitle: 'Installation',
    installWindows: 'Windows peut afficher « Éditeur inconnu » la première fois, car VidSnare n’est pas encore signé. Cliquez sur « Informations complémentaires », puis « Exécuter quand même ».',
    installLinux: 'Pour l’AppImage, autorisez son exécution comme programme (clic droit → Propriétés → Permissions), puis ouvrez-la.',
    disclaimer:
      'Vous êtes responsable du respect des Conditions d’utilisation de YouTube et du droit d’auteur. Ne téléchargez que des contenus que vous avez le droit de télécharger.',
    license: 'Gratuit pour un usage personnel et non commercial.',
    source: 'Code source',
    notAffiliated: 'Non affilié à YouTube ni à Google.',
    language: 'Langue'
  },
  tr: {
    title: 'VidSnare – YouTube’dan video ve ses indirin',
    tagline: 'YouTube’dan video ve müzik indirin. Bu kadar basit.',
    lead: 'Bir bağlantı yapıştırın, kaliteyi seçin, gerisini VidSnare halletsin. Windows ve Linux’ta kişisel kullanım için ücretsiz.',
    downloadFor: '{os} için indir',
    otherDownloads: 'Diğer indirmeler',
    version: 'Sürüm {version}',
    comingSoon: 'İlk sürüm çok yakında.',
    onlyWinLinux: 'VidSnare, Windows ve Linux için kullanılabilir.',
    fileWindows: 'Windows 10 ve 11 – kurulum dosyası',
    fileAppImage: 'Linux – AppImage, tüm dağıtımlar',
    fileDeb: 'Linux – Debian / Ubuntu paketi',
    featuresTitle: 'Neler yapar',
    f1Title: 'Oynatma listeleri ve kanallar',
    f1: 'Bir oynatma listesini veya kanalı bütünüyle yükleyin ve istediğiniz videoları seçin.',
    f2Title: 'Video veya ses',
    f2: '4K’ya kadar video ya da yalnızca ses: MP3, M4A veya Opus.',
    f3Title: 'Altyazılar',
    f3: 'Seçtiğiniz dillerde altyazılar; ayrı dosya olarak ya da videoya gömülü.',
    f4Title: 'İndirme sırası',
    f4: 'Aynı anda birden çok indirme; ilerleme, hız ve kalan süreyle.',
    f5Title: 'Her zaman güncel',
    f5: 'VidSnare ve indirme motoru kendilerini otomatik olarak günceller.',
    f6Title: 'Kendi dilinizde',
    f6: '26 dilde, açık ve koyu temayla.',
    shotDownload: 'Bir oynatma listesinden video seçme',
    shotQueue: 'İndirme sırası',
    installTitle: 'Kurulum',
    installWindows: 'VidSnare henüz dijital olarak imzalanmadığı için Windows ilk seferde “bilinmeyen yayımcı” uyarısı gösterebilir. “Ek bilgi”ye, sonra “Yine de çalıştır”a tıklayın.',
    installLinux: 'AppImage için program olarak çalıştırmaya izin verin (sağ tık → Özellikler → İzinler), sonra açın.',
    disclaimer: 'YouTube Hizmet Şartları’na ve telif hakkı yasalarına uymak sizin sorumluluğunuzdadır. Yalnızca indirme hakkına sahip olduğunuz içerikleri indirin.',
    license: 'Kişisel ve ticari olmayan kullanım için ücretsiz.',
    source: 'Kaynak kodu',
    notAffiliated: 'YouTube veya Google ile bağlantılı değildir.',
    language: 'Dil'
  },
  it: {
    title: 'VidSnare – scarica video e audio da YouTube',
    tagline: 'Scarica video e musica da YouTube. Semplicemente.',
    lead: 'Incolla un link, scegli la qualità e VidSnare fa il resto. Gratis per uso personale su Windows e Linux.',
    downloadFor: 'Scarica per {os}',
    otherDownloads: 'Altri download',
    version: 'Versione {version}',
    comingSoon: 'La prima versione arriverà presto.',
    onlyWinLinux: 'VidSnare è disponibile per Windows e Linux.',
    fileWindows: 'Windows 10 e 11 – programma di installazione',
    fileAppImage: 'Linux – AppImage, qualsiasi distribuzione',
    fileDeb: 'Linux – pacchetto Debian / Ubuntu',
    featuresTitle: 'Cosa fa',
    f1Title: 'Playlist e canali',
    f1: 'Carica un’intera playlist o un canale e scegli esattamente i video che vuoi.',
    f2Title: 'Video o audio',
    f2: 'Video fino al 4K, oppure solo l’audio in MP3, M4A o Opus.',
    f3Title: 'Sottotitoli',
    f3: 'Sottotitoli nelle lingue che preferisci, come file o dentro il video.',
    f4Title: 'Coda di download',
    f4: 'Più download insieme, con avanzamento, velocità e tempo rimanente.',
    f5Title: 'Sempre aggiornato',
    f5: 'VidSnare e il suo motore di download si aggiornano da soli.',
    f6Title: 'La tua lingua',
    f6: 'Disponibile in 26 lingue, con tema chiaro e scuro.',
    shotDownload: 'Scegliere i video di una playlist',
    shotQueue: 'La coda di download',
    installTitle: 'Installazione',
    installWindows: 'La prima volta Windows potrebbe indicare “autore sconosciuto”, perché VidSnare non è ancora firmato. Fai clic su “Ulteriori informazioni” e poi su “Esegui comunque”.',
    installLinux: 'Per l’AppImage, consenti l’esecuzione come programma (clic destro → Proprietà → Permessi), poi aprilo.',
    disclaimer: 'Sei responsabile del rispetto dei Termini di servizio di YouTube e delle leggi sul diritto d’autore. Scarica solo contenuti che hai il diritto di scaricare.',
    license: 'Gratis per uso personale e non commerciale.',
    source: 'Codice sorgente',
    notAffiliated: 'Non affiliato a YouTube né a Google.',
    language: 'Lingua'
  },
  uk: {
    title: 'VidSnare – завантажуйте відео й аудіо з YouTube',
    tagline: 'Завантажуйте відео й музику з YouTube. Просто.',
    lead: 'Вставте посилання, виберіть якість – решту зробить VidSnare. Безкоштовно для особистого використання на Windows і Linux.',
    downloadFor: 'Завантажити для {os}',
    otherDownloads: 'Інші версії',
    version: 'Версія {version}',
    comingSoon: 'Перший випуск зовсім скоро.',
    onlyWinLinux: 'VidSnare доступний для Windows і Linux.',
    fileWindows: 'Windows 10 і 11 – інсталятор',
    fileAppImage: 'Linux – AppImage, будь-який дистрибутив',
    fileDeb: 'Linux – пакет Debian / Ubuntu',
    featuresTitle: 'Можливості',
    f1Title: 'Плейлисти й канали',
    f1: 'Відкрийте весь плейлист або канал і виберіть саме ті відео, які потрібні.',
    f2Title: 'Відео або аудіо',
    f2: 'Відео до 4K або лише звук у MP3, M4A чи Opus.',
    f3Title: 'Субтитри',
    f3: 'Субтитри вибраними мовами – окремим файлом або всередині відео.',
    f4Title: 'Черга завантажень',
    f4: 'Кілька завантажень одночасно, з прогресом, швидкістю та часом, що залишився.',
    f5Title: 'Завжди актуальний',
    f5: 'VidSnare і його рушій завантаження оновлюються автоматично.',
    f6Title: 'Ваша мова',
    f6: 'Доступний 26 мовами, зі світлою й темною темою.',
    shotDownload: 'Вибір відео з плейлиста',
    shotQueue: 'Черга завантажень',
    installTitle: 'Встановлення',
    installWindows: 'Під час першого запуску Windows може показати «Невідомий видавець», бо VidSnare ще не має цифрового підпису. Натисніть «Докладніше», а потім «Усе одно запустити».',
    installLinux: 'Для AppImage дозвольте запуск як програми (правий клік → Властивості → Права), потім відкрийте його.',
    disclaimer: 'Ви відповідаєте за дотримання Умов використання YouTube та авторського права. Завантажуйте лише те, на що маєте право.',
    license: 'Безкоштовно для особистого некомерційного використання.',
    source: 'Вихідний код',
    notAffiliated: 'Не пов’язаний з YouTube чи Google.',
    language: 'Мова'
  },
  id: {
    title: 'VidSnare – unduh video dan audio dari YouTube',
    tagline: 'Unduh video dan musik dari YouTube. Semudah itu.',
    lead: 'Tempel tautan, pilih kualitas, dan VidSnare mengurus sisanya. Gratis untuk penggunaan pribadi di Windows dan Linux.',
    downloadFor: 'Unduh untuk {os}',
    otherDownloads: 'Unduhan lainnya',
    version: 'Versi {version}',
    comingSoon: 'Rilis pertama segera hadir.',
    onlyWinLinux: 'VidSnare tersedia untuk Windows dan Linux.',
    fileWindows: 'Windows 10 dan 11 – penginstal',
    fileAppImage: 'Linux – AppImage, semua distribusi',
    fileDeb: 'Linux – paket Debian / Ubuntu',
    featuresTitle: 'Fiturnya',
    f1Title: 'Playlist dan channel',
    f1: 'Muat seluruh playlist atau channel dan pilih video yang Anda inginkan.',
    f2Title: 'Video atau audio',
    f2: 'Video hingga 4K, atau hanya suaranya sebagai MP3, M4A, atau Opus.',
    f3Title: 'Subtitle',
    f3: 'Subtitle dalam bahasa pilihan Anda, sebagai file atau di dalam video.',
    f4Title: 'Antrean unduhan',
    f4: 'Beberapa unduhan sekaligus, dengan progres, kecepatan, dan sisa waktu.',
    f5Title: 'Selalu terbaru',
    f5: 'VidSnare dan mesin unduhnya memperbarui diri secara otomatis.',
    f6Title: 'Bahasa Anda',
    f6: 'Tersedia dalam 26 bahasa, dengan tema terang dan gelap.',
    shotDownload: 'Memilih video dari playlist',
    shotQueue: 'Antrean unduhan',
    installTitle: 'Pemasangan',
    installWindows: 'Windows mungkin menampilkan “penerbit tidak dikenal” saat pertama kali, karena VidSnare belum ditandatangani. Klik “Info selengkapnya”, lalu “Tetap jalankan”.',
    installLinux: 'Untuk AppImage, izinkan dijalankan sebagai program (klik kanan → Properti → Izin), lalu buka.',
    disclaimer: 'Anda bertanggung jawab mematuhi Persyaratan Layanan YouTube dan hukum hak cipta. Unduh hanya konten yang berhak Anda unduh.',
    license: 'Gratis untuk penggunaan pribadi dan non-komersial.',
    source: 'Kode sumber',
    notAffiliated: 'Tidak berafiliasi dengan YouTube atau Google.',
    language: 'Bahasa'
  },
  vi: {
    title: 'VidSnare – tải video và âm thanh từ YouTube',
    tagline: 'Tải video và nhạc từ YouTube. Thật đơn giản.',
    lead: 'Dán liên kết, chọn chất lượng, VidSnare lo phần còn lại. Miễn phí cho mục đích cá nhân trên Windows và Linux.',
    downloadFor: 'Tải cho {os}',
    otherDownloads: 'Bản tải khác',
    version: 'Phiên bản {version}',
    comingSoon: 'Bản phát hành đầu tiên sắp ra mắt.',
    onlyWinLinux: 'VidSnare có cho Windows và Linux.',
    fileWindows: 'Windows 10 và 11 – trình cài đặt',
    fileAppImage: 'Linux – AppImage, mọi bản phân phối',
    fileDeb: 'Linux – gói Debian / Ubuntu',
    featuresTitle: 'Tính năng',
    f1Title: 'Danh sách phát và kênh',
    f1: 'Tải cả danh sách phát hoặc kênh và chọn đúng những video bạn muốn.',
    f2Title: 'Video hoặc âm thanh',
    f2: 'Video tới 4K, hoặc chỉ âm thanh dạng MP3, M4A hay Opus.',
    f3Title: 'Phụ đề',
    f3: 'Phụ đề theo ngôn ngữ bạn chọn, dạng tệp riêng hoặc nhúng vào video.',
    f4Title: 'Hàng chờ tải',
    f4: 'Tải nhiều mục cùng lúc, có tiến trình, tốc độ và thời gian còn lại.',
    f5Title: 'Luôn cập nhật',
    f5: 'VidSnare và công cụ tải xuống tự động cập nhật.',
    f6Title: 'Ngôn ngữ của bạn',
    f6: 'Có 26 ngôn ngữ, với giao diện sáng và tối.',
    shotDownload: 'Chọn video từ danh sách phát',
    shotQueue: 'Hàng chờ tải',
    installTitle: 'Cài đặt',
    installWindows: 'Lần đầu, Windows có thể báo “nhà phát hành không xác định” vì VidSnare chưa được ký số. Nhấn “Thông tin thêm”, rồi “Vẫn chạy”.',
    installLinux: 'Với AppImage, hãy cho phép chạy như chương trình (chuột phải → Thuộc tính → Quyền), rồi mở nó.',
    disclaimer: 'Bạn chịu trách nhiệm tuân thủ Điều khoản dịch vụ của YouTube và luật bản quyền. Chỉ tải nội dung mà bạn có quyền tải.',
    license: 'Miễn phí cho mục đích cá nhân, phi thương mại.',
    source: 'Mã nguồn',
    notAffiliated: 'Không liên kết với YouTube hay Google.',
    language: 'Ngôn ngữ'
  },
  ko: {
    title: 'VidSnare – YouTube 동영상과 오디오 다운로드',
    tagline: 'YouTube 동영상과 음악을 간단하게 다운로드하세요.',
    lead: '링크를 붙여넣고 화질만 고르면 나머지는 VidSnare가 처리합니다. Windows와 Linux에서 개인 용도로 무료입니다.',
    downloadFor: '{os}용 다운로드',
    otherDownloads: '다른 다운로드',
    version: '버전 {version}',
    comingSoon: '첫 번째 릴리스가 곧 나옵니다.',
    onlyWinLinux: 'VidSnare는 Windows와 Linux를 지원합니다.',
    fileWindows: 'Windows 10 및 11 – 설치 프로그램',
    fileAppImage: 'Linux – AppImage, 모든 배포판',
    fileDeb: 'Linux – Debian / Ubuntu 패키지',
    featuresTitle: '주요 기능',
    f1Title: '재생목록과 채널',
    f1: '재생목록이나 채널 전체를 불러와 원하는 동영상만 골라 받으세요.',
    f2Title: '동영상 또는 오디오',
    f2: '최대 4K 동영상, 또는 MP3·M4A·Opus 오디오만 저장.',
    f3Title: '자막',
    f3: '원하는 언어의 자막을 파일로 저장하거나 동영상에 포함하세요.',
    f4Title: '다운로드 대기열',
    f4: '여러 개를 동시에 다운로드하며 진행 상황, 속도, 남은 시간을 표시합니다.',
    f5Title: '항상 최신',
    f5: 'VidSnare와 다운로드 엔진은 자동으로 업데이트됩니다.',
    f6Title: '여러분의 언어로',
    f6: '26개 언어 지원, 라이트·다크 테마 제공.',
    shotDownload: '재생목록에서 동영상 고르기',
    shotQueue: '다운로드 대기열',
    installTitle: '설치',
    installWindows: 'VidSnare는 아직 코드 서명이 없어서 처음 실행할 때 Windows가 “알 수 없는 게시자”라고 표시할 수 있습니다. “추가 정보”를 누른 뒤 “실행”을 클릭하세요.',
    installLinux: 'AppImage는 프로그램으로 실행할 수 있게 허용한 뒤(오른쪽 클릭 → 속성 → 권한) 여세요.',
    disclaimer: 'YouTube 서비스 약관과 저작권법을 지킬 책임은 사용자에게 있습니다. 다운로드할 권리가 있는 콘텐츠만 다운로드하세요.',
    license: '개인적·비상업적 용도로 무료입니다.',
    source: '소스 코드',
    notAffiliated: 'YouTube 및 Google과 관련이 없습니다.',
    language: '언어'
  },
  'zh-TW': {
    title: 'VidSnare – 下載 YouTube 影片與音訊',
    tagline: '輕鬆下載 YouTube 影片和音樂。',
    lead: '貼上連結、選擇畫質，其餘交給 VidSnare。Windows 和 Linux 個人使用免費。',
    downloadFor: '下載 {os} 版',
    otherDownloads: '其他下載',
    version: '版本 {version}',
    comingSoon: '第一個版本即將推出。',
    onlyWinLinux: 'VidSnare 支援 Windows 和 Linux。',
    fileWindows: 'Windows 10 和 11 – 安裝程式',
    fileAppImage: 'Linux – AppImage，適用所有發行版',
    fileDeb: 'Linux – Debian / Ubuntu 套件',
    featuresTitle: '功能',
    f1Title: '播放清單與頻道',
    f1: '載入整個播放清單或頻道，只挑你想要的影片。',
    f2Title: '影片或音訊',
    f2: '最高 4K 影片，或只存音訊（MP3、M4A、Opus）。',
    f3Title: '字幕',
    f3: '下載你選擇語言的字幕，可存成檔案或嵌入影片。',
    f4Title: '下載佇列',
    f4: '同時下載多個項目，顯示進度、速度和剩餘時間。',
    f5Title: '隨時保持最新',
    f5: 'VidSnare 和下載引擎會自動更新。',
    f6Title: '你的語言',
    f6: '支援 26 種語言，提供淺色和深色主題。',
    shotDownload: '從播放清單挑選影片',
    shotQueue: '下載佇列',
    installTitle: '安裝',
    installWindows: '由於 VidSnare 尚未經過程式碼簽署，第一次執行時 Windows 可能顯示「不明的發行者」。請點選「其他資訊」，再點選「仍要執行」。',
    installLinux: 'AppImage 需要先允許以程式執行（按右鍵 → 內容 → 權限），然後再開啟。',
    disclaimer: '遵守 YouTube 服務條款和著作權法是您的責任。請只下載您有權下載的內容。',
    license: '個人非商業使用免費。',
    source: '原始碼',
    notAffiliated: '與 YouTube 或 Google 無關。',
    language: '語言'
  },
  hi: {
    title: 'VidSnare – YouTube से वीडियो और ऑडियो डाउनलोड करें',
    tagline: 'YouTube से वीडियो और म्यूज़िक डाउनलोड करें। बिल्कुल आसान।',
    lead: 'लिंक चिपकाएँ, क्वालिटी चुनें, बाकी VidSnare कर देगा। Windows और Linux पर निजी इस्तेमाल के लिए मुफ़्त।',
    downloadFor: '{os} के लिए डाउनलोड करें',
    otherDownloads: 'दूसरे डाउनलोड',
    version: 'वर्शन {version}',
    comingSoon: 'पहला रिलीज़ जल्द आ रहा है।',
    onlyWinLinux: 'VidSnare Windows और Linux के लिए उपलब्ध है।',
    fileWindows: 'Windows 10 और 11 – इंस्टॉलर',
    fileAppImage: 'Linux – AppImage, हर डिस्ट्रीब्यूशन',
    fileDeb: 'Linux – Debian / Ubuntu पैकेज',
    featuresTitle: 'यह क्या करता है',
    f1Title: 'प्लेलिस्ट और चैनल',
    f1: 'पूरी प्लेलिस्ट या चैनल लोड करें और ठीक वही वीडियो चुनें जो चाहिए।',
    f2Title: 'वीडियो या ऑडियो',
    f2: '4K तक वीडियो, या सिर्फ़ आवाज़ MP3, M4A या Opus में।',
    f3Title: 'सबटाइटल',
    f3: 'अपनी चुनी भाषाओं में सबटाइटल, अलग फ़ाइल में या वीडियो के अंदर।',
    f4Title: 'डाउनलोड कतार',
    f4: 'एक साथ कई डाउनलोड, प्रगति, स्पीड और बचे समय के साथ।',
    f5Title: 'हमेशा अपडेट',
    f5: 'VidSnare और उसका डाउनलोड इंजन अपने-आप अपडेट होते हैं।',
    f6Title: 'आपकी भाषा',
    f6: '26 भाषाओं में, हल्की और गहरी थीम के साथ।',
    shotDownload: 'प्लेलिस्ट से वीडियो चुनना',
    shotQueue: 'डाउनलोड कतार',
    installTitle: 'इंस्टॉल करना',
    installWindows: 'VidSnare पर अभी डिजिटल हस्ताक्षर नहीं है, इसलिए पहली बार Windows “अज्ञात प्रकाशक” दिखा सकता है। “अधिक जानकारी” और फिर “फिर भी चलाएँ” पर क्लिक करें।',
    installLinux: 'AppImage को प्रोग्राम की तरह चलाने की अनुमति दें (राइट-क्लिक → Properties → Permissions), फिर खोलें।',
    disclaimer: 'YouTube की सेवा की शर्तों और कॉपीराइट क़ानून का पालन करना आपकी ज़िम्मेदारी है। सिर्फ़ वही सामग्री डाउनलोड करें जिसे डाउनलोड करने का आपको अधिकार है।',
    license: 'निजी, गैर-व्यावसायिक इस्तेमाल के लिए मुफ़्त।',
    source: 'सोर्स कोड',
    notAffiliated: 'YouTube या Google से संबद्ध नहीं।',
    language: 'भाषा'
  },
  nl: {
    title: 'VidSnare – download video’s en audio van YouTube',
    tagline: 'Download video’s en muziek van YouTube. Gewoon simpel.',
    lead: 'Plak een link, kies de kwaliteit en VidSnare doet de rest. Gratis voor persoonlijk gebruik op Windows en Linux.',
    downloadFor: 'Downloaden voor {os}',
    otherDownloads: 'Andere downloads',
    version: 'Versie {version}',
    comingSoon: 'De eerste versie komt binnenkort.',
    onlyWinLinux: 'VidSnare is er voor Windows en Linux.',
    fileWindows: 'Windows 10 en 11 – installatieprogramma',
    fileAppImage: 'Linux – AppImage, elke distributie',
    fileDeb: 'Linux – Debian-/Ubuntu-pakket',
    featuresTitle: 'Wat het doet',
    f1Title: 'Afspeellijsten en kanalen',
    f1: 'Laad een hele afspeellijst of een kanaal en kies precies de video’s die je wilt.',
    f2Title: 'Video of audio',
    f2: 'Video tot 4K, of alleen het geluid als MP3, M4A of Opus.',
    f3Title: 'Ondertiteling',
    f3: 'Ondertiteling in de talen die je kiest, als bestand of in de video.',
    f4Title: 'Downloadwachtrij',
    f4: 'Meerdere downloads tegelijk, met voortgang, snelheid en resterende tijd.',
    f5Title: 'Altijd up-to-date',
    f5: 'VidSnare en de download-engine werken zichzelf automatisch bij.',
    f6Title: 'Jouw taal',
    f6: 'Beschikbaar in 26 talen, met licht en donker thema.',
    shotDownload: 'Video’s kiezen uit een afspeellijst',
    shotQueue: 'De downloadwachtrij',
    installTitle: 'Installeren',
    installWindows: 'Windows meldt de eerste keer misschien “onbekende uitgever”, omdat VidSnare nog niet ondertekend is. Klik op “Meer informatie” en dan op “Toch uitvoeren”.',
    installLinux: 'Sta bij de AppImage uitvoeren als programma toe (rechtsklik → Eigenschappen → Rechten) en open hem dan.',
    disclaimer: 'Je bent zelf verantwoordelijk voor het naleven van de Servicevoorwaarden van YouTube en het auteursrecht. Download alleen inhoud die je mag downloaden.',
    license: 'Gratis voor persoonlijk, niet-commercieel gebruik.',
    source: 'Broncode',
    notAffiliated: 'Niet verbonden aan YouTube of Google.',
    language: 'Taal'
  },
  cs: {
    title: 'VidSnare – stahujte videa a zvuk z YouTube',
    tagline: 'Stahujte videa a hudbu z YouTube. Jednoduše.',
    lead: 'Vložte odkaz, vyberte kvalitu a zbytek zařídí VidSnare. Zdarma pro osobní použití ve Windows a Linuxu.',
    downloadFor: 'Stáhnout pro {os}',
    otherDownloads: 'Další verze',
    version: 'Verze {version}',
    comingSoon: 'První verze vyjde brzy.',
    onlyWinLinux: 'VidSnare je k dispozici pro Windows a Linux.',
    fileWindows: 'Windows 10 a 11 – instalátor',
    fileAppImage: 'Linux – AppImage, libovolná distribuce',
    fileDeb: 'Linux – balíček Debian / Ubuntu',
    featuresTitle: 'Co umí',
    f1Title: 'Playlisty a kanály',
    f1: 'Načtěte celý playlist nebo kanál a vyberte přesně ta videa, která chcete.',
    f2Title: 'Video, nebo zvuk',
    f2: 'Video až ve 4K, nebo jen zvuk jako MP3, M4A či Opus.',
    f3Title: 'Titulky',
    f3: 'Titulky ve zvolených jazycích, jako soubor nebo přímo ve videu.',
    f4Title: 'Fronta stahování',
    f4: 'Více stahování najednou, s průběhem, rychlostí a zbývajícím časem.',
    f5Title: 'Vždy aktuální',
    f5: 'VidSnare i jeho stahovací jádro se aktualizují samy.',
    f6Title: 'Váš jazyk',
    f6: 'K dispozici ve 26 jazycích, se světlým i tmavým motivem.',
    shotDownload: 'Výběr videí z playlistu',
    shotQueue: 'Fronta stahování',
    installTitle: 'Instalace',
    installWindows: 'Windows mohou poprvé zobrazit „Neznámý vydavatel“, protože VidSnare zatím není digitálně podepsaný. Klikněte na „Další informace“ a pak na „Přesto spustit“.',
    installLinux: 'U AppImage povolte spouštění jako program (pravé tlačítko → Vlastnosti → Oprávnění) a pak ho otevřete.',
    disclaimer: 'Odpovídáte za dodržování smluvních podmínek YouTube a autorského práva. Stahujte jen obsah, ke kterému máte právo.',
    license: 'Zdarma pro osobní, nekomerční použití.',
    source: 'Zdrojový kód',
    notAffiliated: 'Není spojeno s YouTube ani Googlem.',
    language: 'Jazyk'
  },
  ro: {
    title: 'VidSnare – descarcă videoclipuri și audio de pe YouTube',
    tagline: 'Descarcă videoclipuri și muzică de pe YouTube. Simplu.',
    lead: 'Lipește un link, alege calitatea și VidSnare face restul. Gratuit pentru uz personal pe Windows și Linux.',
    downloadFor: 'Descarcă pentru {os}',
    otherDownloads: 'Alte descărcări',
    version: 'Versiunea {version}',
    comingSoon: 'Prima versiune apare în curând.',
    onlyWinLinux: 'VidSnare este disponibil pentru Windows și Linux.',
    fileWindows: 'Windows 10 și 11 – program de instalare',
    fileAppImage: 'Linux – AppImage, orice distribuție',
    fileDeb: 'Linux – pachet Debian / Ubuntu',
    featuresTitle: 'Ce face',
    f1Title: 'Playlisturi și canale',
    f1: 'Încarcă un playlist sau un canal întreg și alege exact videoclipurile pe care le vrei.',
    f2Title: 'Video sau audio',
    f2: 'Video până la 4K sau doar sunetul ca MP3, M4A ori Opus.',
    f3Title: 'Subtitrări',
    f3: 'Subtitrări în limbile alese, ca fișier separat sau în videoclip.',
    f4Title: 'Coadă de descărcări',
    f4: 'Mai multe descărcări simultan, cu progres, viteză și timp rămas.',
    f5Title: 'Mereu actualizat',
    f5: 'VidSnare și motorul său de descărcare se actualizează singure.',
    f6Title: 'Limba ta',
    f6: 'Disponibil în 26 de limbi, cu temă luminoasă și întunecată.',
    shotDownload: 'Alegerea videoclipurilor dintr-un playlist',
    shotQueue: 'Coada de descărcări',
    installTitle: 'Instalare',
    installWindows: 'Prima dată, Windows poate afișa „editor necunoscut”, pentru că VidSnare nu e încă semnat digital. Apasă „Mai multe informații”, apoi „Rulează oricum”.',
    installLinux: 'Pentru AppImage, permite rularea ca program (clic dreapta → Proprietăți → Permisiuni), apoi deschide-l.',
    disclaimer: 'Ești responsabil să respecți Termenii și condițiile YouTube și legea drepturilor de autor. Descarcă doar conținut pe care ai dreptul să-l descarci.',
    license: 'Gratuit pentru uz personal, necomercial.',
    source: 'Cod sursă',
    notAffiliated: 'Nu este afiliat cu YouTube sau Google.',
    language: 'Limbă'
  },
  hu: {
    title: 'VidSnare – videók és hang letöltése a YouTube-ról',
    tagline: 'Videók és zene letöltése a YouTube-ról. Egyszerűen.',
    lead: 'Illessz be egy linket, válaszd ki a minőséget, a többit a VidSnare elintézi. Személyes használatra ingyenes Windowson és Linuxon.',
    downloadFor: 'Letöltés {os} rendszerre',
    otherDownloads: 'További letöltések',
    version: '{version} verzió',
    comingSoon: 'Az első kiadás hamarosan érkezik.',
    onlyWinLinux: 'A VidSnare Windowsra és Linuxra érhető el.',
    fileWindows: 'Windows 10 és 11 – telepítő',
    fileAppImage: 'Linux – AppImage, bármely disztribúció',
    fileDeb: 'Linux – Debian/Ubuntu csomag',
    featuresTitle: 'Mit tud',
    f1Title: 'Lejátszási listák és csatornák',
    f1: 'Tölts be egy teljes listát vagy csatornát, és válaszd ki pontosan a kívánt videókat.',
    f2Title: 'Videó vagy hang',
    f2: 'Videó akár 4K-ban, vagy csak a hang MP3, M4A vagy Opus formátumban.',
    f3Title: 'Feliratok',
    f3: 'Feliratok a választott nyelveken, külön fájlként vagy a videóba ágyazva.',
    f4Title: 'Letöltési sor',
    f4: 'Több letöltés egyszerre, folyamattal, sebességgel és hátralévő idővel.',
    f5Title: 'Mindig naprakész',
    f5: 'A VidSnare és a letöltőmotorja automatikusan frissül.',
    f6Title: 'A te nyelveden',
    f6: '26 nyelven érhető el, világos és sötét témával.',
    shotDownload: 'Videók kiválasztása egy listából',
    shotQueue: 'A letöltési sor',
    installTitle: 'Telepítés',
    installWindows: 'A Windows elsőre „Ismeretlen közzétevő” üzenetet mutathat, mert a VidSnare még nincs digitálisan aláírva. Kattints a „További információ”, majd a „Futtatás mindenképp” gombra.',
    installLinux: 'Az AppImage-nél engedélyezd a programként való futtatást (jobb klikk → Tulajdonságok → Jogosultságok), majd nyisd meg.',
    disclaimer: 'Te felelsz a YouTube Szolgáltatási feltételeinek és a szerzői jognak a betartásáért. Csak olyan tartalmat tölts le, amelyhez jogod van.',
    license: 'Személyes, nem kereskedelmi használatra ingyenes.',
    source: 'Forráskód',
    notAffiliated: 'Nem áll kapcsolatban a YouTube-bal vagy a Google-lel.',
    language: 'Nyelv'
  },
  sv: {
    title: 'VidSnare – ladda ned video och ljud från YouTube',
    tagline: 'Ladda ned video och musik från YouTube. Enkelt.',
    lead: 'Klistra in en länk, välj kvalitet så sköter VidSnare resten. Gratis för privat bruk på Windows och Linux.',
    downloadFor: 'Ladda ned för {os}',
    otherDownloads: 'Andra nedladdningar',
    version: 'Version {version}',
    comingSoon: 'Den första versionen kommer snart.',
    onlyWinLinux: 'VidSnare finns för Windows och Linux.',
    fileWindows: 'Windows 10 och 11 – installationsprogram',
    fileAppImage: 'Linux – AppImage, alla distributioner',
    fileDeb: 'Linux – Debian-/Ubuntu-paket',
    featuresTitle: 'Vad den gör',
    f1Title: 'Spellistor och kanaler',
    f1: 'Läs in en hel spellista eller kanal och välj exakt de videor du vill ha.',
    f2Title: 'Video eller ljud',
    f2: 'Video upp till 4K, eller bara ljudet som MP3, M4A eller Opus.',
    f3Title: 'Undertexter',
    f3: 'Undertexter på de språk du väljer, som fil eller inbäddade i videon.',
    f4Title: 'Nedladdningskö',
    f4: 'Flera nedladdningar samtidigt, med förlopp, hastighet och tid kvar.',
    f5Title: 'Alltid uppdaterad',
    f5: 'VidSnare och dess nedladdningsmotor uppdaterar sig själva.',
    f6Title: 'Ditt språk',
    f6: 'Finns på 26 språk, med ljust och mörkt tema.',
    shotDownload: 'Välja videor från en spellista',
    shotQueue: 'Nedladdningskön',
    installTitle: 'Installation',
    installWindows: 'Windows kan första gången visa ”okänd utgivare” eftersom VidSnare ännu inte är kodsignerad. Klicka på ”Mer information” och sedan ”Kör ändå”.',
    installLinux: 'För AppImage: tillåt körning som program (högerklicka → Egenskaper → Behörigheter) och öppna den sedan.',
    disclaimer: 'Du ansvarar för att följa YouTubes användarvillkor och upphovsrättslagen. Ladda bara ned innehåll som du har rätt att ladda ned.',
    license: 'Gratis för privat, icke-kommersiellt bruk.',
    source: 'Källkod',
    notAffiliated: 'Inte knuten till YouTube eller Google.',
    language: 'Språk'
  },
  el: {
    title: 'VidSnare – κατεβάστε βίντεο και ήχο από το YouTube',
    tagline: 'Κατεβάστε βίντεο και μουσική από το YouTube. Απλά.',
    lead: 'Επικολλήστε έναν σύνδεσμο, επιλέξτε ποιότητα και το VidSnare κάνει τα υπόλοιπα. Δωρεάν για προσωπική χρήση σε Windows και Linux.',
    downloadFor: 'Λήψη για {os}',
    otherDownloads: 'Άλλες λήψεις',
    version: 'Έκδοση {version}',
    comingSoon: 'Η πρώτη έκδοση έρχεται σύντομα.',
    onlyWinLinux: 'Το VidSnare είναι διαθέσιμο για Windows και Linux.',
    fileWindows: 'Windows 10 και 11 – πρόγραμμα εγκατάστασης',
    fileAppImage: 'Linux – AppImage, κάθε διανομή',
    fileDeb: 'Linux – πακέτο Debian / Ubuntu',
    featuresTitle: 'Τι κάνει',
    f1Title: 'Λίστες αναπαραγωγής και κανάλια',
    f1: 'Φορτώστε ολόκληρη λίστα ή κανάλι και επιλέξτε ακριβώς τα βίντεο που θέλετε.',
    f2Title: 'Βίντεο ή ήχος',
    f2: 'Βίντεο έως 4K ή μόνο ο ήχος σε MP3, M4A ή Opus.',
    f3Title: 'Υπότιτλοι',
    f3: 'Υπότιτλοι στις γλώσσες που επιλέγετε, ως αρχείο ή μέσα στο βίντεο.',
    f4Title: 'Ουρά λήψεων',
    f4: 'Πολλές λήψεις ταυτόχρονα, με πρόοδο, ταχύτητα και χρόνο που απομένει.',
    f5Title: 'Πάντα ενημερωμένο',
    f5: 'Το VidSnare και η μηχανή λήψης του ενημερώνονται αυτόματα.',
    f6Title: 'Η γλώσσα σας',
    f6: 'Διαθέσιμο σε 26 γλώσσες, με ανοιχτό και σκούρο θέμα.',
    shotDownload: 'Επιλογή βίντεο από λίστα αναπαραγωγής',
    shotQueue: 'Η ουρά λήψεων',
    installTitle: 'Εγκατάσταση',
    installWindows: 'Την πρώτη φορά τα Windows μπορεί να δείξουν «Άγνωστος εκδότης», επειδή το VidSnare δεν έχει ακόμη ψηφιακή υπογραφή. Πατήστε «Περισσότερες πληροφορίες» και μετά «Εκτέλεση οπωσδήποτε».',
    installLinux: 'Για το AppImage, επιτρέψτε την εκτέλεση ως πρόγραμμα (δεξί κλικ → Ιδιότητες → Δικαιώματα) και ανοίξτε το.',
    disclaimer: 'Είστε υπεύθυνοι για την τήρηση των Όρων Παροχής Υπηρεσιών του YouTube και της νομοθεσίας για τα πνευματικά δικαιώματα. Κατεβάζετε μόνο περιεχόμενο που έχετε δικαίωμα να κατεβάσετε.',
    license: 'Δωρεάν για προσωπική, μη εμπορική χρήση.',
    source: 'Πηγαίος κώδικας',
    notAffiliated: 'Δεν συνδέεται με το YouTube ή την Google.',
    language: 'Γλώσσα'
  },
  th: {
    title: 'VidSnare – ดาวน์โหลดวิดีโอและเสียงจาก YouTube',
    tagline: 'ดาวน์โหลดวิดีโอและเพลงจาก YouTube ง่าย ๆ',
    lead: 'วางลิงก์ เลือกคุณภาพ แล้ว VidSnare จะจัดการที่เหลือให้ ใช้ฟรีสำหรับการใช้งานส่วนตัวบน Windows และ Linux',
    downloadFor: 'ดาวน์โหลดสำหรับ {os}',
    otherDownloads: 'ดาวน์โหลดอื่น ๆ',
    version: 'เวอร์ชัน {version}',
    comingSoon: 'รุ่นแรกกำลังจะมาเร็ว ๆ นี้',
    onlyWinLinux: 'VidSnare ใช้ได้บน Windows และ Linux',
    fileWindows: 'Windows 10 และ 11 – ตัวติดตั้ง',
    fileAppImage: 'Linux – AppImage ใช้ได้ทุกดิสทริบิวชัน',
    fileDeb: 'Linux – แพ็กเกจ Debian / Ubuntu',
    featuresTitle: 'ทำอะไรได้บ้าง',
    f1Title: 'เพลย์ลิสต์และช่อง',
    f1: 'โหลดทั้งเพลย์ลิสต์หรือทั้งช่อง แล้วเลือกเฉพาะวิดีโอที่ต้องการ',
    f2Title: 'วิดีโอหรือเสียง',
    f2: 'วิดีโอสูงสุด 4K หรือเฉพาะเสียงเป็น MP3, M4A หรือ Opus',
    f3Title: 'คำบรรยาย',
    f3: 'คำบรรยายในภาษาที่คุณเลือก เป็นไฟล์แยกหรือฝังในวิดีโอ',
    f4Title: 'คิวดาวน์โหลด',
    f4: 'ดาวน์โหลดหลายรายการพร้อมกัน พร้อมแสดงความคืบหน้า ความเร็ว และเวลาที่เหลือ',
    f5Title: 'อัปเดตอยู่เสมอ',
    f5: 'VidSnare และเอนจินดาวน์โหลดอัปเดตตัวเองโดยอัตโนมัติ',
    f6Title: 'ภาษาของคุณ',
    f6: 'มีให้เลือก 26 ภาษา พร้อมธีมสว่างและมืด',
    shotDownload: 'เลือกวิดีโอจากเพลย์ลิสต์',
    shotQueue: 'คิวดาวน์โหลด',
    installTitle: 'การติดตั้ง',
    installWindows: 'ครั้งแรก Windows อาจแสดงว่า “ผู้เผยแพร่ที่ไม่รู้จัก” เพราะ VidSnare ยังไม่ได้ลงนามรหัส คลิก “ข้อมูลเพิ่มเติม” แล้วคลิก “เรียกใช้ต่อไป”',
    installLinux: 'สำหรับ AppImage ให้อนุญาตให้เรียกใช้เป็นโปรแกรม (คลิกขวา → คุณสมบัติ → สิทธิ์) แล้วจึงเปิด',
    disclaimer: 'คุณมีหน้าที่ปฏิบัติตามข้อกำหนดในการให้บริการของ YouTube และกฎหมายลิขสิทธิ์ โปรดดาวน์โหลดเฉพาะเนื้อหาที่คุณมีสิทธิ์ดาวน์โหลด',
    license: 'ใช้ฟรีสำหรับการใช้งานส่วนตัวที่ไม่ใช่เชิงพาณิชย์',
    source: 'ซอร์สโค้ด',
    notAffiliated: 'ไม่มีส่วนเกี่ยวข้องกับ YouTube หรือ Google',
    language: 'ภาษา'
  },
  ar: {
    title: 'VidSnare – نزّل الفيديوهات والصوت من YouTube',
    tagline: 'نزّل الفيديوهات والموسيقى من YouTube ببساطة.',
    lead: 'الصق رابطًا واختر الجودة، ويتولى VidSnare الباقي. مجاني للاستخدام الشخصي على Windows وLinux.',
    downloadFor: 'تنزيل لنظام {os}',
    otherDownloads: 'تنزيلات أخرى',
    version: 'الإصدار {version}',
    comingSoon: 'الإصدار الأول قادم قريبًا.',
    onlyWinLinux: 'VidSnare متاح لنظامي Windows وLinux.',
    fileWindows: 'Windows 10 و11 – برنامج التثبيت',
    fileAppImage: 'Linux – AppImage لكل التوزيعات',
    fileDeb: 'Linux – حزمة Debian / Ubuntu',
    featuresTitle: 'ماذا يقدّم',
    f1Title: 'قوائم التشغيل والقنوات',
    f1: 'حمّل قائمة تشغيل أو قناة كاملة واختر الفيديوهات التي تريدها بالضبط.',
    f2Title: 'فيديو أو صوت',
    f2: 'فيديو حتى 4K، أو الصوت فقط بصيغة MP3 أو M4A أو Opus.',
    f3Title: 'الترجمة',
    f3: 'ترجمة باللغات التي تختارها، كملف منفصل أو داخل الفيديو.',
    f4Title: 'قائمة انتظار التنزيل',
    f4: 'عدة تنزيلات في وقت واحد، مع التقدم والسرعة والوقت المتبقي.',
    f5Title: 'محدّث دائمًا',
    f5: 'يحدّث VidSnare نفسه ومحرك التنزيل تلقائيًا.',
    f6Title: 'بلغتك',
    f6: 'متاح بـ 26 لغة، مع سمة فاتحة وأخرى داكنة.',
    shotDownload: 'اختيار فيديوهات من قائمة تشغيل',
    shotQueue: 'قائمة انتظار التنزيل',
    installTitle: 'التثبيت',
    installWindows: 'قد يعرض Windows في المرة الأولى «ناشر غير معروف» لأن VidSnare غير موقّع رقميًا بعد. انقر «مزيد من المعلومات» ثم «التشغيل على أي حال».',
    installLinux: 'بالنسبة إلى AppImage، اسمح بتشغيله كبرنامج (نقرة يمنى ← خصائص ← الأذونات)، ثم افتحه.',
    disclaimer: 'أنت مسؤول عن الالتزام بشروط خدمة YouTube وقوانين حقوق النشر. لا تنزّل إلا المحتوى الذي يحق لك تنزيله.',
    license: 'مجاني للاستخدام الشخصي غير التجاري.',
    source: 'الشيفرة المصدرية',
    notAffiliated: 'غير تابع لـ YouTube أو Google.',
    language: 'اللغة'
  },
  fa: {
    title: 'VidSnare – بارگیری ویدیو و صدا از YouTube',
    tagline: 'ویدیو و موسیقی را از YouTube بارگیری کنید. به همین سادگی.',
    lead: 'پیوند را بچسبانید، کیفیت را انتخاب کنید و بقیه را به VidSnare بسپارید. برای استفادهٔ شخصی روی Windows و Linux رایگان است.',
    downloadFor: 'بارگیری برای {os}',
    otherDownloads: 'بارگیری‌های دیگر',
    version: 'نسخهٔ {version}',
    comingSoon: 'نخستین نسخه به‌زودی منتشر می‌شود.',
    onlyWinLinux: 'VidSnare برای Windows و Linux در دسترس است.',
    fileWindows: 'Windows 10 و 11 – برنامهٔ نصب',
    fileAppImage: 'Linux – AppImage برای همهٔ توزیع‌ها',
    fileDeb: 'Linux – بستهٔ Debian / Ubuntu',
    featuresTitle: 'چه کارهایی می‌کند',
    f1Title: 'فهرست‌های پخش و کانال‌ها',
    f1: 'کل یک فهرست پخش یا کانال را بارگذاری کنید و دقیقاً ویدیوهای دلخواه را انتخاب کنید.',
    f2Title: 'ویدیو یا صدا',
    f2: 'ویدیو تا کیفیت 4K، یا فقط صدا با قالب MP3، M4A یا Opus.',
    f3Title: 'زیرنویس',
    f3: 'زیرنویس به زبان‌های دلخواه، به‌صورت فایل جدا یا درون ویدیو.',
    f4Title: 'صف بارگیری',
    f4: 'چند بارگیری هم‌زمان، با نمایش پیشرفت، سرعت و زمان باقی‌مانده.',
    f5Title: 'همیشه به‌روز',
    f5: 'VidSnare و موتور بارگیری‌اش به‌طور خودکار به‌روز می‌شوند.',
    f6Title: 'به زبان شما',
    f6: 'در ۲۶ زبان، با پوستهٔ روشن و تیره.',
    shotDownload: 'انتخاب ویدیو از فهرست پخش',
    shotQueue: 'صف بارگیری',
    installTitle: 'نصب',
    installWindows: 'چون VidSnare هنوز امضای دیجیتال ندارد، Windows ممکن است بار اول «ناشر ناشناس» نشان دهد. روی «اطلاعات بیشتر» و سپس «به هر حال اجرا شود» کلیک کنید.',
    installLinux: 'برای AppImage اجازهٔ اجرا به‌عنوان برنامه را بدهید (کلیک راست ← ویژگی‌ها ← مجوزها) و سپس آن را باز کنید.',
    disclaimer: 'رعایت شرایط خدمات YouTube و قانون حق نشر بر عهدهٔ شماست. فقط محتوایی را بارگیری کنید که حق بارگیری آن را دارید.',
    license: 'برای استفادهٔ شخصی و غیرتجاری رایگان است.',
    source: 'کد منبع',
    notAffiliated: 'وابسته به YouTube یا Google نیست.',
    language: 'زبان'
  },
  he: {
    title: 'VidSnare – הורדת סרטונים ושמע מ-YouTube',
    tagline: 'הורידו סרטונים ומוזיקה מ-YouTube. פשוט.',
    lead: 'הדביקו קישור, בחרו איכות, ו-VidSnare יעשה את השאר. חינם לשימוש אישי ב-Windows וב-Linux.',
    downloadFor: 'הורדה ל-{os}',
    otherDownloads: 'הורדות נוספות',
    version: 'גרסה {version}',
    comingSoon: 'הגרסה הראשונה תצא בקרוב.',
    onlyWinLinux: 'VidSnare זמין ל-Windows ול-Linux.',
    fileWindows: 'Windows 10 ו-11 – תוכנת התקנה',
    fileAppImage: 'Linux – AppImage לכל ההפצות',
    fileDeb: 'Linux – חבילת Debian / Ubuntu',
    featuresTitle: 'מה הוא עושה',
    f1Title: 'פלייליסטים וערוצים',
    f1: 'טענו פלייליסט או ערוץ שלם ובחרו בדיוק את הסרטונים שתרצו.',
    f2Title: 'וידאו או שמע',
    f2: 'וידאו עד 4K, או רק השמע בפורמט MP3, ‏M4A או Opus.',
    f3Title: 'כתוביות',
    f3: 'כתוביות בשפות שתבחרו, כקובץ נפרד או בתוך הסרטון.',
    f4Title: 'תור הורדות',
    f4: 'כמה הורדות במקביל, עם התקדמות, מהירות וזמן שנותר.',
    f5Title: 'תמיד מעודכן',
    f5: 'VidSnare ומנוע ההורדה שלו מתעדכנים אוטומטית.',
    f6Title: 'בשפה שלכם',
    f6: 'זמין ב-26 שפות, עם ערכת נושא בהירה וכהה.',
    shotDownload: 'בחירת סרטונים מפלייליסט',
    shotQueue: 'תור ההורדות',
    installTitle: 'התקנה',
    installWindows: 'בפעם הראשונה Windows עשוי להציג „מפרסם לא ידוע”, כי VidSnare עדיין לא חתום דיגיטלית. לחצו על „מידע נוסף” ואז על „הפעל בכל זאת”.',
    installLinux: 'בקובץ AppImage אפשרו הרצה כתוכנה (לחיצה ימנית ← מאפיינים ← הרשאות), ואז פתחו אותו.',
    disclaimer: 'האחריות לעמוד בתנאים וההגבלות של YouTube ובדיני זכויות היוצרים היא שלכם. הורידו רק תוכן שיש לכם זכות להוריד.',
    license: 'חינם לשימוש אישי שאינו מסחרי.',
    source: 'קוד מקור',
    notAffiliated: 'לא קשור ל-YouTube או ל-Google.',
    language: 'שפה'
  }
}

export const LANGUAGE_NAMES = {
  en: 'English',
  pl: 'Polski',
  de: 'Deutsch',
  es: 'Español',
  'pt-BR': 'Português (Brasil)',
  ru: 'Русский',
  ja: '日本語',
  fr: 'Français',
  tr: 'Türkçe',
  it: 'Italiano',
  uk: 'Українська',
  id: 'Bahasa Indonesia',
  vi: 'Tiếng Việt',
  ko: '한국어',
  'zh-TW': '繁體中文',
  hi: 'हिन्दी',
  nl: 'Nederlands',
  cs: 'Čeština',
  ro: 'Română',
  hu: 'Magyar',
  sv: 'Svenska',
  el: 'Ελληνικά',
  th: 'ไทย',
  ar: 'العربية',
  fa: 'فارسی',
  he: 'עברית'
}

/** Written right to left; the page mirrors for these. */
export const RTL = ['ar', 'fa', 'he']
