import { join } from 'node:path'
import { describe, expect, it, vi } from 'vitest'
import type { DownloadOptions } from '@shared/download'
import type { DownloadJob, QueueItem } from '@shared/queue'
import type { RunOptions, RunResult, Runner } from '../core/runner'
import { DownloadQueue, finalExtension, type NewJob, type QueueDeps } from './download-queue'

const OUT = join('/home', 'u', 'Downloads')

const video: DownloadOptions = {
  kind: 'video',
  quality: 'best',
  container: 'mp4',
  audioFormat: 'mp3',
  subtitles: { enabled: false, languages: [], includeAutoGenerated: false, embed: false }
}

const item = (n: number, title = `Video ${n}`): QueueItem => ({
  videoId: `vid${String(n).padStart(8, '0')}`,
  title,
  channel: 'Channel',
  thumbnail: null,
  duration: 60,
  uploadDate: null,
  index: n
})

const spec = (n: number, overrides: Partial<NewJob> = {}): NewJob => ({
  item: item(n),
  options: video,
  outputDir: OUT,
  filenameTemplate: '{title} [{id}]',
  playlistCount: null,
  ...overrides
})

interface FakeRun {
  args: string[]
  options: RunOptions
  emit(...lines: string[]): void
  finish(result?: Partial<RunResult>): void
}

/** A yt-dlp stand-in whose output and exit the test controls. */
function fakeRunner(): Runner & { runs: FakeRun[] } {
  const runs: FakeRun[] = []
  const runner = ((_cmd: string, args: string[], options: RunOptions = {}) =>
    new Promise<RunResult>((resolve) => {
      const done = (result: Partial<RunResult> = {}): void =>
        resolve({ code: 0, stdout: '', stderr: '', cancelled: false, timedOut: false, ...result })
      options.signal?.addEventListener('abort', () => done({ code: null, cancelled: true }))
      runs.push({
        args,
        options,
        emit: (...lines) => lines.forEach((l) => options.onLine?.(l, 'stdout')),
        finish: done
      })
    })) as Runner & { runs: FakeRun[] }
  runner.runs = runs
  return runner
}

const tick = (): Promise<void> => new Promise((r) => setTimeout(r, 0))
async function settle(): Promise<void> {
  for (let i = 0; i < 5; i++) await tick()
}

function setup(overrides: Partial<QueueDeps> = {}) {
  const run = fakeRunner()
  const finished: DownloadJob[] = []
  let id = 0
  const deps: QueueDeps = {
    run,
    tools: async () => ({ ytdlp: '/t/yt-dlp', ffmpeg: '/t', deno: '/t/deno' }),
    tempRoot: '/tmp/vs',
    maxConcurrent: () => 2,
    archiveFile: () => undefined,
    onFinished: (job) => finished.push(job),
    fileExists: async () => false,
    fileSize: async () => null,
    now: () => 1000,
    newId: () => `job${++id}`,
    ...overrides
  }
  const queue = new DownloadQueue(deps)
  return { queue, run, finished }
}

const status = (queue: DownloadQueue): string[] => queue.list().map((j) => j.status)

describe('DownloadQueue', () => {
  it('runs at most the configured number of downloads at once', async () => {
    const { queue, run } = setup()
    queue.add([spec(1), spec(2), spec(3)])
    await settle()
    expect(run.runs).toHaveLength(2)
    expect(status(queue)).toEqual(['downloading', 'downloading', 'queued'])

    run.runs[0]!.finish()
    await settle()
    expect(run.runs).toHaveLength(3)
    expect(status(queue)).toEqual(['completed', 'downloading', 'downloading'])
  })

  it('starts more when the limit is raised', async () => {
    let limit = 1
    const { queue, run } = setup({ maxConcurrent: () => limit })
    queue.add([spec(1), spec(2), spec(3)])
    await settle()
    expect(run.runs).toHaveLength(1)
    limit = 3
    queue.pump()
    await settle()
    expect(run.runs).toHaveLength(3)
  })

  it('passes the right arguments to yt-dlp', async () => {
    const { queue, run } = setup({ archiveFile: () => '/data/archive.txt' })
    queue.add([spec(1)])
    await settle()
    const args = run.runs[0]!.args
    expect(args.slice(-1)[0]).toBe('https://www.youtube.com/watch?v=vid00000001')
    expect(args).toContain('Video 1 [vid00000001].%(ext)s')
    expect(args).toContain(`temp:${join('/tmp/vs', 'job1')}`)
    expect(args).toContain('/data/archive.txt')
    expect(args).toContain('deno:/t/deno')
  })

  it('reports progress and finishes with the file path', async () => {
    const onChange = vi.fn()
    const { queue, run, finished } = setup({ onChange })
    queue.add([spec(1)])
    await settle()
    run.runs[0]!.emit('__VS_DL__ downloading|500|1000|NA|2000|1|137')
    expect(queue.list()[0]!.progress).toMatchObject({ fraction: 0.25, speed: 2000, eta: 1 })

    run.runs[0]!.emit('__VS_DL__ finished|1000|1000|NA|2000|NA|137', '__VS_DL__ downloading|100|100|NA|50|0|140')
    run.runs[0]!.emit('__VS_PP__ started|Merger')
    expect(queue.list()[0]!.status).toBe('processing')

    run.runs[0]!.emit(`__VS_FILE__ ${join(OUT, 'Video 1 [vid00000001].mp4')}`)
    run.runs[0]!.finish()
    await settle()
    const job = queue.list()[0]!
    expect(job).toMatchObject({ status: 'completed', filePath: join(OUT, 'Video 1 [vid00000001].mp4'), finishedAt: 1000 })
    expect(job.progress).toMatchObject({ fraction: 1, speed: null, eta: null })
    expect(finished).toHaveLength(1)
    expect(onChange).toHaveBeenCalled()
  })

  it('reports the size of the finished file, not of the downloaded streams', async () => {
    const { queue, run } = setup({ fileSize: async () => 669_088 })
    queue.add([spec(1, { options: { ...video, kind: 'audio' } })])
    await settle()
    run.runs[0]!.emit('__VS_DL__ finished|252182|252182|NA|1000|NA|251')
    run.runs[0]!.finish()
    await settle()
    expect(queue.list()[0]!.progress).toEqual({
      fraction: 1,
      downloadedBytes: 669_088,
      totalBytes: 669_088,
      speed: null,
      eta: null
    })
  })

  it('uses the expected path when yt-dlp does not print one', async () => {
    const { queue, run } = setup()
    queue.add([spec(1, { options: { ...video, kind: 'audio', audioFormat: 'opus' } })])
    await settle()
    run.runs[0]!.finish()
    await settle()
    expect(queue.list()[0]!.filePath).toBe(join(OUT, 'Video 1 [vid00000001].opus'))
  })

  it('marks archive hits as skipped', async () => {
    const { queue, run } = setup()
    queue.add([spec(1)])
    await settle()
    run.runs[0]!.emit('[download] Video 1 has already been recorded in the archive')
    run.runs[0]!.finish()
    await settle()
    expect(status(queue)).toEqual(['skipped'])
  })

  it('explains failures', async () => {
    const { queue, run, finished } = setup()
    queue.add([spec(1)])
    await settle()
    run.runs[0]!.finish({ code: 1, stderr: 'ERROR: [youtube] x: Private video. Sign in' })
    await settle()
    expect(queue.list()[0]).toMatchObject({ status: 'failed', error: { code: 'PRIVATE_VIDEO' } })
    expect(finished[0]?.status).toBe('failed')
  })

  it('fails clearly when the engine is missing', async () => {
    const { queue, run } = setup({ tools: async () => ({ ytdlp: null }) })
    queue.add([spec(1)])
    await settle()
    expect(run.runs).toHaveLength(0)
    expect(queue.list()[0]).toMatchObject({ status: 'failed', error: { code: 'TOOL_MISSING' } })
  })

  it('handles a program that cannot start', async () => {
    const run: Runner = async () => Promise.reject(Object.assign(new Error('spawn'), { code: 'ENOENT' }))
    const { queue } = setup({ run: run as never })
    queue.add([spec(1)])
    await settle()
    expect(queue.list()[0]).toMatchObject({ status: 'failed', error: { code: 'TOOL_MISSING' } })
  })

  describe('cancel', () => {
    it('cancels a waiting job without running it', async () => {
      const { queue, run } = setup({ maxConcurrent: () => 1 })
      const [, second] = queue.add([spec(1), spec(2)])
      await settle()
      queue.cancel(second!.id)
      run.runs[0]!.finish()
      await settle()
      expect(run.runs).toHaveLength(1)
      expect(status(queue)).toEqual(['completed', 'cancelled'])
    })

    it('stops a running job and starts the next', async () => {
      const { queue, run } = setup({ maxConcurrent: () => 1 })
      const [first] = queue.add([spec(1), spec(2)])
      await settle()
      queue.cancel(first!.id)
      await settle()
      expect(run.runs[0]!.options.signal?.aborted).toBe(true)
      expect(status(queue)).toEqual(['cancelled', 'downloading'])
    })

    it('cancels everything', async () => {
      const { queue } = setup({ maxConcurrent: () => 1 })
      queue.add([spec(1), spec(2), spec(3)])
      await settle()
      queue.cancelAll()
      await settle()
      expect(status(queue)).toEqual(['cancelled', 'cancelled', 'cancelled'])
    })

    it('ignores finished jobs', async () => {
      const { queue, run } = setup()
      const [job] = queue.add([spec(1)])
      await settle()
      run.runs[0]!.finish()
      await settle()
      queue.cancel(job!.id)
      expect(status(queue)).toEqual(['completed'])
    })
  })

  describe('retry', () => {
    it('runs a failed job again', async () => {
      const { queue, run } = setup()
      const [job] = queue.add([spec(1)])
      await settle()
      run.runs[0]!.finish({ code: 1, stderr: 'ERROR: HTTP Error 429: Too Many Requests' })
      await settle()
      queue.retry(job!.id)
      await settle()
      expect(run.runs).toHaveLength(2)
      expect(queue.list()[0]).toMatchObject({ status: 'downloading', error: null, finishedAt: null })
    })

    it('does not retry completed jobs', async () => {
      const { queue, run } = setup()
      const [job] = queue.add([spec(1)])
      await settle()
      run.runs[0]!.finish()
      await settle()
      queue.retry(job!.id)
      await settle()
      expect(run.runs).toHaveLength(1)
    })

    it('retries every job that failed for a given reason', async () => {
      const { queue, run } = setup()
      queue.add([spec(1), spec(2)])
      await settle()
      run.runs[0]!.finish({ code: 1, stderr: 'ERROR: x: Signature extraction failed' })
      run.runs[1]!.finish({ code: 1, stderr: 'ERROR: x: Private video' })
      await settle()
      expect(queue.retryFailed(['ENGINE_OUTDATED'])).toBe(1)
      await settle()
      expect(status(queue)).toEqual(['downloading', 'failed'])
    })
  })

  describe('file names', () => {
    it('adds a number when the file already exists', async () => {
      const existing = new Set([join(OUT, 'Video 1 [vid00000001].mp4'), join(OUT, 'Video 1 [vid00000001] (2).mp4')])
      const { queue, run } = setup({ fileExists: async (p) => existing.has(p) })
      queue.add([spec(1)])
      await settle()
      expect(run.runs[0]!.args).toContain('Video 1 [vid00000001] (3).%(ext)s')
    })

    it('never gives two running jobs the same name', async () => {
      const { queue, run } = setup()
      const same = (n: number): NewJob => spec(n, { item: { ...item(n), title: 'Same' }, filenameTemplate: '{title}' })
      queue.add([same(1), same(2)])
      await settle()
      const outputs = run.runs.map((r) => r.args[r.args.indexOf('-o') + 1])
      expect(outputs).toEqual(['Same.%(ext)s', 'Same (2).%(ext)s'])
    })

    it('fills playlist fields in the template', async () => {
      const { queue, run } = setup()
      queue.add([spec(7, { filenameTemplate: '{index} - {title}', playlistCount: 120 })])
      await settle()
      expect(run.runs[0]!.args).toContain('007 - Video 7.%(ext)s')
    })
  })

  it('removes and clears finished jobs only', async () => {
    const { queue, run } = setup({ maxConcurrent: () => 1 })
    const [a, b] = queue.add([spec(1), spec(2), spec(3)])
    await settle()
    queue.remove(a!.id) // running: ignored
    expect(queue.list()).toHaveLength(3)
    run.runs[0]!.finish()
    await settle()
    queue.remove(a!.id)
    expect(queue.list().map((j) => j.id)).toEqual([b!.id, 'job3'])
    queue.cancel('job3')
    queue.clearFinished()
    expect(status(queue)).toEqual(['downloading'])
  })

  it('shutdown stops running downloads and waits for them', async () => {
    const { queue } = setup()
    queue.add([spec(1), spec(2)])
    await settle()
    expect(queue.hasUnfinished()).toBe(true)
    await queue.shutdown()
    expect(status(queue)).toEqual(['cancelled', 'cancelled'])
    expect(queue.hasUnfinished()).toBe(false)
  })
})

describe('finalExtension', () => {
  it('follows the chosen format', () => {
    expect(finalExtension(video)).toBe('mp4')
    expect(finalExtension({ ...video, container: 'mkv' })).toBe('mkv')
    expect(finalExtension({ ...video, kind: 'audio', audioFormat: 'm4a' })).toBe('m4a')
  })
})
